### ISSUE TITLE
Is Falcor being actively maintained?

### ISSUE THREAD

**Issue by nat-418** [Netflix/falcor#1016]
I don't see any commits in this repo for the last two years. Is Falcor complete, deprecated, maintained, or some other status?

**Comment by lucidNTR** [comment]
@nat-418  as far as i know falcor is in internal maintainence mode and this repo not updated from netflix upstream anymore. in addition most core devs left netflix in the meantime. i would really love to organize a state of falcor call and decide if this can be handed over to the community (which consists as far as i know just of me at the moment) or if it is time to fork and get some fresh wind behind the project. i have a detailed plan for the future that i am happy to share, but so far i found no one who was interested.

**Comment by PerchunPak** [comment]
I think it can be counted as deprecated because Netflix stopped using it: https://netflixtechblog.com/seamlessly-swapping-the-api-backend-of-the-netflix-android-app-3d4317155187

**Comment by nicolas17** [comment]
> I think it can be counted as deprecated because Netflix stopped using it: https://netflixtechblog.com/seamlessly-swapping-the-api-backend-of-the-netflix-android-app-3d4317155187

I don't see anything there indicating they are no longer using Falcor. It looks like they replaced the server-side software that serves the API but the protocol is still Falcor?

**Comment by lucidNTR** [comment]
https://netflixtechblog.com/migrating-netflix-to-graphql-safely-8e1e4d4f1e72

there are many mentions of netflix moving away from falcor. while they certainly have their reasons falcor still has its place and has no real alternative in many usecases where graphQL is not a good fit! Therefore it would be wrong to call falcor deprecated it is just in a intermediate state where netflix still has the main repo but is moving away from supporting it over the last 2 years.

**Comment by nicolas17** [comment]
> https://netflixtechblog.com/migrating-netflix-to-graphql-safely-8e1e4d4f1e72

Okay, that is a much more relevant post, thanks for sharing!

> there are many mentions of netflix moving away from falcor. while they certainly have their reasons falcor still has its place and has no real alternative in many usecases where graphQL is not a good fit!

I've been looking at GraphQL, and I miss the Falcor feature where objects reached through different paths (like `["userByName"]["lucidNTR"]` vs `["postByID"]["1666638084"]["author"]`) are returned as pointers to *the same* object, using `$type: "ref"`...

**Comment by lucidNTR** [comment]
@nicolas17  yes and also i generate queries automatically but graphQL is too complex to automatically map to simple plain old js object interactions plus i dont want to write schemas for everything up front but only when a project matures, so graphql is a no go for quick mvps and prototypes or anything where iteration speed is critical. lastly falcor is much simpler to reason about, i often have a much harder time having the whole project in my head with complex graphql compared to the same project with falcor

**Comment by bburns** [comment]
The gist I got from the articles was that Falcor didn't scale enough for Netflix and their pace of development, so they moved to GraphQL.

But Falcor looks like a great way to mesh different data sources together without having to predefine schemas - just what I was looking for! :)

**Comment by janfjohannes** [comment]
@bburns  falcor has the same scaling capabilities as graphQL. They neeeded to raplace their monolithic falcor backend with a new architecture and chose graphQL, they could also have rewritten a new falcor server with a different architecture and solved those issues. So falcor is not inherently less scalable. if you need any help let me know!

**Comment by bburns** [comment]
Thanks, @janfjohannes!

I'm working on an open-source gateway to all your data - email, bookmarks, files, youtube playlists, etc - and then a client app to access everything with one interface. So Falcor looks perfect - can mount different datasources into a path tree, have a client-side cache, etc. 

Glad to have found this project!

**Comment by lucidNTR** [comment]
@bburns  sounds great. something like that for graphql was aquired by netlify recently and since then there is afaik no real alternative. especially the unified auth layer was super helpful. would love to hear more.

**Comment by traez** [comment]
Just started learning GraphQL, and came here while reading up on its history. Well done everyone!
