### ISSUE TITLE
Throw on attempt to retrieve a branch node

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#105]
This will almost certainly be the most common rookie mistake. It will be really helpful to provide an error message if an attempt is made to retrieve a branch note. Unfortunately we can't do anything on an attempt retrieve a branch node on the server. Would love to discuss any ideas here.

 @trxcllnt @michaelbpaulson

**Comment by michaelbpaulson** [comment]
I believe we went against this a long time ago.
