### ISSUE TITLE
Support 'list' as a first class notion, in order to acommodate wrapping lists

### ISSUE THREAD

**Issue by steveorsomethin** [Netflix/falcor#155]
Without knowing the length of a list, it's inefficient perform a get operation on a path such as the following:
[{from: -2, to: 3}, 'summary']

Because I can potentially continue wrapping into an infinite range, in the worst case I'll end up making a ton of requests for data I already have, and insert a bunch of references such that (when the list length is say, 40) indices -2 and -1 return the same summary as 38 and 39.

If falcor was made aware of the length of the entire list we are fetching a range for, it would only need to insert the out-of-range references and perform out-of-range network requests on any request where the list has no presence in the cache. Every subsequent request could then transparently and efficiently map out-of-range values into in-range lookups, eliminating network requests for paths we have in cache.

Ideally, I would like to be able to do something like this:
model.get([{from: -2, to: 3}, 'summary'], (summaries) => console.log(summaries.length))
or
model.get([-1, 'summary'], (summary) => /* summary points to the same value as [39, 'summary'], no network hop, no -1 reference inserted into cache */)

**Comment by michaelbpaulson** [comment]
we have decided against this.
