### ISSUE TITLE
refreshing() mode on the model for get requests

### ISSUE THREAD

**Issue by jordanna** [Netflix/falcor#160]
The internal version that is currently in production (mobile, website UIs) allows us to put the model in a "refresh" mode, which has the following behavior:
- `get` on a path that does not yet exist in cache will `onNext` the value(s) once fetched, i.e. same behavior as "non-refreshing" mode
- `get` on a path that already exists in cache will `onNext` the value(s) from cache immediately, then fetch remote updated value(s), update the cache, and `onNext` when done

It is currently being used to refresh bookmark, rating, and other volatile data on M/SDP launch. The reason we cannot use an invalidation + get approach is because the UI can perform a top-down update while a request is still in-flight. For example, rotating an iPad will cause the M/SDP to re-render without bookmark, rating, and other data that is being updated, but no longer in cache.

**Comment by steveorsomethin** [comment]
Closing as this is no longer needed. Could be useful in the future, but we shouldn't increase the API surface area speculatively.
