### ISSUE TITLE
ESLint clean code

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#168]
Currently our build is filled with ESLint errors. We should really get these cleaned up before we open source. Linters are valuable tools to catch errors, and I was going through the error list last night and I noticed some legitimate bugs. Not using a linter on an OSS project probably won't be very good optics. It's developer should just take some time to fix up the lint errors in their code before OSS. Most of them are pretty minor. I will try and get the erroneous global issues cleaned up via exceptions (ex. Missing require exceptions, etc)

**Comment by michaelbpaulson** [comment]
Done.
