### ISSUE TITLE
Bind requires leaf paths making it hard to use

### ISSUE THREAD

**Issue by ktrott** [Netflix/falcor#194]
Ideally, one could bind to branch paths. Without this ability it makes it difficult to write generic code that binds for you.

Makes it difficult to write something generic as you end up greedily getting leaf paths you might not want right away. You can do it by having a dummy path that just resolves the branch for you but that also doesn't feel correct, requires extra overhead to manage, configure and then request.

**Comment by michaelbpaulson** [comment]
bind -> deref so this is no longer a valid issue.
