### ISSUE TITLE
Object.freeze values when merging them into cache

### ISSUE THREAD

**Issue by steveorsomethin** [Netflix/falcor#217]
Using envify, it would be possible to detect if process.env.NODE_ENV === 'production', and only perform the freeze in dev mode. This also works with browserify, and when further run through uglify the branch to check NODE_ENV will be eliminated completely since envify inlines the variable value.

The utility here is making sure people treat falcor values as immutable, and only use Model.set when changing things. This might seem excessive, but there are already real cases where value mutation has happened in prehistoric code which caused interesting bugs/leaks.

Also, should we freeze recursively?

**Comment by michaelbpaulson** [comment]
Negative.  We will more than likely not do this.
