### ISSUE TITLE
Fresh build includes old version of HttpDataSource in falcor.browser.js

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#296]
Currently a fresh build seems to bring an older version of HttpDataSource into falcor.browser.js. The server interface has changed, so the HttpDataSource is unable to connect to the Router on the server. Probably some reference to an old version in a package.json somewhere.

**Comment by greim** [comment]
Is this why I'm having trouble getting things to behave as expected in my testing? I'm seeing repeated calls even for values I expected to be cached.

**Comment by michaelbpaulson** [comment]
falcor's package.json relies on the latest version of the http-datasource.  This should be fixed.
