### ISSUE TITLE
Consider slightly verbose property indexer.

### ISSUE THREAD

**Issue by stefanpenner** [Netflix/falcor#297]
currently, multiple sibling properties:

```js
model.getValue("location.city", "location.address")
```

can also be expressed as:

```js
model.getValue("location.['city', 'address']")
```

It would be nice if the more terse ES6 destructing inspired variation was instead (or in addition) used.

```js
model.getValue("location.{city,address}")
```

```js
// destructuring equivalent  
let { city, location } = location;
```

**Comment by michaelbpaulson** [comment]
We are dropping the path syntax from our falcor package soon.  We will either provide or the community will provide an ES6 template string integration.
