### ISSUE TITLE
property indexers not path aware

### ISSUE THREAD

**Issue by stefanpenner** [Netflix/falcor#300]
given:

```js
var person = falcor.Model({
  cache: {
    name: "Steve McGuire",
    occupation: "Developer",
    location: {
      country: "US",
      city: "Pacifica",
      address: "344 Seaside"
    }
  }
});
```

It isn't quite obvious how to get the single result of a subset of the graph, specifically: `name`, `location.country`, `location.city`

my attempt was:

```js
person.getValue(`['name', 'location.country', 'location.city']`)
```

which merely resulted in

```js
{
  name: 'Steve McGuire'
}
```

I confirmed that `location` was addressable via `person.getValue('location.city')`

**Comment by michaelbpaulson** [comment]
I am going to close this issue for 2 reasons:

1.  Its answered
2.  The `selector` function at the end of the get used above is no longer a feature in falcor.
