### ISSUE TITLE
Calling function with Model errors with "sequence contains no elements"

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#339]
Currently we are unable to call a "push" method using the Falcor Model. To reproduce this behavior, clone the falcor-router-demo repo, modify the index.html to call a stubbed function in the router,  run the demo, and hit the "/" path on localhost:

// add this code to index.html
model.call(
   "genrelist[0].titles.add",
   [{ $type: "ref", value: ["titlesById", 1] }],
   ["name"]);

 the route is currently stubbed in the router and will always return the same output, which is valid for the call above.

```
  {
    route: 'genrelist[{integers:titles}].titles.push',
    call: function(callPath, args) {
        return {
            path: ['genrelist', 0, 'titles', 2],
            value: {
                $type: 'ref',
                value: ['titlesById', 1]
            }
        }
    }
```

I believe that the server response is correct. However the Model onErrors with the message "sequence contains no elements". This is a common RX error, which is usually caused by a reduce function being executed on an empty stream. The fix it should be to use and can, followed by a lastValue method. Scan does not throw an error if the input sequence is empty. That said, the odd thing is that we should expect some data given we are providing a path Suffex which attempts to find the name. Under the circumstances there maybe more  going wrong here.

Marking this as "open source" because of the severity of this issue. Will also no doubt affect internal customers as soon as they attempt to use call.

**Comment by michaelbpaulson** [comment]
After reviewing this.  Does that make any sense?  Should we not complete?  @jhusain
