### ISSUE TITLE
Create JSON Graph Builder

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#355]
See comment for details:

https://github.com/Netflix/falcor/issues/349#issuecomment-126854101

**Comment by greim** [comment]
FWIW, not sure if it does exactly what's needed here, but I made this utility to convert blobs of JSON into graph fragments: https://github.com/greim/json-graphify

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

Assuming this means helpers for building json graph, https://github.com/greim/json-graphify looks great and there's also https://github.com/Netflix/falcor-json-graph

However, created https://github.com/Netflix/falcor/issues/861 to make sure these end up in the docs.
