### ISSUE TITLE
deref() bottlenecks heavily on observable subscribe calls

### ISSUE THREAD

**Issue by steveorsomethin** [Netflix/falcor#385]
Previously (#173) we had noted that derefSync is fairly slow, but in comparison deref is at least 7 times slower for the same path. I've designed around the issue by using derefSync, but I've now realized I can't reliably use it, and can end up in a dead zone where a model won't resolve until subsequent renders, at best (react).

However, switching to deref is cost prohibitive due to taking roughly 7ms on the usual device. Looking at the implementation, it appears we will go through 5 Observable subscribe calls in the best case, which we also know take at least 1.2ms per subscribe. That plus the 1ms for derefSync appear to account for the total time spent. If we preload paths, that number will multiply as we re-enter deref.

I'd avoid deref completely if possible, but we need a model in order to retrieve versions and detect if we need to perform a get or re-render. For now I'm going to change things to use deref for correctness sake, take the perf hit, and we should prioritize optimization of deref. I wouldn't want to solely rely on a faster Rx, since that would merely bring us to 2x  slower than derefSync if the current benchmarks don't regress.

**Comment by michaelbpaulson** [comment]
deref no longer is async.
