### ISSUE TITLE
Model-created atoms should be unboxed before being sent to server during set operation

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#400]
Currently whenever we set a value into the model, it is boxed in atom. This is an implementation detail, and allows us to add the value to an LRU list. However when we set values, they are first written to the cache and then read using getJSONG. The getJSONG function runs in materialize mode, which means it creates an atom where undefined values are found, but unboxed every other value. This means that any value other than undefined will be unboxed before being sent to the server.

This is incorrect behavior, because attempts to set a atom with any other value than undefined will be sent to the server without metadata.  It is perfectly reasonable to set a value to an atom, ref, or error on the server which is a JSON Graph after all. Operating in box values is not the answer though. This will send every value to the server boxed, regardless of whether it was explicitly boxed by the user or boxed internally to insert into the LRU.

If a user sets the number 5, it should be sent to the server unboxed. If they set an atom of 5, it should be sent to the server boxed. In order to achieve this, we will add a internal property to any atom that  we create. GetJSONG will automatically unbox any internally created atom. Values that were explicitly boxed by the user will be sent to the server boxed.

**Comment by michaelbpaulson** [comment]
we have model-created atoms as being unboxed before being sent to the server.
