### ISSUE TITLE
use rx-lite instead of full rx

### ISSUE THREAD

**Issue by Zolmeister** [Netflix/falcor#419]
Instead of depending on the full rx package use the lite version
https://www.npmjs.com/package/rx-lite

>
  Minified + gzipped rx.lite.js (alone) the size is ~40% smaller than rx.all.js
https://github.com/Reactive-Extensions/RxJS/issues/607

**Comment by ktrott** [comment]
Unfortunately, Rx Lite doesn't have all the operators we need to use and has extra ones. We are also planning to migrate to https://github.com/ReactiveX/RxJS for better performance. ReactiveX RxJS enables requiring each operator individually so that should reduce the overhead as well.

**Comment by michaelbpaulson** [comment]
falcor no longer depends on rx.
