### ISSUE TITLE
Provide official TypesScipt definitions for api

### ISSUE THREAD

**Issue by Davidhanson90** [Netflix/falcor#424]
Would be great if there was an official set of Typescript definitions for this library.

**Comment by eggers** [comment]
+1

**Comment by mfilotto** [comment]
+1

**Comment by ewinslow** [comment]
+1

**Comment by snowcxt** [comment]
+1

**Comment by rob3c** [comment]
+1

**Comment by matijagrcic** [comment]
Started working on this. Got most of it done so I hope to push it soon to [DefinitelyTyped/falcor](https://github.com/DefinitelyTyped/DefinitelyTyped)/falcor and close DefinitelyTyped/DefinitelyTyped#5412.
![2015-12-23 21_41_17-falcor tests ts_ - microsoft visual studio](https://cloud.githubusercontent.com/assets/3612395/11985773/1d3e37a8-a9c0-11e5-8a1a-a95cb2c42bda.png)
![2015-12-23 21_17_29-falcor tests ts_ - microsoft visual studio](https://cloud.githubusercontent.com/assets/3612395/11985774/1d419d76-a9c0-11e5-8bb0-f407f5e15fa7.png)

**Comment by ewinslow** [comment]
Why not check it in to falcor itself so it can be updated in sync with project changes? I think this is the new best practice recommended by typescript team.

**Comment by matijagrcic** [comment]
@ewinslow Yes, i remember reading a blog post about that but can't find it anywhere ;( Do you have a reference to it maybe? Sure I can submit it wherever is the best place.

**Comment by jsen-** [comment]
@matijagrcic more info can be found on the Typescript wiki: https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages

**Comment by matijagrcic** [comment]
@jsen- thanks, but i was referring to [Definitely Typed Shouldn't Exist](http://blog.johnnyreilly.com/2015/09/authoring-npm-modules-with-typescript.html). Took me a while to find it in my bookmarks.

>I'm a member of the Definitely Typed team - and hopefully I won't be kicked out for writing this. My point is this: .d.ts files should live with the package they provide typing information for, in npm / GitHub etc. Not separately.  @johnnyreilly

**Comment by ovrmrw** [comment]
:+1:

**Comment by ovrmrw** [comment]
+1

**Comment by gbouteiller** [comment]
+1

**Comment by michaelbpaulson** [comment]
Closing as it dupes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/5412 which is a much better place for that than here.

**Comment by ewinslow** [comment]
Why is that a better place for it? What about all the reasons given above for why types should be versioned with the code they describe?

**Comment by michaelbpaulson** [comment]
@ewinslow 2 reasons then, at least what I think, a good justification.

1.  This issue has been opened for quite some time and the only person to make progress on it is doing it in a separate repo.  The separate repo has the ticket to create it, but its not completed yet (link above).  
2.  As stated above, I/falcor team will not be providing an official type-script definition any time in the near future.  If this is a desire of the community, then this one will have to be an implementation done by the community.

##### Lets justify
I simply justify, perhaps falsely, on 3 points (one is from previous point).

1. https://github.com/DefinitelyTyped/DefinitelyTyped has a huge community backing and lots of forks / watchers who are eager to contribute back to the eco system.

2. Falcor team will not implement this any time soon (from above)

3. When https://github.com/DefinitelyTyped/DefinitelyTyped finishes, we will be glad to merge that work into the mainline of falcor.  

In the end its what will get this done the fastest is whats best for the community.  It appears that going through https://github.com/DefinitelyTyped/DefinitelyTyped is the most likely that candidate to achieve this feature.  So I [Kenny Rodgered](https://www.youtube.com/watch?v=Jj4nJ1YEAp4) this and folded.

**Comment by matijagrcic** [comment]
@michaelbpaulson Thanks, like the Kenny Rogers reference :+1: I'll try to finish the typings soon, started just before my holidays and didn't have a chance to return to it.

**Comment by gyllen** [comment]
Any news on the typings? Would be awesome to have.

**Comment by rob3c** [comment]
FYI It looks like [DefinitelyType is deprecated now](https://github.com/DefinitelyTyped/tsd/issues/269), so any further efforts by interested parties should probably happen at https://github.com/typings/typings since this has been Kenny Rodgered here.

**Comment by michaelbpaulson** [comment]
Did I just start a meme?
