### ISSUE TITLE
HapiJS implementation link 404

### ISSUE THREAD

**Issue by jhawlwut** [Netflix/falcor#426]
In the documentation, you link to "third party resources" for hapijs that leads here:
```html
https://github.com/dzannotti/falcor-hapi
```
This link just returns a 404.

**Comment by jhusain** [comment]
Removed link for now (from website). Should be up again soon once we confirm its working. Weren't planning on releasing it but we want a fast follow. Shouldn't be long.

**Comment by jhawlwut** [comment]
Cool, thanks for the quick response. Looking forward to the HapiJS
implementation.

On Monday, August 17, 2015, Jafar Husain <notifications@github.com> wrote:

> Removed link for now (from website). Should be up again soon once we
> confirm its working. Weren't planning on releasing it but we want a fast
> follow. Shouldn't be long.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Netflix/falcor/issues/426#issuecomment-131979680>.
>


-- 
Sent from my iPhone

**Comment by jhusain** [comment]
Fixed. Link in website homepage.
