### ISSUE TITLE
Include Keynote - JSON Graph Reactive REST on Falcor website

### ISSUE THREAD

**Issue by matijagrcic** [Netflix/falcor#430]
Include [Keynote - JSON Graph: Reactive REST at Netflix](https://www.youtube.com/watch?v=hOE6nVVr14c) on the Falcor website.

[![Keynote - JSON Graph: Reactive REST at Netflix](http://img.youtube.com/vi/hOE6nVVr14c/0.jpg)](https://www.youtube.com/watch?v=hOE6nVVr14c)

[Ref.](https://news.ycombinator.com/item?id=10076294)

**Comment by gdi2290** [comment]
:+1:
a list of all the videos in the readme with one on the landing page would be a great idea actually

**Comment by jhusain** [comment]
I think its a good idea. Want to consult with designer to figure out the best way to do this. @nicolasartman

**Comment by nicolasartman** [comment]
Sounds good to me. A few potential approaches:

- We could segment the videos dropdown into tutorial and another section that has more general videos like that keynote
- We could provide that video in the introduction section as a video page (same styling, etc)

I think either could work well.

Independently, If we want to display it on the homepage, we could:

- Display a thumbnail with an overlaid play icon that takes you to a separate video page or
- Display either text or a thumbnail, which opens up an in-page video player section.

While the second one feels spiffier to me, I think the first would cover more common use-cases, as I'd imagine folks wouldn't browse half the page, pause for an hour to watch the keynote, then continue reading the page.

There are other avenues to explore too of course, those are just a few simple ones I've thought up so far.

**Comment by rymndhng** [comment]
As the originator of the ref, I really think these first-step, motivational talks are super important at selling to other developers who aren't sure why Falcor vs ... other things, or what problems it solves.

This doesn't necessarily have to be at the front page, but it'd be great if there's a dropdown under "Introduction" that links to a title like "Motivation" or "Why we decided to build Falcor?"

**Comment by jhusain** [comment]
I like the idea of putting it under "About" . Something like "Why Falcor? (Video)"

I want to keep it separate from the tutorial videos. I don't want people getting the idea that the tutorials are as long as the talk. They are designed to be very short.



JH

**Comment by ewinslow** [comment]
I am getting HTTPS errors on this page.

https://netflix.github.io/falcor/starter/why-falcor.html

Looks like it's trying to load the YouTube video over HTTP and Chrome says "no" because it should be served over HTTPS.

**Comment by nicolasartman** [comment]
Thanks @ewinslow! PR #475 will fix this.
