### ISSUE TITLE
Is there a github repo for netflix.github.io/falcor ?

### ISSUE THREAD

**Issue by miguelmota** [Netflix/falcor#432]
I want to submit trivial fixes for the falcor site but don't know where.

For example, you guys have

```
“todos[0][“name”]”
```

but it should be

```
'todos[0][“name”]'
```

**Comment by gdi2290** [comment]
you're looking for the gh-page branch
https://github.com/Netflix/falcor/tree/gh-pages

**Comment by miguelmota** [comment]
Great, thanks!
