### ISSUE TITLE
Falcor 3 - Intro to JSON Graph: $type: "ref" and $ref not the same result

### ISSUE THREAD

**Issue by escapedcat** [Netflix/falcor#446]
I was just following the video and got confused at [Video 3 Intro to JSON Graph; Minute 7:26](https://www.youtube.com/watch?v=2xX5JTHWw4Q&feature=youtu.be&t=446).

This:
```
{ $type: "ref", value: "titlesById[5212]" }
```
...should give you the same result as this:
```
var $ref = falcor.Model.ref;
...
$ref("citiesById[5212]")
```

But when I try try this...
```js

var model = new falcor.Model({
  cache: {
    titlesById: {
      5212: {
        name: "House of Cards",
        rating: 4.5
      }
    },
    genreList: [
      {
        name: "Recently Watched",
        titles: [
          { $type: "ref", value: "titlesById[5212]" }
        ]
      },
      {
        name: "New Releases",
        titles: [
          { $type: "ref", value: "titlesById[5212]" }
        ]
      }
    ]
  }
});

model
  .setValue('genreList[0].titles[0].rating', 5)
  .then(function(value){
    model
      .get('genreList[0..1].titles[0]["name", "rating"]')
      .then(function(json){
        console.log(JSON.stringify(json, null, 4));
      });
  });
```

...I get:
```json
{
    "json": {
        "genreList": {
            "0": {
                "titles": {
                    "0": {
                        "rating": 10
                    }
                }
            },
            "1": {
                "titles": {
                    "0": {
                        "rating": 10
                    }
                }
            }
        }
    }
}
```

For some reason the _name_ is missing. It works using the `$ref` example though.

Sorry if this is already reflected in another issue. Couldn't find anything.

**Comment by jhusain** [comment]
The video slightly misleading. The ref factory function actually parses the path. By the time you create a Reference object, the value must contain a parsed path. If you wanted to create the reference manually, you would need to write this:

```JavaScript
var model = new falcor.Model({
  cache: {
    titlesById: {
      5212: {
        name: "House of Cards",
        rating: 4.5
      }
    },
    genreList: [
      {
        name: "Recently Watched",
        titles: [
          { $type: "ref", value: ["titlesById", 5212] }
        ]
      },
      {
        name: "New Releases",
        titles: [
          { $type: "ref", value: ["titlesById", 5212] }
        ]
      }
    ]
  }
});
```

The confusing thing about this is that it is even slightly working:-). I would expect a spectacular failure and the inability to retrieve "rating" or "name". Possibly due to the fact of the internal method we used to follow references has been updated to understand reference paths, but wasn't tested extensively.

**Comment by escapedcat** [comment]
Haha, I see. Thanks for the explanation. And thanks a lot for the videos. Awesome work!

**Comment by michaelbpaulson** [comment]
I am unsure of the fix.  Our internal implementation _does not_ understand string references.  How it partially works works perplexes me.  But the real question is what is the fix?  I am confused as to the action of this ticket other than "Don't do that."

**Comment by jhusain** [comment]
Just curious about why it happened. The overall message is "don't do that."

**Comment by escapedcat** [comment]
@jhusain just noticed that it's correctly explained in [Falcor 5 - JSON Graph in-depth; Minute 5:13](https://www.youtube.com/watch?v=9tAvnn-Wd14&feature=youtu.be&t=313)
