### ISSUE TITLE
Remove asPathValues from ModelResponse

### ISSUE THREAD

**Issue by ktrott** [Netflix/falcor#452]
To simplify Falcor, we should remove asPathValues from ModelResponse. This will simplify the code complexity.

**Comment by trxcllnt** [comment]
@ktrott As far as I'm aware, we need the ability to get data out as PathValues (for example, in `call`). @jhusain @michaelbpaulson is that still the case?

**Comment by jhusain** [comment]
Paul is correct. Functions currently return Path values relative to their this object. However this could be solved by forcing functions to return JSONGraph objects, enforcing that the only values within are relative to the function position. This is effectively what happens in the router today.

**Comment by michaelbpaulson** [comment]
finished as part of #497
