### ISSUE TITLE
Code clean-up: Remove selector function / output PathValues code throughout code base

### ISSUE THREAD

**Issue by ktrott** [Netflix/falcor#453]
Selector functions were removed before the open source from the public API. We need to clean up and remove it from the code base.

**Comment by michaelbpaulson** [comment]
I am going through `get` right now.  I have hopefully done as little refactoring as my emotions will allow me :)

**Comment by michaelbpaulson** [comment]
@jhusain Are we interested in the following.

?
get(Array|String)
getWithPaths(Array)
getWithJSON(PathMap) 

It would make this clean up worth it.

**Comment by jhusain** [comment]
Please don't change any public APIs yet. I would like to see performance numbers that show that overloading is expensive. 

You can get rid of toPathValues as far as I'm concerned.

**Comment by trxcllnt** [comment]
@jhusain don't we need that for streaming values from a dataSource?

**Comment by jhusain** [comment]
We can stream JSON. In practice values rarely arrive individually from the server, they arrive in bursts. Under the circumstances streaming JSON should be adequate.
