### ISSUE TITLE
Understanding the router and refs

### ISSUE THREAD

**Issue by thaggie** [Netflix/falcor#459]
I'm not sure if issues are where you're expecting / wanting questions with regard to falcor usage - I couldn't find direction in the docs and most questions on stackoverflow seem to have 0 answers - so apologies if this is the wrong place.

I've created myself a simple sample to try and work through how things work, with references they don't seem to be working as I'd expect - I'm not sure if I'm doing it wrong or my expectations are wrong.

```js
app.use('/foo.json', falcorExpress.dataSourceRoute(function (req, res) {
  var router = new Router([
    { 
      route: 'items[{ranges}][{keys}]',
      get: function(pathSet) {
        var pathValues = [];
        var ranges = pathSet[1];
        var props = pathSet[2];
        rangeGenerator(ranges, function(index) {
          var item  = model.items[index];
          props.forEach(function(prop) { 
            pathValues.push( {
              path: ['items', index, prop],
              value: item[prop]
            });
          });
        });
        return pathValues;
      }
    },
    {
      route: 'recent[{ranges}][{keys}]',
      get: function(pathSet) {
        var pathValues = [];
        var ranges = pathSet[1];
        var props = pathSet[2];
        rangeGenerator(ranges, function(index) {
          props.forEach(function(prop) { 
            var link = ['items', model.recent[index], prop];
            pathValues.push( {
              path: ['recent', index, prop],
              value: $ref(link)
            });
          });
        });

        return pathValues;
      }
    }

  ]);
  return router;
}));
```
(rangeGenerator just maps over all the indicees in the ranges)

When I make a request from the brower: `get('recent[0..1].name')` I get back:

```json
{
  "recent": {
    "0":  {
      "name": {
        "$type": "ref",
        "value": ["items", 1, "name"]
    },
    "1":  {
      "name": {
        "$type": "ref",
        "value": ["items", 3, "name"]
    }
}
```
I was expecting it to recurse in the router and return the values for `["items", 1, "name"]` too - but it does not, am I expected to re-call from the client with those paths or is there some additional magic I need to do to get it to return the referenced values as well as the references.

**Comment by ewinslow** [comment]
I also ran into this. You cannot create a reference to values, because falcor doesn't follow the reference if it is the last step in your path.

**Comment by jhusain** [comment]
First question: why are you trying to create a reference to a value? The reason I ask is that although we have a plan to support this, we have been holding off discussing because we have been interested to see whether people would have a need for it. 

In the example above, wouldn't it make more sense to create references to the item object?

```JavaScript
{
  "recent": {
    "0":  {
        "$type": "ref",
        "value": ["items", 1]
    },
 },
 "items": {
   "1": {
      prop1: "some value"
   }
 }
}
```

Now you can just write this:

```JavaScript
model.getValue(["recent[0].name"]).then(function(function(value) { /* ... */ });
// the path will get optimized into "items[1].name" by the router
```

Most of the time we see list of references to Objects within an identity map.

The code:

```JavaScript
app.use('/foo.json', falcorExpress.dataSourceRoute(function (req, res) {
  var router = new Router([
    { 
      route: 'items[{ranges}][{keys}]',
      get: function(pathSet) {
        var pathValues = [];
        var ranges = pathSet[1];
        var props = pathSet[2];
        rangeGenerator(ranges, function(index) {
          var item  = model.items[index];
          props.forEach(function(prop) { 
            pathValues.push({
              path: ['items', index, prop],
              value: item[prop]
            });
          });
        });
        return pathValues;
      }
    },
    {
      route: 'recent[{ranges}]',
      get: function(pathSet) {
        var pathValues = [];
        var ranges = pathSet[1];
        var props = pathSet[2];
        rangeGenerator(ranges, function(index) {
            var link = ['items', index];
            pathValues.push( {
              path: ['recent', index],
              value: $ref(link)
            });
          });
        });

        return pathValues;
      }
    }

  ]);
  return router;
}));
```

**Comment by ewinslow** [comment]
For me I was just playing around in jsbin and had created a primitive value at the top level of the graph like the help world example. As I continued adding routes, the graph grew and I wanted to move that value onto an object in the graph, but couldn't.

**Comment by thaggie** [comment]
Thanks - now I understand.
