### ISSUE TITLE
Code cleanup: Refactor set, move graph operations to falcor-json-graph

### ISSUE THREAD

**Issue by trxcllnt** [Netflix/falcor#472]
@ktrott @jhusain @michaelbpaulson @sdesai @msweeney 

Based on what we've learned in the last three months, the internal set operations are no longer required to build every type of output format, and they don't need to build missing paths. This means most of the internal set implementations are obsolete (and bloating the library), and even the three that are still used are doing more work than they need to.

We only need three set operations:
1. `setJSONGraph`,
2. `setPathMaps`,
3. `setPathValues`

I've built the three new set operations and removed the obsolete modules. Some of these modules are duplicated between falcor and falcor-router, and presumably other projects that want to perform json-graph manipulation. I propose factoring the internal json-graph manipulation modules into the [falcor-json-graph](https://github.com/Netflix/falcor-json-graph) project.

Removing the dead code and factoring out duplicated should further significantly reduce the built file size.

**Comment by michaelbpaulson** [comment]
@trxcllnt could you put those functions in https://github.com/Netflix/falcor-path-utils 

That is where all of our path operations are going (collapse is there currently).

**Comment by michaelbpaulson** [comment]
This removes code output, but does not move core code to falcor-json-graph.  That can be discussed at a later date.
