### ISSUE TITLE
Access Denied on Coveralls

### ISSUE THREAD

**Issue by geekuillaume** [Netflix/falcor#476]
The Coveralls report (https://coveralls.io/github/Netflix/falcor) is private. We cannot access it without being logged as a Falcor Maintainer (I think so, but I havn't tested as I'm not a maintainer).

**Comment by sdesai** [comment]
I'll look into whether or not we can reconfigure the existing Coveralls job to allow report access to the now public repo (so we don't lose history).

Worst case, we'll reset up the job off of the public repo.

**Comment by sdesai** [comment]
@geekuillaume Can you let me know if you can get to it now, from the Badge. I can, without being authenticated.

**Comment by sdesai** [comment]
I believe this is fixed (had to contact the Coveralls folks to migrate for us). Feel free to re-open if you still can't get to the reports.

**Comment by geekuillaume** [comment]
Okay, it's working here too ! Thanks ! :smile:
