### ISSUE TITLE
What is the right way to render a template in a loop?

### ISSUE THREAD

**Issue by ewinslow** [Netflix/falcor#479]
For lists of things on a page, you want to render a range of keys but it's impossible to know beforehand how many indexes are available without incurring a round trip to the data source.

What is the best practice here?

**Comment by dallonf** [comment]
I usually make a request for the first _n_ items in the list (Like `titles[0..19]` to grab the first 20 - this won't throw an error, even if there are less than 20 items in the list) and also grab the length at the same time, which allows me to render pagination controls.

I do agree it would be nice to be able to make length-based requests, though. It's wasteful to send back 19 `$atom`s if there's only one item in the list. And sometimes, I just happen to know there's not a huge number of items in the list and I do in fact want to grab them all.

**Comment by ewinslow** [comment]
So I think I left out some info that would be helpful to explain the problem further...

Suppose I have a "posts" component that looks like this (angular 2 example):

```
<li *ng-for="#post of ???">
  <post [data]="item">
</li>
```

Here I don't know statically:
 * what data is needed by the post component
 * what page of the feed I'm on

Basically I need to "speculatively" unravel that loop somehow to discover what data the post is requesting, so that those requests can then be batched and sent to the server. E.g. perhaps `<post>` looks like:

```
<h1>{{data.getValue('title')}}</h1>
<div [inner-html]="data.getvalue('content')"></div>
```

But the feed item should not need to know this statically, to maintain maximum decoupling.

Is there any way to do this yet? I'm thinking a method that returns an `Observable<Array<Model>>` where the first published Array is as long as the maximum number of items requested but then a new Array truncated to the correct length in published when the results are back from the server.

**Comment by ewinslow** [comment]
Perhaps most succinctly: what should I put in the question marks?

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

Netflix follows a pattern of over-expressing paths in order to accommodate polymorphic results, as well as lists of unknown size as Dallon noted.

I know this is a VERY stale issue, but if you can provide a bit more information about your data model, we might be able to make some recommendations about how to make this a bit easier. For now however, I'm going to lose this.
