### ISSUE TITLE
Error with {keys:props} "pathSet.keys.forEach is not a function"

### ISSUE THREAD

**Issue by Bretto** [Netflix/falcor#480]
Testing
```
route: 'tasksById[{keys:ids}][{keys:props}]',
pathSet.keys.forEach(function (key) {
```
error
```
pathSet.keys.forEach is not a function
```
But
```
route: 'itemById[{keys:ids}]["name","content"]',
pathSet[2].forEach(function (key) {
```
works as expected, is this a bug ?

**Comment by ewinslow** [comment]
I suspect you want `pathSet.ids.forEach`?

**Comment by Bretto** [comment]
No, if you have a look a the "The {keys} Pattern" section in the Router docs you will find:
```
pathSet.keys.forEach(function(key) {
    task[key] = jsong.atom(taskRecord[key]);
});
```
the keys is the breaking the ids is fine.

**Comment by dallonf** [comment]
Aha, that looks like a problem in the docs. It should be `pathSet.props` at that point.

**Comment by jhusain** [comment]
Confirmed.

**Comment by michaelbpaulson** [comment]
@jhusain did we ever fix this ?  I am eager to close this issue :)

**Comment by jhusain** [comment]
Was fixed. Forgot to close.
