### ISSUE TITLE
"JSON Graph" could cause confusion

### ISSUE THREAD

**Issue by ariutta** [Netflix/falcor#488]
Just wanted to point out a potential source of confusion. "JSON Graph" is also used for this project:  [JSON Graph](https://github.com/jsongraph/json-graph-specification).

**Comment by intellix** [comment]
To add: I actually thought this was either an outdated version or the slides being presented were old

**Comment by michaelbpaulson** [comment]
That is interesting.  Unsure what action items can be done here, I'll bring up at next Falcor Sync.
