### ISSUE TITLE
newer values replaced by old ones if comparator returns false

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#498]
New values should never be replaced by old ones ($timestamp), even if comparator returns true

**Comment by trxcllnt** [comment]
for reference, @jhusain filed this issue after our conversation about set improvements, specifically set [now respects](https://github.com/trxcllnt/falcor/blob/get-plus-set/lib/support/mergeValueOrInsertBranch.js#L38) time stamps on values

**Comment by michaelbpaulson** [comment]
I assume this is fixed since new set has this issue fixed.
