### ISSUE TITLE
Es6 template strings

### ISSUE THREAD

**Issue by Bretto** [Netflix/falcor#499]
It seams you can't write your get query on multiple lines
this works:
```
let res = yield this.model.get(
            `category['${categoryId}']items[0..${length}]['categoryId','uid','name','content','modified','ownerId','ownerName','tags']`
        ).then((res)=>{return res.json.category[`${categoryId}`].items;});
```
this doesn't
```
let res = yield this.model.get(
            `category['${categoryId}']items[0..${length}][
'categoryId',
'uid',
'name',
'content',
'modified',
'ownerId',
'ownerName',
'tags'
]`
        ).then((res)=>{return res.json.category[`${categoryId}`].items;});
```

will this limitation be addressed at some point ? it would be nice not to have the all thing on one line.

**Comment by dallonf** [comment]
Would be nice. In the meantime, I find that the array syntax is much nicer most of the time:

```
this.model.get([
  'category', categoryId, 'items', {from: 0, to: length},
  [
    'categoryId', 'uid', 'name', 'content',
    'modified, 'ownerId', 'ownerName', 'tags'
])
```

**Comment by jhusain** [comment]
Opened an issue on Falcor-path-syntax repo.

https://github.com/Netflix/falcor-path-syntax/issues/19

**Comment by jhusain** [comment]
The guidance is good: use the array path syntax for now.

**Comment by gdi2290** [comment]
I would argue that the correct answer is not to use the string syntax for this case since you gain more using the js syntax
