### ISSUE TITLE
What about the Falcor cache on the server ?

### ISSUE THREAD

**Issue by Bretto** [Netflix/falcor#503]
How do I cache the returns of my query (server side) so that the next client don't hit the DB ?

**Comment by jhusain** [comment]
Just request it using the Model. The Model will cache it internally.

**Comment by Bretto** [comment]
How to you access the Model on the server side (in the router for example... ) ?

**Comment by pensierinmusica** [comment]
+1

**Comment by jhusain** [comment]
~~~js

var falcor = require("falcor");
var model = new falcor.Model();
~~~

**Comment by jhusain** [comment]
Rereading this and it looks like I misunderstood the question. Caching the results of your _server side_ APIs is typically best handled by a service layer decorator.

Here's an example of a cache function you can run on your service that will automatically cache the results: https://github.com/Netflix/falcor-router-demo/blob/master/cache.js

If you run this Cache decorator function on your service function, subsequent calls to the same function for the same ID will not trigger a call to the underlying service.

**Comment by IlyasM** [comment]
@jhusain @michaelbpaulson why using a server side falcor model for caching db results is not a good idea? For example, client side model has httpDataSource which talks to a router which redirects request that needs caching to the server side model and server side model does all the querying.

**Comment by IlyasM** [comment]
It would be very nice, if that worked

**Comment by michaelbpaulson** [comment]
We are ok with server side models.  They are affective for batching/caching/ and ID optimization.  If you have a user service, its best to use a server model in case of concurrent requests for data.  This way batching will prevent multiple round trips.  With sequential requests for like data, it can also respond without making a round trip request.

So we support server side models.

**Comment by almasakchabayev** [comment]
@michaelbpaulson How do you solve the problem of serverside model returning json? I mean clientRouter (on server) needs to return pathValues, but it receives json from serverModel. Currently I have written a custom function, which parses json to pathValues. Is it the right approach?
