### ISSUE TITLE
The issue described in #512 is still present in the prebuild libraries in falcor/dist

### ISSUE THREAD

**Issue by OverclockedTim** [Netflix/falcor#519]
#512 specifically mentions building from scratch and hence was probably closed correctly. However, the issue still occurs when using the prebuilt libraries in /dist, specifically:

Throws an exception in falcor-http-datasource's onXhrLoad(observer, xhr, e):

Uncaught TypeError: observer.onNext is not a function
observer.onNext(responseData);

This makes falcor unusable "out of the box" in the browser atm.

**Comment by sdesai** [comment]
Yeah, I wasn't actually sure if 'dist' is intended to be a committed folder or not. I'll update it manually for now, and if it needs to be updated with every commit to source, we'll figure out if it needs to be fit into the CI process, or should be submitted with every PR.
