### ISSUE TITLE
The latest release throws model.get(...).then is not a function error

### ISSUE THREAD

**Issue by sahat** [Netflix/falcor#530]
Falcor version that is hosted at `//netflix.github.io/falcor/build/falcor.browser.js` is throwing an error with the Getting Started example code. I thought I broke something, but after switching to *falcor-0.1.12* everything works fine.

<img width="1060" alt="screenshot 2015-09-08 11 11 52" src="https://cloud.githubusercontent.com/assets/544954/9743303/6e961c32-561a-11e5-82c7-74b961923734.png">

So, I am not sure if it's a bug or the API has changed, but if it's the latter then Getting Started examples on https://github.com/Netflix/falcor and http://netflix.github.io/falcor/ need to be updated accordingly.

**Comment by noonian** [comment]
I can confirm this behavior with the hosted build.

**Comment by michaelbpaulson** [comment]
This should be an easy fix.  We apparently never use promises in our unit tests.  Ill get up an unit test and fix this issue.
