### ISSUE TITLE
Support Node-style callbacks

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#54]
Should be easy to add an on method alongside then method. The on method follows the usual Node.js convention:

model.get(["lolomo",0,0,"name"]).on(function(error, data) {

});

**Comment by michaelbpaulson** [comment]
@ktrott @jhusain @sdesai @steveorsomethin is this still _high relevance_?

**Comment by steveorsomethin** [comment]
With the removal of Rx from the core, the performance win from this is pretty much nil. That was my primary interest, but someone else might have had another reason to want this.
