### ISSUE TITLE
Real Time Chat ?

### ISSUE THREAD

**Issue by Bretto** [Netflix/falcor#543]
Is there a live communication channel type (https://gitter.im/) for Falcor ? It would be good to start exchanging experience and thoughts...

**Comment by clooth** [comment]
I'm for an IRC channel on freenode. Like ##falcor, I created it for now if anyone's interested in joining in.

**Comment by trxcllnt** [comment]
@Bretto we had one when Falcor was a private repo, but ran into issues with it when we made it public. I can't try and establish a new one, because I'm not a project admin anymore.

@clooth sounds great, I'll try to be more active in case anybody has questions.

**Comment by clooth** [comment]
@trxcllnt Awesome. I'm still very new to falcor so I'll be happy to provide operator access and whatnot to those who know their stuff, or step down as an operator myself if required.

**Comment by ekosz** [comment]
:+1: Would love an active channel to have a conversation / ask questions.

**Comment by dbslone** [comment]
:+1:

**Comment by trxcllnt** [comment]
FYI: https://gitter.im/trxcllnt/falcor

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

It's likely best to keep this sort of thing self-organizing, as it has proven challenging to remain responsive with async communication, let alone sync. Looks like the gitter should work for broad knowledge sharing, though.
