### ISSUE TITLE
HttpDataSource directly in new falcor.Model doesn't work

### ISSUE THREAD

**Issue by bobvanluijt** [Netflix/falcor#549]
The https://github.com/Netflix/falcor-express-demo/blob/master/index.html has the following lines:
```
var model = new falcor.Model({
        source: new falcor.HttpDataSource('/model.json')
});
```

Which looks to make sense, but it actually doesn't work, it will keep requesting even if the value is already available.

This does work:
```
var modelSource = new falcor.HttpDataSource('/model.json');
var model = new falcor.Model({
        source: modelSource
});
```

Note:
Originally posted here: https://github.com/Netflix/falcor-express-demo/issues/4

**Comment by michaelbpaulson** [comment]
This seems like something else is going on here.  There is no difference between two, which is weird that one works and the other doesn't.  I can try to take a look a this sometime this week.

**Comment by greim** [comment]
The breakage happens either way for me. @kubrickology can you take a closer look and see what's different? Since the two examples you posted are essentially the same?

**Comment by michaelbpaulson** [comment]
We use both in testing code and neither seem to break like this.  Closing.
