### ISSUE TITLE
Passing additional info with http requests from the client's falcor.Model

### ISSUE THREAD

**Issue by shfrmn** [Netflix/falcor#550]
Actually, it's just a question.
I'd like to know how I can pass some additional info with HTTP requests from the client falcor.Model (e.g. auth tokens). I couldn't find anything written about it in docs. I would really appreciate the answer and I'm sorry if solution is something obvious.

**Comment by gdi2290** [comment]
JWT
```javascript
var model = new falcor.Model('/model.json', {
  headers: {
    'Authorization': `bearer ' + token`
  }
});
```
Cookies
```javascript
var model = new falcor.Model('/model.json', {
  withCredentials: true
});
// server must include the header `Access-Control-Allow-Credentials: true`
```
CORS 
```javascript
var model = new falcor.Model('/model.json', {
  crossDomain: true
});
```

**Comment by shfrmn** [comment]
Thank you, your answer helped, but it looks like you mixed Model and HttpDataSource. Shouldn't it be this way? It works well for me.
```javascript
var model = new falcor.Model({
    source: new falcor.HttpDataSource( '/api/model.json', {
        headers: {
            'Authorization': `bearer ' + token`
        }
    })
});
```

**Comment by gdi2290** [comment]
oops ya you're right

**Comment by shfrmn** [comment]
Falcor is awesome!
