### ISSUE TITLE
Falcor is rewriting paths strangely

### ISSUE THREAD

**Issue by tivac** [Netflix/falcor#556]
I'm using `falcor@0.1.3` and `falcor-http-datasource@0.1.2`, browserified together using `browserify@11.1.0` on `node@4.1.0` running on Windows 7 x64.

I have the following routes specified on the server:

```
user[{keys:users}].details
user[{keys:users}].auth2f.details
user[{keys:users}].auth2f.type
user[{keys:users}].appdata
```

I'm using the following code on the client:

```js
var falcor = require("falcor"),
    HttpDS = require("falcor-http-datasource"),
    model  =  new falcor.Model({
        source : new HttpDS("/model.json")
    });

model.get([
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "details" ],
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "auth2f", "type" ],
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "auth2f", "details" ],
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "appdata" ]
]);
```

and falcor is making a request that looks like this to my server:

`/model.json?paths=[[["F613C9D2-B291-DE11-A58E-0014220D425B","details","user"],["F613C9D2-B291-DE11-A58E-0014220D425B","auth2f","type","user"],["F613C9D2-B291-DE11-A58E-0014220D425B","auth2f","details","user"],["F613C9D2-B291-DE11-A58E-0014220D425B","appdata","user"]]]&method=get`

broken out so they're easier to read, the `paths` param is

```
[
    [
        ["F613C9D2-B291-DE11-A58E-0014220D425B","details","user"],
        ["F613C9D2-B291-DE11-A58E-0014220D425B","auth2f","type","user"],
        ["F613C9D2-B291-DE11-A58E-0014220D425B","auth2f","details","user"],
        ["F613C9D2-B291-DE11-A58E-0014220D425B","appdata","user"]
    ]
]
```

... what happened? It looks like falcor tried to notice that all the paths started with `user` and optimize it out, but it instead did something weird.

The server unsurprisingly doesn't understand that request and returns a [very strange response](https://gist.github.com/tivac/02215b86d724e18845aa).

**Comment by tivac** [comment]
I also tried this with `falcor@0.1.2` and `falcor-http-datasource@0.1.1` with no luck. Can't go further back right now.

**Comment by michaelbpaulson** [comment]
Its not writing paths strangely, its doing exactly as you specified.  The problem is that you are providing an array of Paths.  Instead provide an argument list of paths.

E.g
```javascript 
// No
model.get([
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "details" ],
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "auth2f", "type" ],
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "auth2f", "details" ],
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "appdata" ]
]);

model.get(
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "details" ],
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "auth2f", "type" ],
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "auth2f", "details" ],
    [ "user", "F613C9D2-B291-DE11-A58E-0014220D425B", "appdata" ]);

```

Quick question @tivac do you have these paths stored off in a config?  Will you have to use `apply` to use `get`?

**Comment by tivac** [comment]
Thanks, I feel pretty dumb. I *just* noticed that myself and was hoping I could close this before anyone noticed.
