### ISSUE TITLE
Supporting Sub-PathSets

### ISSUE THREAD

**Issue by ekosz** [Netflix/falcor#568]
Is there a way to request a Sub-PathSet? What I mean by that would be something that looks like:

```js
falcor.get(
  ['my', 'goals', { length: 5 }, ['id', 'name', ['updates', { length: 5 }, ['id', 'text']]]
)
```

That would hopefully return the same thing as requesting:

```js
falcor.get(
  ['my', 'goals', { length: 5 }, ['id', 'name']],
  ['my', 'goals', { length: 5 }, 'updates', { length: 5 }, ['id', 'text']]
)
```

The reason to support this would be better enable patterns [like this one](https://gist.github.com/btholt/a5908e50eec2941ae6d7) where components bubble up their requirements to a falcor request. The pattern currently needs to know all of the sub-resources at the top level.

**Comment by trxcllnt** [comment]
@ekosz the two paths in your second block don't collapse into a single path, so you'll always have to request those leaf nodes as two paths. If you have a path prefix and `n` number of suffixes, you can map the suffixes and apply them to `get` as arguments:

```es6
const prefix = ['my', 'goals', { length: 5 }];
const suffixes = [ [['id', 'name']], ['updates', { length: 5 }, ['id', 'text']] ];
model.get
  .apply(model, suffixes.map(suffix => prefix.concat(suffix)))
  .subscribe(({ json }) => {
    // do work
  });
```
