### ISSUE TITLE
Implementing a chat-like data flow

### ISSUE THREAD

**Issue by myndzi** [Netflix/falcor#579]
I've been trying to think of how to apply Falcor to chat. I've got a couple stumbling blocks.

One is just realtime push notification in general. How can that sort of thing be integrated into a Falcor managed data set? Falcor seems useful for imperative data fetching, but I'm pretty fuzzy on how to use it for reactive stuff. Perhaps that's outside its use-case?

The other is array management. A public chat will have a long history, and on pageload we're only interested in the most recent X lines. If the user scrolls up, we may want to load older chats as we go. As time passes, new messages may come in which we want to add to the end. This puts us in the difficult position of not having a useful "0-index" for the array of chat data. We might have 0 represent the oldest chat message and index everything from that, but then how do we request the _last_ 100 lines or so?

**Comment by intellix** [comment]
Actually, in regards to this. When I first saw the Observable stuff for returning values early, I thought it was actually opening a socket and returning that data to the browser.

Are there any plans to use sockets for returning data asynchronously?

**Comment by nbostrom** [comment]
I've been thinking about this. What if you would join a "room" (think socket.io, etc) when subscribing to a path and leave it when all subscriptions to that path are disposed? Could this be done as a DataSource?

**Comment by trxcllnt** [comment]
Ues, that's why we went with Observables at the edges, but unfortunately we'd need to do some internal refactoring to allow DataSource responses to get/set/call to be streamed in piecemeal. Definitely on the radar though. @jhusain @michaelbpaulson

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

https://github.com/Netflix/falcor/issues/751 Has some comments from Jafar on this topic.
