### ISSUE TITLE
DataSource -- responding to range outside of bounds

### ISSUE THREAD

**Issue by eyston** [Netflix/falcor#582]
I don't know if the title makes sense ...

I'm making a custom data source and I'm wondering the proper way to respond to a request for a range of say `['todos' {length:10} 'name']` when `todos` has less than 10 elements.

If I return 5 elements, `falcor.Model` will retry the request over and over asking for the last 5.  Instead I return 5 elements and 5 `null`s and that seems to make `falcor.Model` happy.  I'm wondering if this is legit or if there is another way to tell `falcor.Model` that 'hey, you requested 10, but there are only 5'.

**Comment by jhusain** [comment]
The answer is straightforward. You must create an atom for every item that was requested by the model but does not exist on the server. 

In other words:

{
  todos: {
    0: {
      name: "go to ATM"
    },
    1: { $type: "atom" }
  }
}

**Comment by eyston** [comment]
Perfect, thanks!
