### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by jdarling** [Netflix/falcor#584]
In the documentation (at http://netflix.github.io/falcor/documentation/jsongraph.html) the following paragraph references entity "44" that is "get milk from store" but instead in the documentation it reads "withdraw money from ATM".  In the response text after this paragraph the right data is shown though.

```
Now we evaluate the “todosById” key, which yields an object. Next, we convert the number 44 into a string using the JSON stringify algorithm. Then we look up the resulting string “44” which yields another object. Finally we look up the key “name” and we find a primitive value type ”withdraw money from ATM”. This value is added to the JSON Graph subset and returned as the result of the abstract get operation.
```

**Comment by JinpaLhawang** [comment]
This issue would be fixed by PR: https://github.com/Netflix/falcor/pull/634
