### ISSUE TITLE
Support for generating sub models

### ISSUE THREAD

**Issue by Pajn** [Netflix/falcor#587]
It would be nice if Falcor had support for generating sub-models where paths are not relative to the root.
For example a movieDetail page needs knowledge of the full path to the movie, which usually includes an ID.
If I could generate a sub-model with points to the movie object directly it would only need knowledge of the properties of movie. It doesn't even need to know the id or if the movie is queried by the id, it would be just as glad if this later on changed to a slug.

Example:
```
const rootModel = new falcor.Model(...);
const movieModel = rootModel.subModel(['moviesById', 5]);

movieModel.get('name').then((response) => console.log('You are watching', response.json.name));
// Would be equal to
rootModel.get(['moviesById', 5, 'name']).then((response) => 
    console.log('You are watching', response.json.moviesById[5].name));
```

As you see, both the get request path and response is relative to the path `['moviesById', 5]`

**Comment by jhusain** [comment]
This is what the ```deref``` method on the model is for.

**Comment by Pajn** [comment]
Sorry, I somehow missed it while scanning the documentation for it :P
