### ISSUE TITLE
Materializered responses are undefined when all values are undefined

### ISSUE THREAD

**Issue by ekosz** [Netflix/falcor#590]
After learning about `_materialize()` from #583 I knew it would solve an issue of mine, but it doesn't seem to be working the way I thought it would.

Here is my call:

```js
falcor._materialize().get(['my', 'invites', {length: 5}, ['name']]).then(function(res) { console.log(res); })
```

But only `undefined` is being logged.

Here is the response from the server:

```js
{
  "jsonGraph": {
    "usersById": {
      "a18ddc00-7a8d-11e5-8c68-5bcc34dfa608": {
        "invites": {
          "0": {
            "$type": "atom"
          },
          "1": {
            "$type": "atom"
          },
          // Cut
        }
      }
    }
  }
}
```

I would have thought the response returned from the promise would look more like:

```js
{
  my: {
    invites: {
      0: undefined,
      // And so forth
    }
  }
}
```

Is `undefined` being returned because all of the invites are `undefined` and its collapsing the tree?

**Comment by michaelbpaulson** [comment]
@ekosz 
* relying on `_` is very dangerous as we may remove this at anytime without revving semver's major version (and not even minor either).
* I am not understanding your issue.  We do not collapse.  What you are saying is that when the entire response is undefined then the output is simply an `undefined`?

**Comment by michaelbpaulson** [comment]
#639 Found the bug you were referring to.
