### ISSUE TITLE
How do you use strings for keys in paths?

### ISSUE THREAD

**Issue by dijs** [Netflix/falcor#592]
I am trying to reference an object within another object on the server. In order to do this I need to pass falcor the parent object's id.

e.g.

`novels[{strings:ids}].chapters.length`

or better if possible

`novel[{string:id}].chapters.length`

I am still new to falcor. So if there is a better way to retrieve these objects, please let me know.

I do not understand how I can retrieve my documents from the database only using indexes...

**Comment by mencken** [comment]
Do it like this:

```
novel[{keys:novelIds}].chapters.length
```

You'll need to be aware that the route can receive multiple novelIds in a single request.  I.e.

```
pathSet = {'novel', ['id1', 'id1', 'id3'], 'chapters', 'length', novelIds: ['id1', 'id1', 'id3']};
```

**Comment by michaelbpaulson** [comment]
above answer is correct.  closing issue.
