### ISSUE TITLE
Rails backend and Falcor

### ISSUE THREAD

**Issue by barsukov** [Netflix/falcor#593]
I try to use falcor with my rails backend I built simple json model which look like on json: 
`{"books":[{"title":"Great","author_name":"CoolAuthor,"category_name":"Poetry"},`

Then I try to make a request through the falcor httpDatasource and model:

```
var falcor = require('falcor');
var HttpDataSource = require('falcor-http-datasource');

var BooModel= new falcor.Model({source: new HttpDataSource('/books.json') });

BookModel.get('books').then(function(response) {
  console.log(response.json.books);
});
//Or simple
BookModel.getValue('books[0].title').then(function(value) {
  console.log(value);
});
```

Then when I call this method in react component, falcor start to do a lot of request without stopp
like infinite loop. then it received error.
`Uncaught MaxRetryExceededError: The allowed number of retries have been exceeded.`

Is it mean response should contain something specific for falcor or it simply does not work with rails backend and should work only with falcor server side?

**Comment by wilkerlucio** [comment]
Try to output this:

```json
{
  "jsonGraph": {
    "books": {
      "0": {
        "title": "Great",
        "author_name": "CoolAuthor",
        "category_name": "Poetry"
      },
      "length": 1
    }
  }
}
```

I'm not sure how hard will be to you to implement the Falcor on Ruby, it's not just about formatting this response, in some cases and type of responses you will have to follow paths and handle enveloping responses (the call, for example, besides the modified paths you also have to compute a list of mutating paths to come along).

You can learn more about this by playing around with the Node.JS Falcor implementation, do some experimenting and see how the responses are formatted, that way I believe you can get a better idea on how to format the responses.

**Comment by barsukov** [comment]
Thank you for the answer . But why falcor does not specify it in the doku? and why it was not easily with REST API? Because for this  case in My app I prefer to use relay and graphql instead of implement it by myself without any Ideas how to do it. I thought it was killer feature for data fetching during Rest API but unfortunately not :( I can try to do it in ruby by myself  when I have a time ;)

**Comment by barsukov** [comment]
It was really depend on this https://github.com/Netflix/falcor/issues/513 probably should not be oppened.

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

If you'd like an example of implementing falcor on the server, https://github.com/Netflix/falcor-router is a good start.

https://github.com/Netflix/falcor/issues/816 has some good discussion of integrating falcor with existing REST services.
