### ISSUE TITLE
documentation: "The `call` Method" is incomplete

### ISSUE THREAD

**Issue by Kosta-Github** [Netflix/falcor#595]
The documentation about the `call` method is incomplete on this page: https://netflix.github.io/falcor/documentation/datasources.html

The sample snippets below the paragraph:
`"To demonstrate the call() method in action, we’ll create a DataSource by adapting a Model with an in-memory cache to the DataSource interface using the asDataSource() method."`
have just been copied from the documentation of the `set` method above.

I would be interested in an example about how to implement an `add` operation for appending stuff to an array (or the sample `todo list`)...

**Comment by rnicholus** [comment]
@Kosta-Github I noticed the same thing a while back. Perhaps [the call route](https://github.com/Widen/fullstack-react/blob/master/server.js#L36) in my [fullstack-react repo](https://github.com/Widen/fullstack-react) will be of some help to you? The route is hit by the [name-adder react component](https://github.com/Widen/fullstack-react/blob/master/name-adder.jsx).

**Comment by Kosta-Github** [comment]
@rnicholus thanks for the links, I discovered them in the meantime already... :-)

**Comment by jeffbski** [comment]
+1
