### ISSUE TITLE
Ability to return superset of requested values from router.

### ISSUE THREAD

**Issue by greim** [Netflix/falcor#610]
If the user asks falcor for `[ 'users', '123', 'avatar' ]`, my router calls `GET /api/users/123` which returns avatar, username, and lots of other data, which is then discarded. If the user asks falcor for `[ 'users', '123', 'username' ]` a few seconds later, the router calls the endpoint again.

It would be nice if the router could return all that data to the client pre-emptively in the json graph, and have it find its way into the model cache (as long as it isn't brimming full). That way getting `[ 'users', '123', 'avatar' ]`, waiting a few ticks, then getting `[ 'users', '123', 'username' ]` wouldn't cause the router to spam the REST api.

Is that possible? I think it would make it more feasible to wrap Falcor around legacy REST APIs.

(@nicovalencia)

**Comment by trxcllnt** [comment]
@jhusain @michaelbpaulson Related to Falcor-Router pr-128

**Comment by michaelbpaulson** [comment]
Its _not_ related to https://github.com/Netflix/falcor-router/pull/128.  What you are asking for is a service layer.  One where when someone asks for a piece of data, the resource itself is cached.  This is not the concerned of the router.  

A simple solution (though wont work in all items) is a falcor model!  I chose to use Rx because it makes things simple.  I hope you are familiar.

```javascript
var serviceModel = new Model();
var getUser = require('getUser');
var router = new Router([{
... other handlers
}, {
    route: 'users[{integers:ids}]["username", "avatar"]',
    get: function getUser(aliasMap) {
        return Rx.Observable.
            from(aliasMap.ids).
            flatMap(function(id) {
                return toObservable(serviceModel.
                    get(['users', id])).
                    concat(getUser.bind(id)).
                    take(1);
            }).
            flatMap(function(user) {
                return Observable.
                    from(aliasMap[2]).
                    map(function(prop) {
                        return {path: ['user', user.id, prop], value: user[prop]};
                    });
            });
    }
```

Now this is a naive service layer implementation that will cache users.  Does this answer your question?

**Comment by greim** [comment]
Thanks for the reply. I've actually already started using Falcor Models as caching layers on the server side and it's working fairly well so far! It's client-side caching I'm wondering about here. (Not browser caching, but the Falcor Model in browser JS memory) Using an HTTP datasource to talk to a server-side router, I do this:

```js
// in the browser
model.get('users[1].username');
```

The HTTP datasource makes a network call to `/model.json?paths=['users',1,'username']`. But suppose the router returns even more:

```js
// router sends this to browser
{
  users: {
    1: {
      username: 'foo', // <-- client only asked for this
      email: 'foo@example.com',
      avatar: { $type: 'ref', value: ['media','2'] }
    }
  },
  media: {
    2: {
      src: 'http://media.example.com/foo.jpg'
    }
  },
}
```

In my experiments, that extra data isn't being cached in the Falcor Model. So if I `get()` that data immediately after it results in another network call to the server.

**Comment by michaelbpaulson** [comment]
Correct.  Falcor will only transfer the data requested.  The big problem with allowing _supersets_ to be transferred is we are just back to REST with the flaws we don't like, non controllable message sizing.  By having an efficient service layer you are only hitting middleware / load balancers.  At Netflix, which is obviously not true of others, that the aforementioned is ok.  If the case is that prop A and prop B are _always_ requested, then request them both in one request.

**Comment by greim** [comment]
Thanks for the reply. I do actually see the unrequested data being physically sent over the network, but yeah it doesn't get cached in the model afterward. I understand what you're saying; I was mainly coming the POV of easing the transition from REST to Falcor. Especially since sending extra data over the wire is opt-in. If you follow the given formulas, only requested data gets sent.

**Comment by michaelbpaulson** [comment]
The primary reason why un-opted-in extra data is a bad idea is simply you wont know what data you are getting.  You could only need the title for 100 movies, but get the entire movie object for all 100 when only 1 to 2 actual entire movie objects are needed.  So, for Netflix, it has always been better to have fine grain control over what data is being requested.
