### ISSUE TITLE
how about enable $ref point a $atom ?

### ISSUE THREAD

**Issue by ustccjw** [Netflix/falcor#620]
case code like this:

````
get: async pathSet => {
		const { from, to } = pathSet.indexRanges[0]
		const articles = await Article.get(from, to)
		const result = []
		articles.
			map(article => JSON.parse(article)).
			forEach((article, index) => {
				result.push({
					path: ['articles', index],
					value: $ref(['articleByNumber', article.number]),
				})
				result.push({
					path: ['articleByNumber', article.number],
					value: $atom(article),
				})
			})
		return result
	}
````

**Comment by michaelbpaulson** [comment]
@ustccjw you are very close to having this finished.  The remainder of work would be around a light caching layer (optional to get it to work, but required for production).  That can be discussed if needed.  

Second thing to do is add a second route that gets individual properties off the article.

```javascript
{
    route: 'articleByNumber[{integer:ids}]["prop1", "prop2", "prop3"]',
    get: function getArticleByNumber(aliasMap) {
        var ids = aliasMap.ids;
        var props = aliasMap[2];
        
        // this has been written assuming that getArticles is sync
        const articles = await Article.get(ids); // caching is awesome here
        return articles.
            map((article) => {
                return props.map((prop) => {
                    return {path: ['articleByNumber', article.number, prop], value: article[prop]};
                });
            }).
            reduce((acc, pathValues) => {
                return acc.concat(pathValues);
            }, []);        
}
```

```javascript
// The following queries would work then.
model.get(['articles', {to:9}, ['title', 'description', 'rating']]).subscribe((x) => {
    console.log(x);
});  

// OUTPUT
{
    articles: {
        0: {
            title: 'Total Recall',
            description: 'The greatest film ever with Arnold',
            rating: '6/5'
    },
    ...
}
```

You could also add a route that simply has 1 property `article` that just has all the article data on it.  Then your query would look something like

```javascript
// The following queries would work then.
model.get(['articles', {to:9}, 'article']).subscribe((x) => {
    console.log(x);
});  

// OUTPUT
{
    articles: {
        0: {
            article: {
                title: 'Total Recall',
                description: 'The greatest film ever with Arnold',
                rating: '6/5',
                ... the x amount of remaining fields would be here. ...
            }
    },
    ...
}
```

Hopefully that helps.

**Comment by ustccjw** [comment]
Thanks for the nice answer.

I use redis to cache. For my case, i use article as a atom, but I found i can not ref a atom: i can not get the article by ['articles', no], which ref the ['articleByNumber', number]

**Comment by trxcllnt** [comment]
@ustccjw If a reference points directly to an atom (as opposed to the "branch" just before an atom), you can retrieve it directly by appending `null` to the end of the path: `['articles', articleNumber, null]`.

**Comment by ustccjw** [comment]
@trxcllnt sorry, i can not understand. Can you show me code clearly? Thanks!

**Comment by michaelbpaulson** [comment]
Essentially what he is saying is the following: 

Here is your route
```javascript
get: async pathSet => {
        const { from, to } = pathSet.indexRanges[0]
        const articles = await Article.get(from, to)
        const result = []
        articles.
            map(article => JSON.parse(article)).
            forEach((article, index) => {
                result.push({
                    path: ['articles', index],
                    value: $ref(['articleByNumber', article.number]),
                })
                result.push({
                    path: ['articleByNumber', article.number],
                    value: $atom(article),
                })
            })
        return result
    }
```
So you will produce a jsonGraph response like the following.

```javascript
{
    jsonGraph: {
        articles: {
            0: {$type: 'ref', value: ['articlesByNumber', 0]},
            ...
        },
        articlesByNumber: {
            0: {
                $type: atom,
                value: {... article in full ...}
            }
        }
    }
}
```

to be able to query that, you need to get the value _after the reference_.  One of the designs of the query language is that it will follow references **up to** the last key, but **not** the last key of the query.  So for me to get out data here is an example query.

```javascript
model.get(['articles', 0]).subscribe((x) => { ... });

// x
{
    json: {
        articles: {
            0: {$type: ref, value: ['articles', 0]}
        }
    }
}  

// But thats a reference!  I want the value!!!!
// "As you wish" (can you guess the movie quote?)
model.get(['articles', 0, null]).subscribe((x) => { ... });

// x
{
    json: {
        articles: {
            0: { ... article object ... }
        }
    }
}
```

As I mentioned earlier, the model will follow references **up to** the last key in a path query, but **not** the last key.  We can get around this issue by adding an extra key at the end of the path.  `null` tells the matching algorithm to _skip_ this key.  This will provide the correct behavior you are looking for.  

The aforementioned answer I gave is a more _falcory_ way of doing things.  Don't make a reference point directly to an object, but instead provide a way to pluck individual properties off that object.  To get real crazy, it is ok, in our eyes, to have a reference point to another reference.

**Comment by ustccjw** [comment]
Much thanks!  I got the falcory way!
