### ISSUE TITLE
Path invalidation: nextCache undefined

### ISSUE THREAD

**Issue by IwanKaramazow** [Netflix/falcor#621]
I'm trying to incrementally rebuild pieces of a webapp with falcor. Currently I'm at the 'admin'-section: this mainly consists of displaying (paginated lists) with the ability to edit/add/remove items from that list.

Example admin-language-section:
The web app is available in 3 different languages. Current model & router:
```javascript
// domain model
{
  languagesById: {
    123: {
      en: 'EnglishTitle',
      fr: 'FrenchTitle',
      nl: 'DutchTitle'
    },
    345: {
      en: 'Hello',
      fr: 'Bonjour',
      nl: 'Hallo'
    },
    ...
  },
  languages: {
    list: {
      0: {$ref('languagesById[123]')},
      1: {$ref('languagesById[345]')},
      ...
    },
    length: 543 
  }
}

// Falcor routes
{
    route: 'languageList.list[{ranges:indices}]',
    async get(pathSeth) {
      // TODO check if user is admin!
      const list = await findLanguageRange(pathSeth.indices[0].from, pathSeth.indices[0].to);

      let results = [];

      list.map( (entry, index) => {
        const id = entry["_id"];
        results.push({path: ['languageList', 'list', index], value: ref(["languagesById", id])});
      });

      return results;
    }
  },
  {
    route: 'languagesById[{keys:languageIds}]["nl","en","fr"]',
    async get(pathSeth) {
      const results = await findLanguagesById(pathSeth[1]);

      let paths = [];

      pathSeth[1].map( (id, index) => {
        pathSeth[2].map( key => {
          paths.push({path: ['languagesById', id, key], value: results[index][key]});
        });
      });

      return paths;
    }
  },
  {
    route: 'languageList.length',
    async get(pathSeth) {
      const length = await countLanguageEntries();

      return { path: ['languageList', 'length'], value: length };
    }
  }, 
  { // remove a language item from the list
    route: 'languageList.list.remove',
    async call(callPath, args) {
      // args[0] === id of item
      // args[1] === index of item in list
      
      //todo check if user is admin
      const newLength = await removeLanguage(args[0]);

      return [
      pathInvalidation(['languageList', 'list', args[1]]),
      {
        path: ['languageList', 'length'],
        value: newLength
      }];
    }
  }
```

The problem arises at ```languageList.list.remove```. The entry in the database gets removed correctly & the client receives a newLength that is valid, but... something goes wrong with the pathInvalidation.

If I read the docs correctly, I have to set ```ìnvalidated: true``` for a certain path. If I want remove an item from the ```languageList.list```, the only thing I have to invalidate is the path: ```['languageList', 'list', indexOfItemToRemove]```, am I correct?
Do I also need to invalidate the same entry in the ```languagesById```?

When I remove an language-entry in the list with ```languageList.list.remove``` and do a ```console.log(model.getCache())``` I get a ```TypeError: cacheNext is undefined```.

Is this an issue, or did I screw up the router syntax?

Edit: this is probably related to https://github.com/Netflix/falcor/issues/589

**Comment by michaelbpaulson** [comment]
First off, things are looking great!  You have set up the routes (as far as I can tell) the exact way you should.  If the project you are working on is larger, please feel free to reach out to us and we can help / coach on some tricky situations.  If you have feed back / hopefully constructive criticism please don't hesitate. 

I think it would be best if we could get on a google hangout to debug this problem together.  I am genuinely unsure what is happening and this will be.  From what I am reading, this looks very correct.  You are properly invalidating the expected item in cache (languageList, list, {index}), and passing down a new length.  This should be enough for correct/expected behavior.  

Could we jump on a hangout today?
