### ISSUE TITLE
Falcor examples with RX

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#622]
I am new to both falcor and rx. Are there any examples of where I can use them both together. I have a rough idea of how would someone implement it, but it would be nice to see the right way.

**Comment by michaelbpaulson** [comment]
@almasakchabayev There are two things to be aware of.

* Versions 0.x emit Rx.Observables through inheritance.  
* Versions 1.x (**hasn't been released yet**) will break previous api and emit ModelResponses
  * ModelResponses are `subscribables`/`thenables`  They can easily be transformed to an observable.

If you are using _master_ then you will have to wrap the output from a `falcor.Model` with the following method found [here](https://github.com/Netflix/falcor/blob/master/MIGRATIONS.md#no-more-rx). The aforementioned link has links to the docs on ModelResponses as well.

We also have an [example app](https://github.com/Netflix/falcor-express-demo).  If you run into any issues, feel free to re-open this ticket!

**Comment by almasakchabayev** [comment]
@michaelbpaulson thanks for an early reply. I have seen these examples, however they do not use observables. I wonder how would someone would use observables on both server and client. Also can you share approximate date of when falcor 1.x would be released?
