### ISSUE TITLE
Falcor subscribe not working as expected

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#626]
Hello in the following example:
```
import React from 'react';
import ReactDOM from 'react-dom';
import falcor from 'falcor';
import _ from 'lodash';

const model = new falcor.Model({
  cache: {
    todos: [
      {
        text: 'check falcor',
        completed: false,
      },
      {
        text: 'do some codewar',
        completed: false,
      },
      {
        text: 'finish pluralsight',
        completed: false,
      }
    ]
  }
});

const App = ({todos = [], addTodo}) => <div>
  {_.values(todos).map((todo, index) => <TodoListItem todo={todo} index={index} />)}
</div>;

const TodoListItem = ({todo, index}) => <div>
  {todo.text} - {todo.completed.toString()}
  <button onClick={e =>
    model.setValue(`todos[${index}]["completed"]`, true).then(done => console.log(done))}
  >Check as done</button>
</div>;

const rootElement = document.createElement('div');
document.body.appendChild(rootElement);
var eventStream = model.
  get('todos[0..1]["text", "completed"]').
  subscribe(data =>
    ReactDOM.render(<App todos={data.json.todos} />, rootElement)
  );
```

When I click a button `Check as done`  I see `true` being printed in console. I was then expecting that `model.get('todos[0..1]["text", "completed"]').` would emit new event with new data which would trigger `ReactDOM.render(<App todos={data.json.todos} />, rootElement)` to rerender the component with new data, however it does not happen. What am I misunderstanding

**Comment by dzannotti** [comment]
To the best of my knowledge, this is an expected behaviour subscription is not for updates, but to allow you to cancel the request before it's fullfilled if you are looking for updates, you should use  the `onChange` callback of the model

**Comment by almasakchabayev** [comment]
@dzannotti Well model.get().onChange() throws onChange is not a function...

**Comment by dzannotti** [comment]
`onChange` is a function passed to the constructor of the model, see http://netflix.github.io/falcor/doc/Model.html
```
new falcor.Model({ 
    ...yourConfig, 
   onChange: function() {
       console.log('someone did a set/call')
  }
})
```

You can also use `model.getVersion(path)` to track which part of the tree changed/require refetching.

**Comment by almasakchabayev** [comment]
@dzannotti Thanks for sharing info. However I do not have a reference to model inside onChange, right?

**Comment by almasakchabayev** [comment]
@dzannotti Ok, I got it. `get(...).subscribe(...)` completes immediately for some reason. I can only break it into a stream of data from cache and from server (which is good). SO for model updates I ended up doing this:

```
import React from 'react';
import ReactDOM from 'react-dom';
import falcor from 'falcor';
import _ from 'lodash';
import Rx from 'rx';
const $ref = falcor.Model.ref;

const subject = new Rx.Subject();

const App = ({todos = []}) => <div>
  {_.values(todos).map((todo, index) => <TodoListItem todo={todo} index={index} />)}
</div>;

const TodoListItem = ({todo, index}) => <div>
  {todo.text} - {todo.completed.toString()}
  <button onClick={e => {
    model.set(falcor.Model.pathValue(`todos[${index}]["completed"]`, true)).subscribe();
    subject.onNext();
  }}>Check as done</button>
</div>;

const rootElement = document.createElement('div');
document.body.appendChild(rootElement);

var model = new falcor.Model({
  // source: new falcor.HttpDataSource('./model.json');
  cache: {
    todos: [
      {
        text: 'check falcor',
        completed: false,
      },
      {
        text: 'do some codewar tasks',
        completed: false,
      },
      {
        text: 'finish pluralsight',
        completed: false,
      }
    ]
  },
});
subject.subscribe(() => model.
    get('todos[0..1]["text", "completed"]').
    forEach(data =>
      ReactDOM.render(<App todos={data.json.todos} />, rootElement)
    )
);
subject.onNext();

```

**Comment by trxcllnt** [comment]
@almasakchabayev yes, the best way to do this is to provide an onChange handler to the root Model:

```es6
import React from 'react';
import ReactDOM from 'react-dom';
import falcor from 'falcor';
import _ from 'lodash';
import Rx from 'rx';
const $ref = falcor.Model.ref;
const $pathValue = falcor.Model.pathValue;

const App = ({todos = []}) => <div>
  {_.values(todos).map((todo, index) => <TodoListItem todo={todo} index={index} />)}
</div>;

const TodoListItem = ({todo, index}) => <div>
  {todo.text} - {todo.completed.toString()}
  <button onClick={e => {
    model.set($pathValue(`todos[${index}]["completed"]`, true)).subscribe();
  }}>Check as done</button>
</div>;

const rootElement = document.createElement('div');
document.body.appendChild(rootElement);

var rootModel = new falcor.Model({
  // source: new falcor.HttpDataSource('./model.json');
  onChange() {
    modelChanges.onNext(rootModel);
  }
  cache: {
    todos: [
      {
        text: 'check falcor',
        completed: false,
      },
      {
        text: 'do some codewar tasks',
        completed: false,
      },
      {
        text: 'finish pluralsight',
        completed: false,
      }
    ]
  },
});
const modelChanges = new Rx.BehaviorSubject(rootModel);
modelChanges
  .flatMapLatest((model) => {
    return model.get('todos[0..1]["text", "completed"]');
  })
  .subscribe(({json}) => {
    ReactDOM.render(<App todos={json.todos} />, rootElement);
  });
```

**Comment by almasakchabayev** [comment]
@trxcllnt thanks for the answer! I receive the error `Cannot read property onNext of undefined` though. Seems that modelChanges var is not defined when rootModel is initialized

**Comment by almasakchabayev** [comment]
@trxcllnt I digged to source code and the current way I am doing it is via using `_root`:
```
...
const modelChanges = new Rx.BehaviorSubject(rootModel);
rootModel._root.onChange = () => {console.log('new model streamed');modelChanges.onNext(rootModel);}
```

**Comment by dzannotti** [comment]
not tested but something like this should work - atleast should give you an idea how to use onChange incase you want to refetch onChange
```
import React from 'react';
import { render } from 'react-dom';
import falcor from 'falcor';

const $ref = falcor.Model.ref;
const $pathValue = falcor.Model.pathValue;

const App = ({todos = []}) => <div>
  {_.values(todos).map((todo, index) => <TodoListItem todo={todo} index={index} />)}
</div>;

const TodoListItem = ({todo, index}) => <div>
  {todo.text} - {todo.completed.toString()}
  <button onClick={e => {
    model.set($pathValue(`todos[${index}]["completed"]`, true)).subscribe();
  }}>Check as done</button>
</div>;

const rootElement = document.createElement('div');
document.body.appendChild(rootElement);

var rootModel = new falcor.Model({
  // source: new falcor.HttpDataSource('./model.json');
  onChange() {
    model.get('todos[0..1]["text", "completed"]').then((json) =>
        render(<App todos={json.todos}/>, rootElement)
    )
  },
  cache: {
    todos: [
      {
        text: 'check falcor',
        completed: false,
      },
      {
        text: 'do some codewar tasks',
        completed: false,
      },
      {
        text: 'finish pluralsight',
        completed: false,
      }
    ]
  },
});
```

**Comment by almasakchabayev** [comment]
Thanks, the problem is that model is not defined in onChange, so I get `Cannot read property 'get' of undefined`

**Comment by michaelbpaulson** [comment]
Are there any action items that should be addressed here?   Or is this a _user land_ issue?

**Comment by dzannotti** [comment]
it's a user land issue

**Comment by dzannotti** [comment]
@almasakchabayev - sorry I didn't test it, just modified the code blindly
just ran this on react-heatpack and confirm it works
```
import React from 'react';
import { render } from 'react-dom';
import falcor from 'falcor';

const $ref = falcor.Model.ref;
const $pathValue = falcor.Model.pathValue;

const TodoListItem = ({ todo, index }) =>
  <div>
    {todo.text} - {todo.completed.toString()}
    <button onClick={e => {
      rootModel.set($pathValue(`todos[${index}]["completed"]`, true)).subscribe();
    }}>Check as done</button>
  </div>
;


const App = ({ todos = [] }) =>
  <div>
    {Object.values(todos).map((todo, index) => <TodoListItem todo={todo} index={index} />)}
  </div>
;

const rootElement = document.querySelector('#app');

const rootModel = new falcor.Model({
  // source: new falcor.HttpDataSource('./model.json');
  onChange() {
    if (typeof rootModel === 'undefined') {
      return;
    }
    triggerRender();
  },
  cache: {
    todos: [
      {
        text: 'check falcor',
        completed: false,
      },
      {
        text: 'do some codewar tasks',
        completed: false,
      },
      {
        text: 'finish pluralsight',
        completed: false,
      }
    ]
  },
});

function triggerRender() {
  rootModel.get('todos[0..1]["text", "completed"]').then(({ json }) =>
    render(<App todos={json.todos}/>, rootElement)
  )
}

triggerRender()
```

**Comment by almasakchabayev** [comment]
@dzannotti It works! Thanks a lot! Although it does not fill very reactive :) Could you may be please explain how you use falcor with rx in netflix? And how would I need to structure a non-trivial application

**Comment by dzannotti** [comment]
@almasakchabayev i do not work for netflix, so i have no idea how they use falcor internally sorry. As far as the reactivity goes, looks reactive enough even tho an react implementation of an HoC that binds to a path and checks versioning of the tree and passes down to children the bound model as context it's probably more efficient/reactive

**Comment by almasakchabayev** [comment]
@dzannotti how do I bind to a path in falcor? There is nothing in documentation about it... That is what I was looking for initially

**Comment by dzannotti** [comment]
http://netflix.github.io/falcor/doc/Model.html#deref

**Comment by almasakchabayev** [comment]
@dzannotti Thanks. Do you may be have link to any examples that uses deref. From just API documentation it is difficult yo understand how that works in practice

**Comment by michaelbpaulson** [comment]
@almasakchabayev So this is very interesting... deref.  In master deref works _completely_ different than it does in latest npm.  In the npm version deref is not ergonomic, it _async_ resolves.

Here is how master works:

```javascript
model.get([path, {to:9}, my, datum]).subscribe((x) => {
    // Pass the point in the output in which you wish to deref to!
    var pathModel = model.deref(x.json.path);
});
```

Current deref (in npm) flips the notion of a get then deref to deref then get (which is less performant and ergonomic).

```javascript
model.
    deref(
        // Path to deref to
        [path], 
        // leaf nodes, at least one needs to be included.
        [{to:9}, my, datum]).
    subscribe((pathModel) => {
        // perform gets here
        pathModel.get([{to: 9}, my, datom]).subscribe(...);
    });
```

As you can see master has much better integration with top down renderers (like react) and deref.  You get to use the output you generate to deref to that point in the graph.

I hope that answers your questions.

**Comment by almasakchabayev** [comment]
@michaelbpaulson Thanks, that answers my question. Could you also please elaborate on how would you built a reactive MVI architecture with falcor, where M is falcor model (like redux store and I would use deref as connect) V is React (not sure how to go about routing). This is the main intent of what I am trying to do. Do you think the approach I took is a step in right direction or it is completely off.

**Comment by jhartma** [comment]
I am not so familiar with Rx, but if you're interested,  [here is an example](https://github.com/jhartma/express-react-redux-falcor) of how Falcor and Redux seemingless and without much effort work together, including updating the dom.

**Comment by almasakchabayev** [comment]
@jhartma Thanks for the resource, will have a look.

**Comment by michaelbpaulson** [comment]
@almasakchabayev are we good to close this down?

**Comment by almasakchabayev** [comment]
Sure, sorry
