### ISSUE TITLE
Subscribe to model changes?

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#627]
Hello,

Is it possible to subscribe to model changes, i.e. suppose I want to `get('todos[0]["completed"]').subscribe(//render function)` and after `setValue('todos[0]["completed"]', true)` model emits new data and render function is invoked with this new data?

**Comment by jhartma** [comment]
If you use redux and [redux-falcor](https://github.com/ekosz/redux-falcor/blob/master/src/actions.js) you get that for free. It kind of merges the model into the redux store, so when you read or write to the falcor model, it updates the store and all your views get updated, too.
It is not so well documented, however, but you can easily grasp the actions from the source code.

**Comment by almasakchabayev** [comment]
@jhartma I am just not familiar with redux. I am familiar with Rx (and falcor is built with Rx), so I thought there is some way to observe model changes

**Comment by michaelbpaulson** [comment]
@almasakchabayev Falcor's Model constructor does take a `onChange` handler that will notify you when the graph has changed.

```javascript
var model = new Model({
    onChange: changeHandler
});

function changeHandler() {
    console.log('graph has changed');
}

model.setValue(['running', 'man'], 5).subscribe((x) => {
    console.log('subscribe.onNext', x);
});

// consoled
> subscribe.onNext {
    json: {
        running: {
            man: 5
        }
    }
}
> graph has changed

**Comment by michaelbpaulson** [comment]
@almasakchabayev If this is satisfying please close the issue or further comment.  Thanks.

**Comment by almasakchabayev** [comment]
@michaelbpaulson Thanks, one question though. I have just found that there was a discussion about .observe method here https://github.com/Netflix/falcor/issues/91, which would be exactly what I was looking for. If I understood correctly the feature will not be implemented. Are there any plans on something similar?

**Comment by michaelbpaulson** [comment]
For now we have no plans of supporting observe.  Now this can change, but in the near future that is not the case.  `onChange` is our suggested change detection.

**Comment by almasakchabayev** [comment]
So the suggested way would be to create a subject and onNext it in the onChange callback?

**Comment by michaelbpaulson** [comment]
Depends an what technologies / methodologies you are using.  There is not one canonical way since there is not one canonical javascript framework.

**Comment by almasakchabayev** [comment]
@michaelbpaulson  ok, thanks for quick replies
