### ISSUE TITLE
How to model an arbitrarily-sized list that contains refs

### ISSUE THREAD

**Issue by ckknight** [Netflix/falcor#630]
I'm working on modeling something with the rough shape:

    scene = {
      sprites: [{
        sprite: $ref('spritesById.someid'),
        position: {x: 0, y: 0},
      }]
    }

I've tried the following approaches:

* Treating `scene.sprites` as a single atom.
 * This has the downside of being unable to  reference back to the actual sprite, as a ref inside an atom is unqueryable.
* Treating `scene.sprites` as a queryable array that exposes its indices and `length`.
 * The client needs to pull down all sprites at once before a scene is rendered, so I can either pull down `scene.sprites.length` first, then `scene.sprites[0..(len)]`, but that requires 2 network requests minimum.
 * Alternatively, I tried pulling down `scene.sprites.length` and `scene.sprites[0..100]` simultaneously. it's typical that a scene may have ≈10 or so, so handing the atypical but very possible case of 100 would work (and if necessary pull the remaining given the known `length`). This has the downside that if there is only 1 sprite in the scene, then the response is bloated with `{ $type: "atom" }` for each sprite that does not exist, for each field requested on the nonexistent sprite.

**Comment by trxcllnt** [comment]
@ckknight your second solution is typically what we'd recommend. Is the worst-case (99 "undefined" atoms) a true show-stopper, or more of an annoyance? If I recall correctly, Falcor's internals can handle merging incomplete server responses, so if it's a show-stopper, perhaps @michaelbpaulson has some ideas on if it's possible/valid to change falcor-router to omit the "undefined" atoms in its responses.

**Comment by ckknight** [comment]
Well, I gave a small subset of the actual data needed to fully render a scene to the user.

The worst case is actually not 99 undefined atoms, but multitudes of that. For every sprite, I need multiple pieces of referenced data, which bloats the jsong envelope further and further.

Oh, and given that users start off by default with 3 scenes and we already have users with >50, this is a big consideration.

Also, I really don't want to sacrifice much on network bandwidth, as I'm designing with an offline-first, mobile-first, slow internet-compatible mindset. There's still users out there on GPRS.

**Comment by michaelbpaulson** [comment]
@ckknight We have actually been kicking around the idea of adding making `materializedPaths` a part of the JSONGraphEnvelope (attributed to @ktrott).  This could significantly reduce envelope size for you.  But there is no good way of solving this problem through `get` currently (and more than likely forever).  @trxcllnt has experimented with using `call` to load all the paths.  It would look something like this.

```javascript
var routerParent = new Router([{
    route: 'user.loadSprites',
    call: function loadAllSprites() {
        
        // pretending that your api back an array.
        var sprites = loadAllSpritesByUser(this.req.USER_COOKIE_ID);
        return sprites.
            map(function(sprite) {
                return [{
                    path: ["sprite", sprite.index],
                    value: $ref(["spritesById", sprite.id]),
                }, {
                    path: ["spritesById", sprite.id],
                    value: sprite.toValue() // whatever value you want to pass down.
                ];
            }).
            concat({path: ['sprites', 'length'], value: sprites.length});
    }
}]);
```

Then you can do something like
```javascript
model.call(['user.loadSprites']).subscribe(undefined, undefined, onLoad);

function onLoad() {
    // all data will in the cache at this point, you can start your top down renderer.
}
```

Sorry this was in a rush, hopefully makes sense.

**Comment by michaelbpaulson** [comment]
@ckknight Are we good?

**Comment by ckknight** [comment]
It feels highly unsatisfying, especially regarding what sprite data to pass down. One call may want some subset of the sprite data (e.g. just the name), and another may want another subset (e.g. the url and size).

Also, that this is so outside of normal falcor data access leaves a bad taste in my mouth and makes me worried for maintainability and upgradability.

_Note: I understand that "ick factor" is subjective, but it's blaring right now_

**Comment by michaelbpaulson** [comment]
@ckknight perhaps you have misunderstood me.  The `call` is only performed at initial load.  The rest would use `get` as their method.  

There is no way, currently, to load _all_ of the data in a range.  So you can do 1 of three things:  

* Overfetch: what you are currently doing.
* Underfetch / virtualize:  This works for the 90% use case considering ranges are used with list items.  The list items then are able to be virtualized and only a small proportion can see at any one time.
* Call preloading:  You still get all the benefits of caching and perfect message sizing.  The downside is the initialLoad of your program is separated from the rest of your program.  Your standard render flow and everything else should be worked off of `get`, its just that first call is a `call`.

**Comment by IwanKaramazow** [comment]
I ran into a similar problem when trying to get something like ```recipes.list[{keys:ids]].["title","ingredients"]``` .
```javascript
list : {
  id: {
     title: 'chocolate cake'
     ingredients: {
      0: 'chocolate',
      1: 'cake'
     }
   }
}
```
Ingredients is an array with a variable length of ingredients, there's no way of knowing the length upfront... It could be 2 ingredients, it could be 20 ingredients.

Is overfetching, e.g. [0..30], the 'best practice' in the case?

**Comment by michaelbpaulson** [comment]
@IwanKaramazow @ckknight We have potential solutions that we will be exploring through 2016, but for now over-fetching has been our approach as it works well in our use-case.  As we formalize the changes we will be making a ticket to track the upcoming changes and to explain how it works to the community.  For now I am going to close this ticket as all current solutions have been put on the table.  Which to re-iterate are

* over-fetch
* fetch some and display with virtualizing the rest of the list (imagine a movie list but you only need the first 7 items to display the list until the user starts to scroll).
* the initial load of the list uses a `call` operation to perfectly load the required data with length, references, and data in one call.  All UI calls go through `get` to get out the cache / extra data needed from server.

**Comment by mik01aj** [comment]
@michaelbpaulson if you already have `$type:"atom"` and `$type:"ref"`, why not add `$type:"atomWithRefs"` or `$type:"listWithRefs"` where the references could be handled?

I have a situation where a discussion entry has attachments. In my REST API, they are just lists of Ids (`attachedAuthorIds`, `attachedBookTitleIds`, `attachedImageIds`). In Falcor, I have to make a hard choice like @ckknight explained. I think that adding types like these would be practical.
