### ISSUE TITLE
Defining DataSource in a Crossdomain

### ISSUE THREAD

**Issue by AJMoura** [Netflix/falcor#631]
Hello,

I'm currently using two local machines (in the same network) trying to communicate HttpDataSource to a falcor router and it gives me a CORS error.

I have the Model side developed in Node.js / Angular / Falcor, and the Router in Node.js.
Is this viable or will it be possible?

Best regards.

**Comment by threepointone** [comment]
Yes, you should be able to enable CORS in your express app. Try adding this before any other routes - 
```js
app.all('/', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "X-Requested-With");
  next();
 });
```

**Comment by filipeperdigaosousa** [comment]
I tested your solution and it doesn't work...

The client application is still getting the same error about "cross domain". Any other suggestion?

Thank you.

**Comment by gdi2290** [comment]
var source = new HttpDataSource('/model.json', {
  crossDomain: true
});

**Comment by michaelbpaulson** [comment]
@gdi2290 I assume you are correct to your solution so I'll be closing this ticket down :)
