### ISSUE TITLE
documentation: there are some errors 

### ISSUE THREAD

**Issue by warmhug** [Netflix/falcor#632]
http://netflix.github.io/falcor/documentation/model.html  

In the section "Retrieving Data from a Model"

```js
model.getValue("todos[0].customer").then(log); 
// prints {name: "Jim Hobart", address:"123 pacifica ave., CA, US"} because the value of an Atom is considered a value
```
where `todos[0].customer` should be `todos[1].customer`!

And, there are some repeat statements and small problems in other documentations. Please pay attention to these details

**Comment by michaelbpaulson** [comment]
Please feel free to submit a PR, we love helping hands!  If not, we can certainly take care of this at some point.
