### ISSUE TITLE
Conditional path retrieval, local cache vs unmatched routes

### ISSUE THREAD

**Issue by IwanKaramazow** [Netflix/falcor#642]
Current scenario:
A user logs in in a 30-day daily challenge app. He gets redirected to the dashboard and there we fetch
the current day like:
```javascript
model.get('challenges.currentDay') //returns the current day, e.g. '5'
```
There are two possibilities:
-if a user completed the 'challenge-of-the-day', we need to retrieve the result for that given day.
-if a user hasn't completed any challenge for that given day, we need to fetch a list with customized, possible challenges.

```javascript
// router
{ route: 'challenges.currentDay',
 async get(pathSet) {
    const paths = [];
     const user = await findUserById(this.userId);
     // pseudo-code
    if ( !user.challenges[currentDay].completed)
         // fetch some random challenges a add the paths to 'paths' for the random list of challenges
    else 
         // fetch the result of the challenge for the currentDay, and add the relevant paths to 'paths'
   paths.push(pathValue(['challenges', 'currentDay'], user.currentDay));
   return paths;
}
```

Is this the right approach to avoid two network requests? If I first request the currentDay and afterwards go back and fetch the necessary data for that given currentDay, I could as well be using REST...

I thought the above result would work, but apparently when I query the model like
```javascript
model.get('challenges.currentDay').then( res => 
     model.get(['challenges', 'possibilities', {from: 0, to: 2}, ['title', 'info']]).then( res => 
         console.log(res) // undefined ))
```
The jsongraph in the network-tab seems to have all data.
The problem is my datasource only handles ``` route: 'challenges.currentDay' , route: 'challengesById[{integers: ids]```.
I guess the cache checks the datasource for the possibilities, no matching routes for the possibilities, and returns atoms.

Isn't it redundant to add a route for ```['challenges', 'possibilities', {from: 0, to: 2}, ['title', 'info']]```, if ```['challenges', 'currentDay']``` returns the path for the ```possibilities``` & refs pointing to```challengesById``` if certain conditions are met?

**Comment by mik01aj** [comment]
I don't see why you don't return a `$ref` to `['users', id, 'challenges', dayNumber]` in your `challenges.currentDay` route handler.

**Comment by IwanKaramazow** [comment]
Never thought of it like that.
In the constructor of the router class, the ```ìd``` of the user gets set to ```this.userId```
That's why I don't access ```['users', id]``` and go straight to the ``` ['challenges', dayNumber ]``` part.

If I ever manage to get a descent understanding of falcor, I'll write a 'Thinking in falcor' blogpost..

**Comment by IwanKaramazow** [comment]
Fixed it somehow, no idea why, but the approach as described above now works.

**Comment by michaelbpaulson** [comment]
Perfect.  Glad to hear.  I was going to give some advice but I am glad to hear all is well.  Thanks for the support / engagement with falcor.
