### ISSUE TITLE
The router calls the same route many times needlessly

### ISSUE THREAD

**Issue by mik01aj** [Netflix/falcor#643]
I have a route for `works.[{integers}].title`, in a router that is exposed via `falcorExpress.dataSourceRoute`. When I request this...

    /model.json?paths=[["works",123,"title"],["works",123,"title"]]&method=get

...the underlying `Router` instance calls the `get` handler for my route twice, with the same arguments. Why aren't these requests batched?

-----

I know that requesting the same path twice is stupid and you can avoid it by using `.batch()` on the client-side `falcor.Model`, but the same situation happens also when I request `PathSet`s like these:

```
model.batch().get(
    ['someCollection', id, 'someReferencedObject', 'name'],
    ['someCollection', id, 'someReferencedObject', 'childObject', 'stuff]
).then(...)
```

In this case, the route handler for `['someCollection', id, 'someReferencedObject']` would be still called twice (the client-side `.batch()` doesn't help here).

**Comment by michaelbpaulson** [comment]
@mik01aj you have a two part question:

##### why doesn't `/model.json?paths=[["works",123,"title"],["works",123,"title"]]&method=get` call my handler once?  

All paths sent to a router go through collapse first if you are using a Model.  That request you have made should never happen from a falcor model.  So that is truly a _bad_ request.  If a model generated that, please get code that causes that.

##### why do multiple get requests, regardless of batch, sometimes result in multiple requests to a route handler?

We process each path on the server one at a time.  Since the above example, the two paths are **not** collapsable, therefore we evaluate them independently.  This is where a service layer becomes very handy.

If you have further questions please feel free to ask, else close the ticket please.

**Comment by michaelbpaulson** [comment]
@mik01aj I just thought of something, there could be a way of achieving this within the router as well.  It would involve this piece of code, https://github.com/Netflix/falcor-router/blob/master/src/run/recurseMatchAndExecute.js#L114 - https://github.com/Netflix/falcor-router/blob/master/src/run/recurseMatchAndExecute.js#L122 up above at the top of the expansion loop.  That should effectively do what you are asking for.

**Comment by michaelbpaulson** [comment]
I am going to close this ticket and open it on the router.

**Comment by michaelbpaulson** [comment]
Sorry for the ticket spam.  That probably wont help at all actually...  It will only help if the handlers are _sync_.

**Comment by mik01aj** [comment]
> We process each path on the server one at a time. Since the above example, the two paths are not collapsable, therefore we evaluate them independently. This is where a service layer becomes very handy.

I don't understand the reason behind this design decision. Why not run them in parallel?

And as a "service layer", you mean, an ORM, or a HTTP client that supports caching, right? Maybe this would be a solution for now.

**Comment by michaelbpaulson** [comment]
You just said yourself.  Why not run them in parallel?  Well this is the issue at its crux.  You are given 2 uncollaspable routes and you want to run them in parallel?  Well there are bound to be collisions.  

There are solutions that we talked about but that would require each route being processes to know whats "in flight" and if it matches its route or some intersection of its route.  Then essentially calculate the complement and execute immediately while waiting for the intersection portion to finish.   

So its possible, just would require time.  As of now, adding a model as a service layer seems to work well.

I cannot find my example of it, so here is a basic new one.  This will be javascript shorthand.

```javascript

var serviceModel = new Model({
    source: new Router([{
        route: 'works[{integers}]',
        get: function getWorks(aliasMap) {
            //... return you stuff here ...
        }
    }]);

}).batching();

var applicationRouter = new Router([{
    // Hopefully you see how this could be used to get entire objects and pluck
    // requested props off
    route: 'works[{integers}].title',
    get: function getWorksProps(aliasMap) {
        return serviceModel.
            get(aliasMap).
            ... Do stuff to your code so that it returns path values ...
            ... Use the service model to aleviate _concurrent_ requests...
    }
}]);

```

**Comment by mik01aj** [comment]
> You are given 2 uncollaspable routes and you want to run them in parallel? Well there are bound to be collisions.

For the `get` method, I don't see a problem. 

> There are solutions that we talked about but that would require each route being processes to know whats "in flight" and if it matches its route or some intersection of its route. Then essentially calculate the complement and execute immediately while waiting for the intersection portion to finish.

Yes, that's what I meant. I did it similarly in [flying-squirrel](https://github.com/lovelybooks/flying-squirrel) ([see comparison](https://gist.github.com/mik01aj/ca4574e715284e63db52)).

**Comment by michaelbpaulson** [comment]
This issue will be discussed in our roadmap items.  Currently we will continue to recommend using a Model as a service layer (as above).

**Comment by mik01aj** [comment]
@michaelbpaulson, do you have any updates about your roadmap? :)

**Comment by michaelbpaulson** [comment]
@mik01aj 
Roadmap for falcor?  I think we will be posting our plans on github very soon (if that is what you are asking).  If you are asking about this specific issue and our roadmap, this issue (we do not consider it one) will more than likely never be addressed.  Its intentional that a serviceModel is used, thus requests will be batched and deduped.

**Comment by mik01aj** [comment]
I was referring to your comment from 3rd December. I'll wait for the upcoming update.
