### ISSUE TITLE
Mistake in Router walkthrough

### ISSUE THREAD

**Issue by mik01aj** [Netflix/falcor#648]
From http://netflix.github.io/falcor/documentation/router.html#walkthrough-building-a-router-for-netflix-like-application: 

![image](https://cloud.githubusercontent.com/assets/3027415/11566256/e1622da4-99e1-11e5-8500-c24ec7f361ad.png)

I think there should be `genreList[0,1,5..7,9].name` in the first code block. Correct?

Source link: https://github.com/Netflix/falcor/blob/gh-pages/documentation/router.md

**Comment by michaelbpaulson** [comment]
correct: And if you can, convert from legacy path requesting with stringSyntax to array syntax.  So it should be:

###### for example...
```
['genreList', [0, 1, 5, 6, 7, 9], 'name]
```

**Comment by mik01aj** [comment]
I can make a PR with this line fixed, but if you'd like to fix the syntax too, I'll better leave this to you. :)

**Comment by jhusain** [comment]
Would appreciate the PR. Will be refreshing documentation before next release, but until then every little bit helps.

thanks.

**Comment by mik01aj** [comment]
ok, see the PR.
