### ISSUE TITLE
multiple dataSources?

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#649]
Is it possible to have multiple dataSources, for instance one over http and the other over web sockets? If yes, then how to differntiate them when making a call?

**Comment by michaelbpaulson** [comment]
Yes is the simple answer:

I am just finishing up this: https://github.com/Netflix/falcor-datasource-chainer which has its rules and specifications for how it interacts with the model, router, and other dataSources here: #615 .

But this wont be "dev done" for a bit.  So in the mean time this can be achieved through composition.  You can always create your own dataSource that adheres to the dataSource contract (found [here](http://netflix.github.io/falcor/doc/DataSource.html)) which determines which dataSources to call and etc. etc.

Hope that helps.

**Comment by almasakchabayev** [comment]
Great! thanks.
