### ISSUE TITLE
Local cache and remote data Issue

### ISSUE THREAD

**Issue by Bretto** [Netflix/falcor#656]
I am requesting for some prop on an Item
```
model.get(`itemsById['${itemId}']['firstName']`).then(...)
``` 
So now I have ItemId.firstName in the local cache.
Now I do a second call
```
model.get(`itemsById['${itemId}']['firstName', 'lastName']`).then(...)
```
I already have the 'firstName' so Falcor only request for 'lastName' on the remote.
The Item on the remote doesn't have a 'lastName' prop and the result of the promise is undefined.
The problem is the result from my query in the Network tab is:
```
{"jsonGraph":{"itemsById":{"cihvjetqq00023k5nwpoy4d70":{"lastName":{"$type":"atom"}}}}}
```
but in my handler I am getting __undefined__, shouldn't Falcor still give me back the firstName from the cache no matter what as a result ? I am confused...

**Comment by LukeTillman** [comment]
I just hit this same behavior (only it was with a `deref` call instead of a `get`) where the already loaded and cached data wasn't included in the response when the server returns empty atoms. In my case, I was loading the first 5 items of a collection where the initial server response looked something like this:

```
{
  "jsonGraph" : {
    "videos" : {
      "0" : {
        "$type" : "ref",
        "value" : ["videosById", "29160f69-2d5c-4c21-8ec6-9e5b5ab8cdff"]
      },
      "1" : { "$type" : "atom" },
      "2" : { "$type" : "atom" },
      "3" : { "$type" : "atom" },
      "4" : { "$type" : "atom" }
    }
  }
(...snip)
}
```

Then later on a different page in the application, I was trying to load the first 10 items in that same collection. In that case, the request to the server was (correctly) only for items 5-9 since 0-4 were still cached from the earlier request. The response looked something like this:

```
{
  "jsonGraph" : {
    "videos" : {
      "5" : { "$type" : "atom" },
      "6" : { "$type" : "atom" },
      "7" : { "$type" : "atom" },
      "8" : { "$type" : "atom" },
      "9" : { "$type" : "atom" }
    }
  }
}
```

I was using deref (at `videos`) and got an empty observable that just called the `onComplete` callback (i.e. no model returned). I expected I'd get a model since there was a record at index 0 cached from the earlier call.

**Comment by michaelbpaulson** [comment]
I think @Bretto that you may have an error in your code.

```javascript
var falcor = require('falcor');
var Rx = require('rx');
var model = new falcor.Model({
    cache: {
        person: {
            firstName: 'bobby'
        }
    },
    source: {
        get: function() {
            return Rx.Observable.create(function(observer) {
                observer.onNext({
                    jsonGraph: {
                        person: {
                            lastName: falcor.Model.atom()
                        }
                    }
                });
                observer.onCompleted();
            });
        }
    }
});

model.
    get(['person', ['firstName', 'lastName']]).
    then(function(obj) {
        console.log(JSON.stringify(obj, null, 4));
    });

```

It just output the following
```bash
{
    "json": {
        "person": {
            "firstName": "bobby"
        }
    }
}
```

@Bretto Could you validate that you are not doing something incorrect in your code, because this is one of the standard operations of falcor.

**Comment by michaelbpaulson** [comment]
@LukeTillman I just built this and everything seems to work as expected.

```javascript
var falcor = require('falcor');
var Model = falcor.Model;
var Rx = require('rx');
var model = new falcor.Model({
    cache: {
        videos: {
            0: Model.atom(),
            1: Model.atom(),
            2: Model.atom(),
            3: Model.atom()
        }
    },
    source: {
        get: function() {
            return Rx.Observable.create(function(obs) {
                obs.onNext({
                    jsonGraph: {
                        videos: {
                            4: Model.atom(),
                            5: Model.atom(),
                            6: Model.atom(),
                            7: Model.atom()
                        }
                    }
                });
                obs.onCompleted();
            });
        }
    }
});

model.
    deref(['videos'], [{to:7}, 'summary']).
    subscribe(function(videos) {
        console.log(videos);
    });
```

this is falcor@0.1.12.  There are some bug fixes in 0.x that we are going to release soon, but that should not fix your issue it does not seem. 

Could you please give more context on your problem?  I could potentially debug it if I had more context.

**Comment by LukeTillman** [comment]
@michaelbpaulson Sorry, I probably didn't communicate that too clearly. Using your code as a starting point, I'm talking about a scenario like this:

```
var falcor = require('falcor');
var Model = falcor.Model;
var Rx = require('rx');
var model = new falcor.Model({
    cache: {
        videos: {
            0: { summary: 'Some summary' },
            1: Model.atom(),
            2: Model.atom(),
            3: Model.atom()
        }
    },
    source: {
        get: function() {
            return Rx.Observable.create(function(obs) {
                obs.onNext({
                    jsonGraph: {
                        videos: {
                            4: Model.atom(),
                            5: Model.atom(),
                            6: Model.atom(),
                            7: Model.atom()
                        }
                    }
                });
                obs.onCompleted();
            });
        }
    }
});

model.
    deref(['videos'], [{to:7}, 'summary']).
    subscribe(function(videos) {
        console.log(videos);
    });
```

The difference (from your code) being one of the items in the cache is already populated with some data. I would expect in this situation that the `console.log` call would be triggered with a model instance. I tested on 0.1.14 and it's not.

Does that help?

**Comment by Bretto** [comment]
The issue in my case was that I was returning undefined as a value, when I converted the undefined to null it fix the issue

**Comment by LukeTillman** [comment]
@michaelbpaulson If you want, I can open a separate issue if you can confirm the scenario I posted above. (Since this issue is closed now). Just let me know.

**Comment by michaelbpaulson** [comment]
@LukeTillman please do, its better for tracking purposes.
