### ISSUE TITLE
UnhandledPaths v2 (Master Ticket)

### ISSUE THREAD

**Issue by michaelbpaulson** [Netflix/falcor#665]
Previous spec for unhandledPaths https://github.com/Netflix/falcor/issues/615

**We are not going to do DataSource chaining as we are trying to avoid changing the JSONGraph interface.  This alternative method allows for easier composition of DataSources at the _Router_ level.**

--------------------------
We believe that composition will be a better path to take moving forward as unhandledPaths leak a notion that something can take care of the missing data. 

### Changes to the Router
There will be 3 new prototype methods added to the router.  The easiest way to think of the three methods is they have the same input as a [DataSource](http://netflix.github.io/falcor/doc/DataSource.html) but have the same return options as any routed method.

```javascript
/**
 * Takes in a function to execute when all unhandledPaths have been accumulated at the end of a
 * router request.
 * @param {Function} unhandledHandler - The get handler takes in a list of PathSets and can return
 * the same thing any route can, that is pathValues, jsonGraph, promises of either, or observables of
 * either.
 */
Router.prototype.onUnhandledGet = function(unhandledHandler) {
}; 
/**
 * @param {Function} unhandledHandler - The set handler takes in a jsonGraphEnvelope and can 
 * return same thing as any route.
 */
Router.prototype.onUnhandledSet = function(unhandledHandler) {
};   
/**
 * STILL REQUIRES MORE FLUSHING OUT - the paths / suffixes make an interesting facet to
 * how much should be taken care of by the unhandler vs the router itself.
 * @param {Function} unhandledHandler - The call handler takes in a callPath, arguments, paths, 
 * and suffixes and can return same thing as any route.
 */
Router.prototype.onUnhandledCall = function(unhandledHandler) {
};   
```

After a get/set/call if there were requests for routes that do not have corresponding handlers in the router then they will be accumulated until the end of the request.  After that the onUnhandled* will have a chance to generate their own jsonGraph.  The `this` object of the unhanlded* is the router object.

#### Materializing and unhandledPaths interaction within the Router
The flow is the following.  First we resolve all matchable routes.  We take that jsonGraph envelope and attempt to merge in any unhandledPaths from the unhandledHandler for the requested method.  Finally, only applying to get/set, the message will be materialized for any missing data. 

### Changes to the Model
None.  Horray!

### Extra Libraries
None.  Horray!

### Changes to the JSONGraphEnvelope
None.  Horray!

@jhusain @ktrott @sdesai Have we considered the following interface option.  `onUnhandledDataSource(DataSource source)`.  Since the three methods are a piecemeal DataSource with different return options.  Thoughts?

**Comment by sdesai** [comment]
> Have we considered the following interface option. onUnhandledDataSource(DataSource source).

Just to clarify for the thread (since we had this confusion offline): You're suggesting adding this, **in addition** to the 3 separate methods (`Router.prototype.onUnhandledGet`, ...). 

I think it makes sense, however if we do add it, I'd consider:

1. Collapsing the 3 separate on* methodsinto a single method also, for symmetry:

   `Router.onUnhandledPathsDataSource(DataSource source)`
   `Router.onUnhandledPaths(getHandler, setHandler, callHandler)`

2. Maybe collapse them into a single method (@ktrott's point) to avoid "which one wins" complications, if we provide 2 ways of registering to handle unhandled paths

**Comment by michaelbpaulson** [comment]
I really like option 2 as it prevents extra requests for control flow and _relative complement_ calculations.

**Comment by tivac** [comment]
Definitely prefer collapsing them into a single method. It's much simpler to reason about.
