### ISSUE TITLE
model.get(...).toPathValues is not a function

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#668]
According to docs there is a function responsible for traversing incoming json into a stream of pathValues: http://netflix.github.io/falcor/doc/ModelResponse.html#toPathValues

However when trying to use it it throws and there is no such a function in a source code: http://netflix.github.io/falcor/doc/response_ModelResponse.js.html

Has this function been removed?

**Comment by jhusain** [comment]
In the newest version this function has been removed to reduce file size. We didn't think it was necessary. FYI, you can return a JSONGraphEnvelope from a route handler in a Router.

**Comment by almasakchabayev** [comment]
@jhusain we need it to solve the following problem: 
We have a server-side model with ServerRouter, which caches db requests.
ClientRouter talks to server-side model.
server-side model returns json, but in ClientRouter I need to return pathValues. So i had to write my custom parser, which you can find here https://github.com/almasakchabayev/falcor-to-path-values.

Could you please guide us on how to approach it, without using custom parser

**Comment by michaelbpaulson** [comment]
@almasakchabayev You have asked this question on another question correct?  If so, please close this question down.  We don't *think* we will be re-supporting path values anytime soon, unless this issue keeps coming up.
