### ISSUE TITLE
difference between model.get(...).then and model.get(...).forEach

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#670]
I understand that one is Promise, the other is Observable. `.then` returns final json and after testing it seems that `.forEach` is only returning once. Are there any behavioral difference between the two? (except for that fact that one is Promise and the other is Observable of one)

**Comment by jhusain** [comment]
If you call the progressively() method on the model response the for each method will call you twice: once immediately with everything in the cache you requested, and then a second time once any outstanding debt is retrieved from the server.

Furthermore when you call for each, you get a Subscription object back which you can use to cancel the request.

**Comment by almasakchabayev** [comment]
@jhusain Thanks got it. But now I feel like `.progressively().subscribe()` and `progressively().forEach()` do the same thing. Could you please elaborate on differences here, thank you.

**Comment by michaelbpaulson** [comment]
There is no difference between forEach and subscribe. [Check out the code!](https://github.com/Netflix/falcor/blob/master/lib/response/ModelResponse.js#L78)
