### ISSUE TITLE
redirect deep route to default sorting route

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#672]
Is it possible to ref  `authorsById[{keys:ids}].posts.count` to `authorsById[{keys:ids}].posts["sort:createdAt=desc"].count` ?

I naively tried just reffing it like:
```
return {
            path: [`authorById`, id, 'comments', 'count'],
            value: $ref([`authorById`, id, 'comments', 'sort:createdAt=desc', 'count'])
          }
```

But what I get is : 
```
{
... {
        posts: {
            count: [
                'dealsById'
                'd5a50b08-8842-472a-b088-76ec4c20de53',
                'posts',
                'sort:createdAt=desc',
                'count'
            ]
        }
    }
}
```

I know that i can redirect from `[`authorById`, id, 'comments']` to `[`authorById`, id, 'comments', 'sort:createdAt=desc']`, but just wondering whether it is possible to make the previous behaviour work.

As a side note: is sorting done right?

**Comment by almasakchabayev** [comment]
Actually I cannot do redirect from `[authorById, id, 'comments']` to `[authorById, id, 'comments', 'sort:createdAt=desc']`

The following error is thrown: 
`References with inner references are not allowed.`

**Comment by michaelbpaulson** [comment]
@almasakchabayev you cannot do what you are attempting to do.  A reference cannot contain an inner reference means that while following a reference you cannot encounter another reference.  So if A -> [B, C] but B -> D then we throw out an error for such things :)

* I am curious what the router output is because it must not be what you think you are getting.  I would assume the jsonGraph coming back would look like

```javascript
{
    jsonGraph: {
        authorById: {
            <id>: {
                comments: ref(['authorById', <id>, 'comments', 'sort:createdAt=desc'])
            }
        }
    }
}
```

**Comment by almasakchabayev** [comment]
Thanks for explanation. Although that would be cool functionality. Can you think of any way to make it work? :) May be change my sorting implementation?

I did not understand the question, but what I have tested are below.
this output
```
{
... {
        posts: {
            count: [
                'dealsById'
                'd5a50b08-8842-472a-b088-76ec4c20de53',
                'posts',
                'sort:createdAt=desc',
                'count'
            ]
        }
    }
}
``` 
I get when I ref `authorsById[{keys:ids}].posts.count` to `authorsById[{keys:ids}].posts["sort:createdAt=desc"].count` (I guess refs are loged like that when they encounter ref instead of a value)

And I get error when I ref `[authorById, id, 'comments']` to `[authorById, id, 'comments', 'sort:createdAt=desc']`

**Comment by michaelbpaulson** [comment]
There are two things wrong here:  
* the first we can change, though we are reluctant, which are inner references.
* The second we cannot ever fix for a very good reason.  Lets say we can follow references that are internal to other references, point 1.  There would still be impossible code to resolve.  To explain this better, lets go over how the cache works.

We would be following the original path, `[authorsById, <id>, comments]` to `[authorById, <id>, comments, sort...]`.  When we hit a _reference_ in the cache, we start back up at the top of the cache and follow that reference through the cache.  So we would _infinitely_ (not technically throw an error after 50 times) follow `[authorsById, <id>, comments]` -> `[authorById, <id>, comments, sort...]`.  In other words, we would evaluate `[authorsById, <id>, comments]` and follow the reference, which would follow the reference, follow the reference, ... etc (you get the idea). 

So even if internal references were allowed the above setup would never work.  Does that help?

**Comment by almasakchabayev** [comment]
Got it, thanks!
