### ISSUE TITLE
router precedence works unexpectedly

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#673]
I have two routes: 
`authorsById[{keys:ids}][{keys:fields}]`
`authorsById[{keys:ids}][{keys:fields}][{keys:fieldProps}]`

For some reason when I request authorsById['1'].name `authorsById[{keys:ids}][{keys:fields}][{keys:fieldProps}]` route takes precedence to `authorsById[{keys:ids}][{keys:fields}]`

I receive pathSet, where `pathSet[3] = [ undefined ]`

Is it expected behaviour? Shouldn't the first route takes precedence, as there are not enough arguments?

**Comment by michaelbpaulson** [comment]
@almasakchabayev I am going to get a test case up for this and make a fix on falcor-router.  The issue has been moved to the aboved linked ticket on the router.

**Comment by almasakchabayev** [comment]
Could you please patch update the falcor version with this fix?
