### ISSUE TITLE
Undefined response when expanding index range on model.get

### ISSUE THREAD

**Issue by khy** [Netflix/falcor#678]
When I do this:
```
model.get(['users', {from: 0, to: 10}, ['firstName', 'lastName']]).then( response => {...
```
`response.json.users` has three user objects (there are only three user objects in the database).

When I subsequently do this:
```
 model.get(['users', {from: 0, to: 20}, ['firstName', 'lastName']]).then( response => {...
```
`response.json.users` is undefined

On the second request, my falcor-express backend receives indexes 11 through 20 and returns an empty array which, as far as I can tell, is what it should do (since there are only three user objects).

My expectation is that on the second request, I would get back the same three user objects from the first request.

Is that expectation incorrect?

(let me know if this belongs in falcor-express)

**Comment by trxcllnt** [comment]
@khy have you seen #590?

**Comment by michaelbpaulson** [comment]
Its like it, but different.  Just has to do with `get`.  I can look at this soon.  Until then I'll be holidaying hard :).  It will be until early January (like the 5th).

**Comment by khy** [comment]
Cool, have fun. No urgency, just experimenting.

**Comment by michaelbpaulson** [comment]
I'll still get to this soon.  I am off on a non falcor tear for a bit.

**Comment by michaelbpaulson** [comment]
@khy should be fixed here: https://github.com/Netflix/falcor/pull/714
