### ISSUE TITLE
falcor The allowed number of retries have been exceeded when plus sign is encountered

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#679]
I have a route for a search box that retrieves tags by text (text comes from the input box). If the user enters + in the input box falcor throws `The allowed number of retries have been exceeded ` before it even enters the route.

Is it expected behaviour? and what shall I do? Currently the only thing I can think of is adding a middleware that would catch that before falcor middleware starts processing the request, however it does not seem as a good solution.

**Comment by almasakchabayev** [comment]
It seems that Falcor Client model does not encode URI components...

**Comment by trxcllnt** [comment]
@almasakchabayev are you using [falcor-http-datasource](https://github.com/Netflix/falcor-http-datasource)? If so, could you check what's happening when it [builds](https://github.com/Netflix/falcor-http-datasource/blob/master/src/buildQueryObject.js#L16) the query string?

**Comment by almasakchabayev** [comment]
@trxcllnt I receive following requests on the server:
```
 GET /model.json?paths=%5B%5B%22tagsByText%22,%22+%22,%7B%22from%22:0,%22to%22:40%7D,%5B%22id%22,%22text%22%5D%5D%5D&method=get 304 18.792 ms - -

info: GET /model.json?paths=%5B%5B%22tagsByText%22,%22+%22,%7B%22from%22:0,%22to%22:40%7D,%5B%22id%22,%22text%22%5D%5D%5D&method=get 304 7.212 ms - -

info: GET /model.json?paths=%5B%5B%22tagsByText%22,%22+%22,%7B%22from%22:0,%22to%22:40%7D,%5B%22id%22,%22text%22%5D%5D%5D&method=get 304 3.598 ms - -

info: GET /model.json?paths=%5B%5B%22tagsByText%22,%22+%22,%7B%22from%22:0,%22to%22:40%7D,%5B%22id%22,%22text%22%5D%5D%5D&method=get 304 7.451 ms - -

info: GET /model.json?paths=%5B%5B%22tagsByText%22,%22+%22,%7B%22from%22:0,%22to%22:40%7D,%5B%22id%22,%22text%22%5D%5D%5D&method=get 304 10.984 ms - -

info: GET /model.json?paths=%5B%5B%22tagsByText%22,%22+%22,%7B%22from%22:0,%22to%22:40%7D,%5B%22id%22,%22text%22%5D%5D%5D&method=get 304 7.011 ms - -

info: GET /model.json?paths=%5B%5B%22tagsByText%22,%22+%22,%7B%22from%22:0,%22to%22:40%7D,%5B%22id%22,%22text%22%5D%5D%5D&method=get 304 3.018 ms - -

info: GET /model.json?paths=%5B%5B%22tagsByText%22,%22+%22,%7B%22from%22:0,%22to%22:40%7D,%5B%22id%22,%22text%22%5D%5D%5D&method=get 304 5.148 ms - -

info: GET /model.json?paths=%5B%5B%22tagsByText%22,%22+%22,%7B%22from%22:0,%22to%22:40%7D,%5B%22id%22,%22text%22%5D%5D%5D&method=get 304 3.290 ms - -
```

**Comment by trxcllnt** [comment]
> @almasakchabayev Or do you want me to put a console log inside the falcor-http-datasource?

This is what I was referring to, yes, since it's using `encodeURIComponent` (which should convert both plus signs and commas). I just tried encoding one of your paths in my Chrome console and seems like its working fine:
```es6
> encodeURIComponent(JSON.stringify([["tagsByText","+",{"from":0,"to":40},["id","text"]]]));
< "%5B%5B%22tagsByText%22%2C%22%2B%22%2C%7B%22from%22%3A0%2C%22to%22%3A40%7D%2C%5B%22id%22%2C%22text%22%5D%5D%5D"
```

**Comment by almasakchabayev** [comment]
@trxclint I was using version 0.1.2 which is the default version installed by npm. There was no encodeURIComponent in buildQueryString.js. When installing straight from git everything works as expected

**Comment by michaelbpaulson** [comment]
Moving issue to Netflix/falcor-http-datasource
