### ISSUE TITLE
Simpler syntax for multiple-PathSets requests

### ISSUE THREAD

**Issue by ewinslow** [Netflix/falcor#684]
In a real app it's easy to get into a situation where you want to request data that doesn't fit neatly into one pathset syntax, so you end up specifying multiple pathsets. This is especially true for ranges, since you often want the length as well as some of the properties from items in the range:

```
model.get(
  ['videos', 'length'],
  ['videos', {from:0, to:9}, ['name', 'rating']],
  ['headlines', 'length'],
  ['headlines', {from:0, to:2}, ['title', 'releasedAt']]
);
```

It would be the bees' knees if there were a syntax that allowed you to specify something that looks more like the shape if what you're anticipating...

```
model.get({
  videos: {
    "0..9": {
      name: "",
      rating: 1,
    },
    length: 1,
  },
  headlines: {
    "0..2": {
      title: "",
      releasedAt: "",
    },
    length: 1,
  }
});
```

Of course, this won't work as-is because the 0..x syntax ambiguous. Is it a range or a string key?

My thought is that Falcor could just assume it's a key by default and provide a way to specify if it's actually a range:

```
model.get({
  videos: {
    "0..9": {
      $type: 'range',
      name: "",
      rating: 1,
    },
    length: 1,
  },
  headlines: {
    "0..2": {
      $type: 'range',
      title: "",
      releasedAt: "",
    },
    length: 1,
  },
});
```

WDYT?

**Comment by nbostrom** [comment]
Here's a something that kinda does what you're asking for: https://www.npmjs.com/package/falcor-graph-syntax

**Comment by michaelbpaulson** [comment]
We have talked about this.  For now we are going to avoid any further syntax.  In fact, we are removing path syntax from the core and providing an es6 template string library.  The only reasons why I don't like this is the same reason why I don't like the path syntax.

1.  It slows things down.  something has to parse every key looking for a specific setup.
2.  The switch case problem.  This works for the moment, but then someone wants keys inside keys of a dictionary:

```javascript
model.get({
    '["key1", "key2"]': { ... you get the idea ... }
});
```

The _simple_ dsl you are suggesting would get inevitably more complicated.

3. Its hard to programmatically create.  

```javascript
var range = {};
range.from = some_calc();
range.to = some_calc();

// Sets the 2nd element to the range in the request array.
query[1] = range;
```

vs

```javascript

... above is json tree building stuff ...
var from = some_calc();
var to = some_calc();
var key = from + '..' + to;

// Because we are generating this based on values, we have to create the tree recursively
// which is no fun to debug.
nextJSON = currentJSON[key] = {};
... below is more json building ...
```

It is true that more information can be described as a tree than a set of arrays that represent the tree.  But for now we will be supporting path syntax (only for the near term as I am eager to destroy) and array syntax (best for performance).

**Comment by ewinslow** [comment]
Thanks for the update! Bummed about the conclusion, but I suppose it's easy enough for me to build a library that parses my own special syntax into the canonical array of arrays format. Better for Falcor to be as barebones as possible!
