### ISSUE TITLE
sometimes falcor does not return data for all paths requested

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#698]
I have a bug that is difficult to reproduce, as it is not consistent.

When I request
```
model.get(
			['featuredDeals',{from:0,to:9},'tags','sort:createdAt=desc', 'edges', {from: 0, to: 6}, ['id', 'text']],
			['featuredDeals',{from:0,to:9}, ['title','conditions','id','image','discount']],
			['featuredDeals',{from:0,to:9},'business',['name','image']],
			['featuredDeals',{from:0,to:9},'likes','sort:createdAt=desc','count'],
			['featuredDeals',{from:0,to:9},'likedByUser', '{{me}}']
)
```

Most of the time the output is good. However SOMETIMES there are no tags in response, which means the first path was ignored.

I am not sure what might cause this problem. Also I cannot reproduce this bug. It happens too rarely

**Comment by michaelbpaulson** [comment]
I have not seen this before.  What would be good is when this does happen dump the cache (`getCache`) and save that out somewhere so that we can take a look at it together.  At this point, my guess is as good (or worse) as yours.

**Comment by almasakchabayev** [comment]
@michaelbpaulson Cache is too big to paste here, not sure if it is a good idea, but I have not put expiration date on cache, what would be recommended value for that?

You can find cache dump here: https://github.com/almasakchabayev/falcor-cache-results/blob/master/cache-dump

I am sorry for it being so big, but actually right in the beginning of the file you can see that tagsById are inconsistent starting from index 13 and for some reason dealsByTags (line 283) stop refing from 406... If you can take a look at it would be great.

**Comment by trxcllnt** [comment]
@almasakchabayev are you using a `falcor-router` as the data source? if so, can you ensure the router is always returning references for each `tagsById[id]`? @michaelbpaulson it looks like cache has merged in the materialized response from a router when it encounters missing paths.

**Comment by almasakchabayev** [comment]
I use falcor-router on server. In my routes I always ref tagsById. Do I need to ref the paths where no data is found, i.e. where empty atom is returned? 

Also wanted to mention that I have another falcor model on server to cache db results with which client-router communicates. What client router does is simply forward all request to server model and when  json is received it transforms it into pathValues using toPathValues function: https://github.com/almasakchabayev/falcor-to-path-values/blob/master/src/toPathValues.js

in toPathValues I did not consider that paths that do not match will return an atom so it is probably my fault. I was just struggling to understand what happens with toPathValues from https://github.com/Netflix/falcor/blob/ee13637f673a3ade8ca08fc2527afcccf1c6f33f/lib/response/ModelResponse.js
Could you may be guide me on how to reimplement this properly?

**Comment by michaelbpaulson** [comment]
You can technically post process a JSON response from a model to create pathValues.

```javascript
function toPathValues(json, paths) {
    var pathValues = paths.
        reduce((pVs, path) => {
            pVs.push({
                // Any short circuited values will not work here.
                path: path,

                // Takes the json and keeps decending until it hits missing
                value: path.reduce((jsonOrValue, key) => {
                    if (!jsonOrValue) {
                        return undefined;
                    }
                    return jsonOrValue[key];
                }, json);
        }, []).

        // there must be a value
        filter(x => x && x.value);
}
```

This is not a complete function as it does not consider a lot of edge cases, but it is relatively complete.  The edge cases are plentiful and the full code is plentiful as well :)

**Comment by almasakchabayev** [comment]
@michaelbpaulson Thanks for your suggestion. I noticed in your function you pass paths, I assume it is somehow extracted from the pathSet, I could not find a function for it in falcor-path-utils, could you may be point me at it. I can implement it myself, just did not want to write it if it already exists

**Comment by almasakchabayev** [comment]
@michaelbpaulson I have just realized that falcor-router has cache of pathValues for each route (not documented). So I do not really need server model route to cache my db results, right? :)

**Comment by michaelbpaulson** [comment]
@almasakchabayev incorrect.  That cache is only alive during the executing request.  If you want longer lived cache and protecting yourself against concurrent requests for the same data I would suggest a server side model.
