### ISSUE TITLE
typo in documentation model example

### ISSUE THREAD

**Issue by andyfenelon** [Netflix/falcor#701]
##### Retrieving Data from a Model - example
http://netflix.github.io/falcor/documentation/model.html

this
`model.getValue("todos[0].customer").then(log); `
should be
`model.getValue("todos[1].customer").then(log); `

var $ref = falcor.Model.ref;
var model = new falcor.Model({cache:{
    todos: [
        $ref('todosById[79]'),
        $ref('todosById[99]')
    ],
    todosById: {
        "99": {
            name: 'deliver pizza',
            done: false,
            priority: 4,
            customer: {
                $type: 'atom',
                value: {
                    name: 'Jim Hobart',
                    address: '123 pacifica ave., CA, US'
                },
                // this customer object expires in 30 minutes.
                $expires: -30 * 60 * 1000
            },
            prerequisites: [$ref('todosById[79]')]      
        },
        "79": {
            $type: 'error',
            value: 'error retrieving todo from database.'
        }
    }
}});

**Comment by michaelbpaulson** [comment]
If typos are found, feel free to submit a PR.

**Comment by jhusain** [comment]
Was in docs already so I fixed it. Thanks for the report.
