### ISSUE TITLE
Empty array on call route causes error on browser.

### ISSUE THREAD

**Issue by delaneyj** [Netflix/falcor#711]
Specifically I have a Router route that at the moment will `return []`;  This causes a `Unhandled promise rejection TypeError: Cannot read property 'error' of null` error on the client.  However if I change to `return [{path:['ack'],value:true}];` the error no longer happens.  It seems like a hack given even though I have no need for the response (right now) there is network traffic happening.  I would think on an empty array there is no async response or an empty response, not an error..

Currently the situation is happening because my implementation of the call route is incomplete but for the sake of argument you have a call of `sendEmail` while it might want to send back a 'Your email has been sent' there are situations where that is not the case.  Is this *by design* or a bug?.

**Comment by jhusain** [comment]
This is a bug. Should be valid to return nothing.

**Comment by michaelbpaulson** [comment]
So I agree it should be valid to return nothing.  Not sure about this empty array :)  (as thats not nothing).  BUT!!! With the code that is in falcor-router, I cannot tell a difference between and empty array and undefined (output has to flatMapped, which means that an empty array and undefined get filtered out).

But I am going to move this ticket to [falcor-router](https://www.github.com/Netflix/falcor-router)

**Comment by delaneyj** [comment]
Already fix and closed on the router side, sorry I forgot to put the issue there.  Thanks for the fast response!
