### ISSUE TITLE
Clarification in the docs regarding DataSource.call

### ISSUE THREAD

**Issue by delaneyj** [Netflix/falcor#712]
There are some details about DataSource.call that I don't seem to grok and hope that its explained in the docs and just missed it.

1.  The second parameter is `args` and takes a `Array.<Object>`, what's the reasoning behind this?  It seems like an plain `Object` makes more sense as currently you send message such as 
`[{key:'key',value:'value'},{key2:'key2',value2:'value2}]` instead of something lik `{key:value,key2:value2}`.  Sure I'm just missing a use case that a simple `Object` doesn't fulfill.
2.  The `refSuffixes` and `thisPaths` don't have a lot of documentation related to them.  They appear to be client get requests that happen in addition to any paths returned by the call's actions.  Are these parameters that have to be handled in the back-ends handler or are they merged into the `Array.<Path>` that the handler will return?  This might be a more of a falcor-router question.

**Comment by michaelbpaulson** [comment]
Thanks @delaneyj for the question.  We are working very hard on the docs to make them great, and this clearly is an area here we need help.

1.  Why an array vs option bag for the `args` argument to the call function?
  * The answer is simple.  We wanted to mock the `apply` function in javascript.  This understanding will help answer question 2 also.  You are right.  If you just wanted to pass in an option bag, it seems rather odd to use an array, but if you just want to bass in an Id, it is odd to have to create an object just to do that.

2.  What the falcor are `refSuffixes` and `thisPaths` and who handles them?  
  * Who handles them? Right now the router always handles them through a get request, but `call` gets a chance to fulfill them.  I could be smarter [here](https://github.com/Netflix/falcor-router/blob/master/src/run/call/runCallAction.js#L35) and use argument count to determine if I need to handle the refPaths / thisPaths in the router or if call does.  
  * So what are `refSuffixes` and `thisPaths`?
    * `refSuffixes` These are concat'd to the end of any `ref` coming out of a call function and a `get` is executed on that.

```javascript
{
    route: 'call.function',
    call: (callPath, args) => {
        return [{
            path: ['a', 'b'],
            value: ref(['c', 'd'])
        }, {
            path: ['my', 'next'. 'ref'],
            value: ref(['netflix', 'chill'])
        }];
    }
}

// Somewhere on a client far far away
model.call(['call', 'function'], [], [['ref', 'suffix']]).subscribe(...);

```

The router would execute the `call` function then do a follow up get for the following paths:

```javascript
this.get([
    ['c', 'd', 'ref', 'suffix'],
    ['netflix', 'chill', 'ref', 'suffix']
]);
```

    * What are `thisPaths`?  They are paths that are concat'd to the `this` path of the call function.  In the previous example, if the following query changed to include `thisPaths` the output would look like:

```javascript 
// Somewhere on a client far far away
model.call(['call', 'function'], [], [['ref', 'suffix']], [['path', 'to', 'content']]).subscribe(...);
```

follow up get request looking like
```javascript
this.get([
    // From the refPaths
    ['c', 'd', 'ref', 'suffix'],
    ['netflix', 'chill', 'ref', 'suffix'],

    // From the thisPaths, which is callPath.slice(0, callPath.length - 1).concat(thisPaths);
    // notice that 'function' is missing from callPath since we slice off the last element of the callPath.
    ['call', 'path', 'to', 'content']
]);
```

I hope that helps!  I am going to close down the question, but if you have follow ups, please feel free to re-open and ask away.

**Comment by delaneyj** [comment]
Thanks so much for this @michaelbpaulson, been trying to absorb it before asking more questions.  Can't reopen this issue but ...

1. The API is probably pretty set so that's fine but for the ids example `{ids:[1,2,3,4,5]}` seems like a lot less cruft than the `{key:'key',value:'value'},{key2:'key2',value2:'value2}` example given before when your options get detailed.  Either way can workaround to look like the other but in my case I'm mostly likely going to have to just wrap my arguments in an array.  Its probably best to give reasoning in the docs for clarification beyond this issue tracker.

2. Can you give an example where the `refSuffixes` && `thisPaths` **should** by handled by a `call`?  It seems that the `call` & `get` handling are being complected.  I totally get that you can batch the call with a get in a single response but don't understand why router's call handler should know at all about `refSuffixes` && `thisPaths`.  I do understand why the client side has those optional arguments though from an optimization context.

**Comment by michaelbpaulson** [comment]
I'll address in order:

1. The api is set, but perhaps you have a misconception of what I was trying to say to you.  Lets take your Id example:

```javascript

new Router([{
    route: 'super.cool.call',
    call: function(callPath, args) {
        .. does something with ids ..
    }
}]);
```

Now you are suggesting `{ids: [...]}`, but what I am suggesting is **not** `[{key:'key',value:'value'},{key2:'key2',value2:'value2}]` but `[...]`.  There is no need to pass in the object of ids instead, just pass in the Ids.  You should think of call like a javascript function.  If I were to write a function that would do stuff based on Ids, I would just pass in the varags of Ids.  You can think of `args` like a list of arguments into said function.

2.  This is a simple answer.  Its where eventual consistency is in place.  If you set the value `5` into an eventually consistent database, and then immediately read, you may get the old value instead of the new value 5.  So having call be able to handle all subsequent data requests is great in that case, else, just let the router handle it for you.

**Comment by delaneyj** [comment]
Both of those answers make sense and should be clarifications in the docs.  

1. I understood the use case of but as soon as you add something more info to the args it seems like it gets unwieldy.  Say you have you ids `[1,2,3,4]` then need `metadata`, do you add to the beginning; to the end?  If you have different kind of ids in a single call (Upload these files and share with these people) the apply doesn't seem to be the right metaphor.  Spread operator helps a lot in these situations but doesn't seem as explicit.

**Comment by michaelbpaulson** [comment]
@delaneyj Its no different than if you are writing a function with the same requirements.
If I were to write a function with the same requirements...

```javascript
// example function
function exampleFunction(ids, metadata) { ... }

// example call
model.call([...], [ids, metadata]).subscribe(...);
```

And if you want to combine, you can:

```javascript
// example function
function exampleFunction(data) { ... }
var data = {
    ids: [...],
    someField1: ...,
    someField2: ...
};

exampleFunction(data);

// example call with the same signature.
model.call([...], [data]).subscribe(...);
```

I hope I am not talking past you.  But do you see what I mean.  Its just a list of arguments as if you were passing them into a function.  So if you were to ask, what about different Ids with different metadata.  Then I would ask "how would you write a function signature to accept that same requirement in JS?  Then thats your arg list."

**Comment by timkindberg** [comment]
You should add your [refPath and thisPath examples](https://github.com/Netflix/falcor/issues/712#issuecomment-173225945) to the docs. I had NO idea what the hell those things were until I read this. Now I'm like "ah ha, 'ref' paths and 'this' paths, I get it!"

**Comment by michaelbpaulson** [comment]
@jhusain

**Comment by drFabio** [comment]
Finally understood it.
But @michaelbpaulson  on your example that the suffixes were added:

>  // From the refPaths
    ['c', 'd', 'ref', 'suffix'],
    ['netflix', 'chill', 'ref', 'suffix'],

They were added to all refs what would happen if "c,d" and "netflix,chill" did not share the same path? for example if I needed a differend suffix to netfix and a diffeend one to c, d ?
