### ISSUE TITLE
Add a gitter channel

### ISSUE THREAD

**Issue by timkindberg** [Netflix/falcor#718]
I'd like to be able to chat to other people using and trying to use falcor

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by ntilwalli** [comment]
:+1:

**Comment by trxcllnt** [comment]
It's not a priority for the Falcor team, but I've started one for my fork: [![Gitter](https://badges.gitter.im/trxcllnt/falcor.svg)](https://gitter.im/trxcllnt/falcor?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by timkindberg** [comment]
Hmmm... it's not all that difficult. Effort (small) for payoff (community/support) is worth it. But I totally get priorities :) They could even just add your gitter badge for now to make it suuuuper easy.

**Comment by chrisvariety** [comment]
We're not just talking about adding a button here. Staffing a chat room to continuously answer questions in near real-time is a lot of work, y'all.

**Comment by timkindberg** [comment]
My project has a gitter and I don't staff it. That is not a requirement by any means. This is really a very straight forward request that requires little effort but gives you a dedicated place for falcor users to support each other and build community.

**Comment by trxcllnt** [comment]
We had one when it was a private repo, but something with Gitter broke when we made it public. I don't have admin privileges anymore so I can't investigate why it stopped working. You're free to join mine and I'll be as active as my workload allows.

**Comment by timkindberg** [comment]
Yours works just fine. I wouldn't necessarily say you guys need to police it. Just casual checking in is good. We can close this I'd say.
