### ISSUE TITLE
Key going from string to number to string before sending request

### ISSUE THREAD

**Issue by enderv** [Netflix/falcor#720]
I might very well be doing this wrong but according to the docs

> A part of a Path that can be any JSON value type. All types are coerced to string, except null. This makes the number 1 and the string "1" equivalent.

The route is setup like so

`route: "item[{keys:ids}]['name']"`

And the get I am doing

    model.get(['item',"16140997201362921294", 'name'])
        .then(data => {
            console.log('fetching item');
            console.log(data);
          })
        .catch(error =>{
          console.log(error);
        })

However when I log the requests server side they are listed as 
`/model.json?paths=[[%22item%22,16140997201362921000,%22name%22]]&method=get`

Showing the ids field having been changed from string to a number and then back again.

**Comment by trxcllnt** [comment]
@enderv we coerce to integers [during path collapsing](https://github.com/Netflix/falcor-path-utils/blob/master/lib/toPaths.js#L67) so we can collapse contiguous ranges ([0, 1, 2, 3], etc.) into `{from, to}` keys. Can you verify that's what's happening here?

**Comment by enderv** [comment]
Yeah thats the spot. Just followed it down and its passing the isNumber check so the rounded number value is being added to the keys array.

Is that as intended or could another condition be added to isNumber to check the string length as well?

**Comment by chrisvariety** [comment]
FYI same issue as https://github.com/Netflix/falcor/issues/704#issuecomment-173440152

**Comment by enderv** [comment]
Oops. Thanks @chrisvariety I'll close this one out as a dupe then.
