### ISSUE TITLE
get(query).subscribe not working as expected.

### ISSUE THREAD

**Issue by delaneyj** [Netflix/falcor#723]
I have a situation where there is a two lists of games in falcor and a call where one is getting added to another.  For simplicity sake I invalidate both list in the cache for testing.  While causing extra network calls for now this works.  However if I setup a similar situation within a React component using subscriptions the invalidations don't cause a retriggering of the data callback.

```jsx
...
      componentDidMount() {
      this.falcorSubscription = falcorModel.get(`games.open[0..10]['id','title']`).subscribe(data=> {
        debugger;
        if (!data.json) debugger;
        this.setState({
          falcorQuery: data.json
        })
      });
    }

      componentWillUnmount() {
        this.falcorSubscription.dispose();
      }
...
```

I know the cache has been updated as other component are using the data.  My assumption was: whatever query you gave a `get` would trigger an subscribe callback if it contained stale data.  If this is not the case can someone explain how subscribe() is intend to be used?  Thanks!

**Comment by trxcllnt** [comment]
@delaneyj `subscribe` doesn't establish a listener, it just invokes the lazy `get` operation. For more information, check out the [RxJS docs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/readme.md).

**Comment by delaneyj** [comment]
@trxcllnt in the case of `call`/`get`/`set` it appears there will be one and only one `onNext` before `onComplete`.  `forEach` seems a little misleading when its only a signal value being returned.  Thanks for the clarification.

**Comment by michaelbpaulson** [comment]
@delaneyj you can have more than one onNext.  If you have 1/2 of the request in your cache and when you subscribe you do it this way, you will get 2 on nexts.  The first one being whats in the cache, the second being the complete request.

```javascript
model.
    get(pathSet).
    progressively().
    subscribe(...);
```
