### ISSUE TITLE
Invalid ranges like {from:1, to: 0} throw weird errors

### ISSUE THREAD

**Issue by mik01aj** [Netflix/falcor#725]
When I try to use a range like this in the Falcor client, I get this error:

![image](https://cloud.githubusercontent.com/assets/3027415/12816246/877fe7e0-cb4b-11e5-9d9c-eb13692dfeab.png)

(the `null` in error message is misleading - actually it's `undefined` when you check it)

This is also the relevant part from the result I got from my Falcor server (the API response, not materialized JSON):

![image](https://cloud.githubusercontent.com/assets/3027415/12816319/fd11e9b8-cb4b-11e5-9fe3-9432c18f6521.png)

I understand that the range is obviously invalid, but in this case Falcor should either:
a) resolve the range to an empty list of keys
b) throw a meaningful error **before** sending the request

---

Btw, I noticed that using an empty list in a request also throws the same error. So maybe there's one more bug a level deeper. (In my understanding, when I ask Falcor client for `['foo', [], 'bar']` it shouldn't send a request at all).

**Comment by michaelbpaulson** [comment]
@mik01aj You are correct.  This bug is naughty.  I'll have to do some investigating about this and see what I can come up with.

**Comment by michaelbpaulson** [comment]
@mik01aj I cannot repro.  Here is my unit test and I cannot repro.

```javascript
var onGet = sinon.spy();
var model = new Model({
    cache: {
        a: Model.ref(['b']),
        b: {
            0: Model.atom('hello')
        }
    },
    source: {
        get: onGet
    }
});

var modelGet = model.get(['a', {to:0, from:1}]);
var onNext = sinon.spy();
toObservable(modelGet).
    doAction(onNext, noOp, function() {
        expect(onGet.callCount).to.equals(0);
        expect(onNext.callCount).to.equals(0);
    }).
    subscribe(noOp, done, done);
```

**Comment by mik01aj** [comment]
Thanks. :+1:
