### ISSUE TITLE
Web worker example doesn't work

### ISSUE THREAD

**Issue by adammw** [Netflix/falcor#727]
Using https://github.com/Netflix/falcor/blob/master/examples/datasource/webWorkerSource.js as an example against latest master, I get the error:
`ERRORS: {"message":"An exception was thrown when making a request."}`

Which can be traced back to the lack of a falcor.Observable class.

Could the example be updated or some pointers on how to achieve a similar result?
/cc @michaelbpaulson

**Comment by michaelbpaulson** [comment]
@adammw Yes, you could always replace it with an Rx.Observable (npm i rx).  This code is old.  Its where we had our own small rx library, which was a long time ago.  

So replace `falcor.Observable.create(...);` with `Rx.Observable.create(...);`.  If you get the example working again, I would be greatly pleased to merge in a PR :)

**Comment by jontewks** [comment]
Hey @michaelbpaulson, I was looking into this example and came across this and figured a good way to understand it would be to fix it! So I have opened up #733. Thanks!
