### ISSUE TITLE
How to find the path you want in a list of pathValues ?

### ISSUE THREAD

**Issue by Bretto** [Netflix/falcor#729]
I am getting a live feed of pathValues via sockets. I then manually set the model. Every thing is working as expected, the issue is sometime I need to find a particular path in the set and apply some transform before setting the model. Is there a Util in Falcor to find a path based on "something" ?

**Comment by michaelbpaulson** [comment]
I think I see what you are saying.  Are you saying you wish to apply the Router's matching capabilities for path matching?

I assume you mean something like: "I want to match ['videos', NUMBERS, 'title']" Correct?

If that is the case, there is nothing, currently, that falcor can do this, that is not to say its not possible to create one.

**Comment by Bretto** [comment]
Yes currently I am doing something like this atm:
```
let contentPath = _.find(pathValues, (o)=>{
            return o.path[2] === 'content';
        });
namePath.value = TntUtils.tansform(contentPath.value);
```
I was looking for something a little bit more elegant and polyvalent.

**Comment by michaelbpaulson** [comment]
@Bretto we may be breaking out, at some point, the path matching process of the router into its own library.  But that is far, potentially never, on the horizon.  
But writing a small utility that is _not_ performance minded first should be easy.  It'll literally be this.

```javascript
var registeredPaths = [];

// For simplicity I am going to ignore PathSets.  Meaning all paths are paths of 1 
// i.e: ['videos', 1, 'title']
// and not matching the following ['videos', [0, 1], 'title'] 
// though not hard, just annoying to do in github editor.
var INTEGERS = "__ints__";
var KEYS = "__keys__";

function matcher(path, fn) {
    registeredPaths.push([path, fn]);
}

// takes in the path value to alter
function executeMatchers(pathValue) {
    var handler = getRegisteredPathHandler(pathValue.path);
    if (handler) {
        pathValue.value = handler(pathValue);
    }
    return pathValue;
}

function getRegisteredPathHandler(path) {
    var handler;
    for (var i = 0; i < registeredPaths.length && !handler; i++) {
        if (isMatch(path, registeredPaths[i][0])) {
            handler = registeredPaths[i][1];
        }
    }
}

function isMatch(path, virtualPath) {
    var matched = true;
    for (var i = 0; i < path.length && matched; ++i) {
        // pretend isNumber exists
        var atom = path[i];
        var virtualAtom = virtualPath[i];

        if (virtualAtom === KEYS) {
            continue;
        }

        if (isNumber(atom) && virtualPath[i] === NUMBERS) {
            continue;
        }

        if (atom !== virtualAtom) {
            matched = false;
        }
    }

    return matched;
}
```

Warning: I did not test this code and i programmed it as fast as I could.

**Comment by michaelbpaulson** [comment]
I assume you are happy, and will close down now.
