### ISSUE TITLE
Returning an array as a value causes {"undefined":{"$type":"atom"}} in result

### ISSUE THREAD

**Issue by mik01aj** [Netflix/falcor#732]
Let say my route handler returns this: 

    { path: ['things', thingId, 'linkedTopic'], value: ['topics', 123] }

Maybe you noticed - I forgot to wrap my `value` in `Model.ref`. 

The returned result, when asking for `["things", 629026273, "linkedTopic", "headline"]` is:

    {"jsonGraph":{"things":{"629026273":{"linkedTopic":
        {"undefined":{"$type":"atom"}, "headline":{"$type":"atom"}}
    }}}}

Definitely looks like a bug. :beetle: 

AFAIK returning arrays as results doesn't make any sense in Falcor (unless wrapped in `ref` or `atom`), so I guess you could just throw a meaningful error if there's an array returned as `value`.

**Comment by greim** [comment]
Did you try wrapping the array in `Model.atom` instead of `Model.ref`? Wrapping it in a ref would definitely cause problems.

**Comment by mik01aj** [comment]
@greim, I really meant a reference there. I just wrote `['topics', 123]` instead of `Model.ref(['topics', 123])` by mistake. My code is OK.

But the point was, returning array in place of a value doesn't make any sense (AFAIK), so Falcor should throw an `Error` instead of constructing weird objects with `{"undefined":{"$type":"atom"}}`. I never asked for key `"undefined"`, so why do I get it in result? :beetle:

**Comment by greim** [comment]
I see. I totally misunderstood your question, sorry!

So if a route returns an invalid thing, the whole thing should propagate a meaningful exception that I can catch at the server level, log the error, and return a 500? That makes sense and seems reasonable. Basically it's a programmer error.

**Comment by trxcllnt** [comment]
@mik01aj @greim yes, this looks to be an issue with [falcor-router](https://github.com/Netflix/falcor-router)

**Comment by mik01aj** [comment]
Okay, re-reported as https://github.com/Netflix/falcor-router/issues/173
