### ISSUE TITLE
Falcor-router doesn't follow $ref, and follow only one instead of multiple routes

### ISSUE THREAD

**Issue by przeor** [Netflix/falcor#736]
Hello,

I am new to Falcor, I really love the idea and can't wait to use it on production. We already are working with Falcor in one of our commercial project :-) ... unfortunately I've spent good chunk of my time to solve what's the problem and I couldn't find what am I missing so please give me any hint.

The issue:
<img width="547" alt="screen shot 2016-02-17 at 02 58 04" src="https://cloud.githubusercontent.com/assets/5995/13097559/56de9902-d522-11e5-9585-bc90bf27c263.png">

In that console log (^^) there is a response from the falcor-router. The problem is that I've definied the path for the **productsById** but for some reasons the falcor-router doesn't follow the path on the backend, but unfortunately sends back to the client side an array of **["productsById", 123]**

On the backend it looks as following:
![111111112222](https://cloud.githubusercontent.com/assets/5995/13097623/f13b1dfe-d522-11e5-9d88-e95abfc7234d.jpg)

In a summary: the $ref (red arrows on the screenshot) doesn't follow the route of **route: "productsById[{integers}].name"**. To be more precise, the falcor-router doesn't execute the console.log from the example 
```
        console.log("IS productsById !!!");
        console.log("IS productsById !!!");
```
so it stucks somewhere here for some reason:
```
        return {
          path:["_view", 123, "name"], 
          value: $ref(['productsById', 123])
        };
```
The complete example is available here:
- server.js: https://github.com/przeor/falcor-netflix-shopping-cart-example/blob/master/server.js#L58
- index.html: https://github.com/przeor/falcor-netflix-shopping-cart-example/blob/master/index.html

I've also created a short screencast video of that behaviour: https://www.youtube.com/watch?v=0OoiIZDkRZc&feature=youtu.be

My question to more experienced people in Falcor - WHAT I AM MISSING :-( ? I was really hard looking for answers in documentation/examples. Probably it's something very simple that I am missing, but looking forward to your feedback.

**Comment by trxcllnt** [comment]
@przeor essentially same fix as [this issue](https://github.com/Netflix/falcor-router/issues/172#issuecomment-181814055). Drop ".name" in the definition of your second route, and add "name" to the end of the paths returned by your first route and things should start working. Cheers.

**Comment by przeor** [comment]
thank you @trxcllnt - this is the hotfix: https://github.com/przeor/falcor-netflix-shopping-cart-example/commit/53174ec0fed439a33a4c789da80dd4387673e0cb

In general, I need to get my head around how to build those routes - the curious thing is that other unofficial examples also has the same error as I've done it in my shopping cart example.

Thank you Falcor Team :-)
