### ISSUE TITLE
Returning errors for individual indexes on range query

### ISSUE THREAD

**Issue by jordanh** [Netflix/falcor#739]
This may extend generally to returning errors for any individual id or index, but we've encountered an odd behavior when writing a route handler for range queries.

Here's a snippet of code from our scaffold generator for Falcor, [falcor-saddle](https://github.com/ParabolInc/falcor-saddle):

``` javascript
  return {
    route: routeBasename + routeSuffixRanges,
    async get(pathSet) {
      const responses = [];
      for (const { from, to } of pathSet.indexRanges) {
        const modelObjs = [];
        try {
          modelObjs.push(...await getRangePromise(from, to));
        } catch (err) {
          responses.push(jsonGraph.error(err)); // <-- this error's message: field is blank
        }
        for (let idx = 0; idx < modelObjs.length; idx++) {
          responses.push(
            jsonGraph.pathValue([routeBasename, from + idx],
              jsonGraph.ref([routeByIdBasename, modelIdGetter(modelObjs[idx])])
            )
          );
        }
      }
      return responses;
    }
  };
```

When this route resolves for the range, an error is given at the particular index where an exception was thrown but its `message:` key is empty. Is this expected or should it be propagated?

**Comment by trxcllnt** [comment]
@jordanh it sounds like the error being thrown isn't serializing correctly. My best guess is the Error instance needs to implement `toString` (or `toJSON`) to return its message key.

**Comment by jordanh** [comment]
We'll give it a shot and report back. Thank you @trxcllnt.

cc @jrwells

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

This thread died, so I'm closing.
