### ISSUE TITLE
$expires 0 does not work currently. 

### ISSUE THREAD

**Issue by michaelbpaulson** [Netflix/falcor#749]
$expires 0 does not currently work in the version of falcor.  `get` considers the `$expired:0` to be expired though its part of a single operation.  So get operations have to be extendible to what for expiration they use to do testing of expired items.

**Comment by steveorsomethin** [comment]
Recently mentioned as ongoing pain point for windows team by @mattflix.

**Comment by asyncanup** [comment]
pull requested: https://github.com/Netflix/falcor/pull/905
