### ISSUE TITLE
JSON output doesn't include branch nodes when value is undefined

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#750]
In JSON mode, Falcor does not reify branch nodes that actually exist. If it can't find a value, it doesn't return its branch nodes or any of its ancestors, even if they're known to exist.

In this example we attempt to retrieve a property that doesn't exist in a list, and get nothing back whatsoever instead of the list object with nothing inside.

``` js
var model = new falcor.Model({
  cache: {
    list: {
        name: "Horror",
        length: 0
    }
  }
});

model.get("list[0].propThatDoesNotExist").then(function(response =>
console.log(JSON.stringify(response, null, 2));

// prints
{
  json: {
  }
}

```

The response should be...

``` js
// prints
{
  json: {
    list: {
     0: {
     }
   }
  }
}
```

Note that when returning JSON we want to reify every branch node we know exists. Otherwise we give the impression that nodes do not exist which actually do exist.

**Comment by trxcllnt** [comment]
lol :+1:

**Comment by michaelbpaulson** [comment]
Lol (+1)

**Comment by steveorsomethin** [comment]
https://github.com/Netflix/falcor/pull/855
