### ISSUE TITLE
Support for websockets?

### ISSUE THREAD

**Issue by bitliner** [Netflix/falcor#751]
Is websocket supported at the moment?

If it is not, is it in the roadmap?

Does the structure of this module include a way to easily integrate websocket?

**Comment by jhusain** [comment]
There's no reason you can't implement a data source that uses a web socket today under the hood. However there is one caveat: although the data source returns an observable which allows data to stream back to the client, currently only Observables which stream a single value are supported.  We plan to supports streaming multiple responses back to the Model from the server in an upcoming version. 

One good reason to use a web socket today would be to push data or cache invalidations. You can do  this today by just listening to the web socket for notifications and then modify the Model cache  using set and invalidate.

**Comment by jhusain** [comment]
To be clear, you can multiplex concurrent Data source operations over the web socket, but each Data source operation can only stream back a single response. Given this limitation, the  main benefit of websockets over HTTP/2 is the ability to push cache invalidations and data into the Model cache. Once again this is done manually, by simply invoking model.withoutDataSource().set(...) and model.invalidate().

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

Considering this answered and closing. @jhusain, please feel free to comment if anything has changed around this.
