### ISSUE TITLE
Falcor 0.1.16 on NPM broken badly

### ISSUE THREAD

**Issue by andyrj** [Netflix/falcor#752]
Somehow the push to npm for version 0.1.16 has a ton of non-ascii characters sprinkled throughout the code base, which causes it to throw: "Uncaught SyntaxError: Unexpected token ILLEGAL" when run in browser.

version 0.1.15 on npm doesn't have these strange symbols and still works in my build, is this a known change or some kind of corrupted build that was pushed to npm?

**Comment by jhusain** [comment]
Which browser are you using? Unicode characters are  valid in JS

**Comment by andyrj** [comment]
Google Chrome 48.0

**Comment by jhusain** [comment]
One more question: what Web server are using? Are you loading  off the filesystem or serving with a Web server?

**Comment by andyrj** [comment]
that is with the latest version of Express setup with the middle ware specified in the falcor documentation.

**Comment by jhusain** [comment]
What is the content type that the Web server is serving? The Web server should be serving the content type as Unicode.

**Comment by sdesai** [comment]
Unrelated to the actual encoding thread you're pursuing, but 0.1.16 seems like it was published by mistake. From a cursory glance it looks like it was published from master by mistake (it has the newer deref, which accepts a boundJSONArg, it has the unicode prefix etc). I'll try and get a 0.1.17 out with the latest on 0.x today.

**Comment by yorzi** [comment]
@sdesai are you going to wrap up the 0.1.17 and publish the fix soon?

**Comment by sdesai** [comment]
It should be out there now
