### ISSUE TITLE
[Documentation] an example of the .call is not clear 

### ISSUE THREAD

**Issue by przeor** [Netflix/falcor#753]
Hello,

While I am working on my project, I very often check the documentation - thanks all for your hard work!

One of the confusion for me is call example in the documentation as following:
<img width="437" alt="screen shot 2016-03-11 at 08 10 21" src="https://cloud.githubusercontent.com/assets/5995/13695646/fbd021ba-e760-11e5-91ea-b00877c99aac.png">
at https://netflix.github.io/falcor/documentation/model.html

In general, how I can make a call on DataSource? 

I already made my first working call on my example project: https://github.com/przeor/falcor-netflix-shopping-cart-example

...  and as far as I know, it HAS to use falcor-router to be useful. 

WHAT IS THE POINT OF GIVING an example of .call like the one above? What is a point of that example?

I can improve it in doc, but I want to understand first... Maybe I am missing something in my process for that use case of .call+DataSource?

**Comment by jhusain** [comment]
The point of the Data Source example above is to demonstrate how call is invoked. A Router implements Data Source, and therefore it is possible to invoke a call on a Router the same way.

Here is a example of a call implemented in the router in the DataSource Guide:

~~~js
 var dataSource = new Router([
 {
        route: 'list.push',
        call: function(callPath, args) {

            // retrieving the title id from the reference path:            
            titleId = titleRef.value[1];
            if (parseInt(titleId, 10).toString() !== titleId.toString())
                throw new Error("invalid input");

            return myListService.
                addTitle(titleId).
                then(function(length) {
                    return [
                        {
                            path: ['myList', length - 1],
                            value: titleRef
                        },
                        {
                            path: ['myList', 'length'],
                            value: length
                        }
                    ];
                });
        }
    }
]);
~~~

Can you clarify what you think the gap in the documentation is?  Can you clarify what you think the gap in the documentation is? Are you trying to figure out how to invoke your function on the server?

**Comment by jhusain** [comment]
updated comment above to fix some grammar and typos.

**Comment by przeor** [comment]
Thank you @jhusain, I will ask my question from different perspective to make sure my falcor's domain knowledge:

Is it possible to make a functional "push" call on a DataSoruce by using ***ONLY*** front-end/back-end model?

I know that ***falcor-router*** allows 
:
 ```        
route: 'list.push',
call: function(callPath, args) {
```

... but can be a .call DONE WITHOUT falcor-router? 

(if .call can be useful without falcor-router then, then please show me how from my curiosity standpoint)

**Comment by jhusain** [comment]
You need to build a falcor server to use a Falcor client. To use call you must use a Router. Sounds reasonable to add a link from the DataSource doc to the Router doc. Will do so.

**Comment by przeor** [comment]
exactly @jhusain - when I was starting with Falcor I thought on the beginning that you can add/remove items from client-side Falcor's model without use of any backend side.

My imagination was that I will do whole app on the frontend (with use of .call etc.) - but after few days of working with it, the reality showed me that it's not possible - we need backend to do .call on the Model's properly.

I am closing that thread. Thank you for your time.

**Comment by kevnk** [comment]
@jhusain In your code snippet, where does `titleRef` come from? I'm trying to get a good explanation and example of Falcor's `call` method and this [stackoverflow](http://stackoverflow.com/q/37926068/622287) is as far as I've gotten. 

Thanks for any clarification you may have.

**Comment by greim** [comment]
@kevnk My assumption is that there should be a

```js
var titleRef = args[0];
```

...line in that code sample. The corresponding client-side call would look like:


```js
model.call(['list','push'], [{
  $type: 'ref',
  value: ['itemsById', '12345']
}])
```
