### ISSUE TITLE
How to do not cache jsonGraphError?

### ISSUE THREAD

**Issue by ustccjw** [Netflix/falcor#754]
When i get jsonGraphError object, how to do not cache jsonGraphError object?

**Comment by sdesai** [comment]
You can use the errorSelector to mutate the error object, and add an expiry field before it gets added to cache. Here's an example: http://netflix.github.io/falcor/documentation/model.html#the-errorselector-value

IIRC, I think there's a bug with the "Expire Immediately (as in, don't cache this value)" use case, but you can use a small negative value, for example $expires:-10 to indicate "Expire in 10ms from the time this is put in cache" to work around it. http://netflix.github.io/falcor/doc/global.html#Atom

**Comment by ustccjw** [comment]
@abasiri Maybe i should invalidate it after getValue execute

**Comment by abasiri** [comment]
I believe the message was meant for @sdesai
