### ISSUE TITLE
[good practises] How to retrieve the created object ID (ie. from mongoDB) when doing the .call

### ISSUE THREAD

**Issue by przeor** [Netflix/falcor#755]
Hello,

I've read somewhere that when doing a call, then it's a bad practise to return a created object (with an id)? Have I misunderstand something? (I can't recall the source right now, so I am asking for double-check)

Frontend code:
```
    await falcorModel
    .call(
        ['restaurants', 0, 'menuItems','add'],
        XYZ_DATA,
        ["name"]
        ).
    then((result) => {
    });
```

Then based on the XYZ_DATA, in falcor-router I have:
```
  route: 'restaurants[{integers}].menuItems.add',
  call: (callPath, args) => {
      let NewMenuItemRef = $ref(['menuItemsById', MOCKitemID]);

      // var newProductRef = $ref(['productsById', randomMockedMongoId]);
      let results = [
        {
          path: ['menuItemsById', MOCKitemID],
          value: MOCKitem
        },
        {
          // path: ['restaurants', 0, 'menuItems', index], 
          path: ['restaurants', 0, 'menuItems', 6],
          value: NewMenuItemRef
        }
      ];

      console.log(JSON.stringify(results, null, 5));
      return results;
    }
  },
```

P.S. The example above have MOCKED data (ie. objectID & "6" as a number in an array of ***menuItems***). let's assume that MOCKitemID is an ID created by mongoDB.

QUESTION: what is good practise to return this object (altogether with an ID) so the client-side app can know the ID created by mongoDB while doing the .call on the backend (with use of ***  route: 'restaurants[{integers}].menuItems.add',  call: (callPath, args) => {***) ?

Thanks in advance for an advice :-)

**Comment by jhusain** [comment]
This is the use case for "refPaths" in call. You can specify paths to look up on any JSON Graph references returned from call. That way you can retrieve keys from the newly-created object without knowing its ID.

**Comment by przeor** [comment]
thanks for your time @jhusain ... hmm I've encountered one more problem, let me share  the code:

On client-side I have:
```
  async onAddItemDone(newMenuItem, refMap) {
    let MOCKitem = {"title":"Test title mock","description":"1","type":"MenuItem","description2":"2","description3":"3","allergens":{"type":"Allergens","vegetarian":true,"gluten":true,"egg":true,"dairy":true,"nut":true,"soy":true,"fish":true,"showAllergens":true}};
    newMenuItem = MOCKitem;

    /*
      adding an item with .call on Model
     */
    await falcorModel
    .call(
          ['restaurants', 0, 'menuItems','add'],
          [newMenuItem], 
          [
            "id"  //     refPaths that will be looked up on newly-added menuItems after successful function completion
          ],
          [
            "length"  // thisPaths that will be looked up on list after successful function completion
          ]
        ).
    then((result) => {
    });

    const menuItemsLen = await falcorModel.getValue(
      ['restaurants', 0, 'menuItems', 'length']
    );

    console.info("1) >>> menuItemsLen", menuItemsLen); // it works fine, the thisPaths does it's job

    let allCurrentMenuItems = await falcorModel.get(
      ['restaurants', 0, 'menuItems', {from: 0, to: menuItemsLen-1 }, ['id', 'title', 'description', 'picUrl']]
    );


    // HERE THE PROBLEMS BEGINS that:
    console.info("\n\n\n DEBUG MODEL IS BELOW\n\n\n ");
    /*
      1) Here I can find a new object (as on the screenshot)
     */
    console.info(falcorModel._root.cache);
    console.info("\n\n\n DEBUG MODEL IS ABOVE\n\n\n ");

    console.info("\n\n\n allCurrentMenuItems BELOW \n\n\n ");
    /*
      2) here at allCurrentMenuItems there is still old (not updated list)
     */
    console.info(allCurrentMenuItems);
    console.info("\n\n\n allCurrentMenuItems ABOVE \n\n\n ");
  }
```

# THE PROBLEM:
1) when I lookup the ***console.info(falcorModel._root.cache)***, then I can find the object created on with my ***.call*** function:
<img width="485" alt="screen shot 2016-03-18 at 17 12 53" src="https://cloud.githubusercontent.com/assets/5995/13884228/691d7458-ed2d-11e5-9632-eba27ca1bab4.png">


2) But then I check this ***console.info(allCurrentMenuItems)*** (as in the above's code snippet) then I see old (not updated objects):
<img width="482" alt="screen shot 2016-03-18 at 17 13 09" src="https://cloud.githubusercontent.com/assets/5995/13884188/382ee480-ed2d-11e5-8d2f-3485a39e8b5b.png">



THIS IS MY falcor-router's code:
```
  {
  route: 'restaurants[{integers}].menuItems.add',
  call: (callPath, args) => {
      let NewMenuItemRef = $ref(['menuItemsById', MOCKitemID]);

      // mocking: the INDEX somehow has to be fetched from mongoDB
      MOCKitem.orderNumber = 6;

      let results = [
        {
          path: ['restaurants', 0, 'menuItems', MOCKitem.orderNumber],
          value: NewMenuItemRef
        }
      ];

      console.log(JSON.stringify(results, null, 5));
      return results;
    }
  },
```

P.S. please provide feedback how I can do it more professionally, I will be grateful - as you can check with your experience and help me to improve :-) when I get it, then I will pass this knowledge forward.

**Comment by jhusain** [comment]
Can you let me know if this resolves the issue?

**Comment by przeor** [comment]
Yes - thank you @jhusain. I have managed make this works.
