### ISSUE TITLE
How to expose non-directional relationships in JSON graph?

### ISSUE THREAD

**Issue by greim** [Netflix/falcor#757]
My app has a "connection" entity between two users:

```
GET /connections/:id
<= {
  id: '123',
  user1_id: '234',
  user2_id: '345',
  created_at: '2016-02-12T22:34:42.767Z'
}
```

There's no directionality in the mapping, if that makes sense; user1 and user2 could be switched and it would mean the same thing. For JSON graph I originally thought of this:

```
// IDEA 1
users
`--:id
   `--connection_list
      |--length (integer)
      `--:index (reference into [users, :id])
```

But that won't work because I also want to show how long the users have been connected, and the above doesn't expose the connection object (specifically the `created_at` value). So then I thought of this:

```
// IDEA 2
users
|--:id
|  |--connection_list
|  |  |--length (integer)
|  |  `--:index (reference into [users, :id])
|  `--connections_by_user
|     `--:userId (reference into [connections, :id])
`--connections
   `--:id
      `--created_at (date string)
```

But that's sort of wonky because I'd have to grab the `userId` from Falcor, and use it to construct more paths into Falcor which forces an extra round trip. So then I thought of this:

```
// IDEA 3
users
|--:id
|  `--connection_list
|     |--length (integer)
|     `--:index (reference into [connections, :id])
`--connections
   `--:id
      |--user1 (reference into [users, :id])
      |--user2 (reference into [users, :id])
      `--created_at (date string)
```

Which might work, but I'd have to add some funky client-side logic to figure out whether it's `user1` or `user2` that I'm interested in, since a connection is non-directional and doesn't "know" which user is in context. So then I thought of this:

```
// IDEA 4
users
|--:id
|  `--connection_list
|     |--length (integer)
|     `--:index
|        |--connection (reference into [connections, :id])
|        `--user (reference into [users, :id])
`--connections
   `--:id
      `--created_at (date string)
```

Which as far as I can tell will get me what I need and feels the least bad. But still feels *maybe* kind of weird because it seems to suggest an entity that doesn't actually exist in our data scheme. (i.e. the thing that lives directly under connection_list/:index) Am I missing anything here, and/or is there a better way to do this that I haven't thought of? Thanks.

**Comment by jhusain** [comment]
Idea three is how we model many to many relationships. Any client-side logic you were writing to determine which user you are interested and should be able to be moved to the server in the form of a reference. In other words instead of a reference to user 1, you could have a reference on the connection to "userThatMeetsSomeCondition." Let me know if that makes sense.

**Comment by greim** [comment]
Ah, hadn't thought of that angle, but makes sense. So modifying idea 3 above it might look like this:
```
// IDEA 3 (modified)
users
|--:id
|  `--connection_list
|     |--length (integer)
|     `--:index (reference into [connections, :id])
`--connections
   `--:id
      |--user1 (reference into [users, :id])
      |--user2 (reference into [users, :id])
      |--created_at (date string)
      `--user_connected_from
         `--:id (reference into [users, :id])
```
Struggling to think of a proper name for it but `user_connected_from` is the in-context user and the reference is to the user with the non-matching ID. Let me know if that isn't what you had in mind but that makes sense. Thanks for the response!
