### ISSUE TITLE
Result wrapper should not be mutated in progressive mode

### ISSUE THREAD

**Issue by madcapnmckay** [Netflix/falcor#758]
When in progressive mode the first result we receive for a particular get operation is subsequently mutated when the new results are received. This means that client code cannot easily assert that the results have indeed changed i.e. by doing a === on the previous and current response.

A better approach would be to create a new result wrapper object when new results are received and copy any existing results onto it.

**Comment by jhusain** [comment]
This feature shares the same implementation with the proposed update feature. Update  will accept a previous response and emit a new response, copying nodes by reference into the new message when they haven't changed.

The first step will be to add a version flag to each node in the message that corresponds to the version on the cache node. Then when updating the response we'll compare the response version number against the cache version number.

**Comment by jhusain** [comment]
I'll take this on. I've been looking at the get algorithm closely over the last two weeks.

**Comment by steveorsomethin** [comment]
This was fixed in https://github.com/Netflix/falcor/pull/766
