### ISSUE TITLE
Falcor model - add to headers a token with Bearer after successful login (without reloading the SPA)

### ISSUE THREAD

**Issue by przeor** [Netflix/falcor#762]
Hello,

What is best approach for reloading a model after a user login correctly in case that we want add an JWT Bearer token into any next Falcor's network requests?

LET'S IMAGINE:
1) A user enter's login form's page of our APP
2) A user logs correctly with his username and password
3) A server has responded correctly with the token
4) We save this token into our localStorage.token
**************** AT THIS POINT ANY OTHER requests need to have the token in headers *****
5) A user requests for more data from dashboard etc. that requires valid token

In general, it works me all besides one downside: I need to refersh the page so the code from my ***falcorModel.js*** runs again.

This is my falcorModel.js:
```
const falcor = require('falcor/dist/falcor.browser');
const FalcorDataSource = require('falcor-http-datasource');

let headers;
if(localStorage.token) {
    headers = {
      headers: {
        'Authorization': 'Bearer ' + localStorage.token
      }
    };
}


const model = new falcor.Model({
  source: new FalcorDataSource('/model.json', headers)
});

export default model;
```

In general, my problem is that after I am authenticated with: 
```
  async login(credentials) {
    let loginResult = await falcorModel
      .call(
            ['login'],
            [credentials]
          ).
      then((result) => {
        return loginResult;
      });

    let tokenRes = await falcorModel.getValue('login.token');

    if(tokenRes === "INVALID") {
      // login failed, get error msg
      let errorRes = await falcorModel.getValue('login.error');
      this.setState({error: errorRes});
      return;
    }

    if(tokenRes) {
      this.setState({error: JSON.stringify(tokenRes)});
      localStorage.setItem("token", tokenRes);
      /*
          QUESTION: what to do here to make the Falcor adding the token for any next requests after this successful login?
      */
    } else {
      alert("Fatal login error, please contact an admin");
    }

    return; 
```
... then I need somehow to say to Falcor's model, to add this Bearer token in any next request.

#### Probably someone with more knowledge can give a quick hint, that avoid binding a refresh function to ***window.*** (that probably also won't work as supposed)

I am looking also for feedback how to write this front-end side async login function in a better fashion :-)

**Comment by przeor** [comment]
Just want to tell you that I was checking stackoverflow and this issue: https://github.com/Netflix/falcor/issues/550 and the answers weren't complete, so this is why I've opened this new issue.

Thank you for your understanding.

**Comment by przeor** [comment]
My idea for this problem:

In the falcorModel.js to export a function that returns a model, instead of model itself?

```
const model = new falcor.Model({
  source: new FalcorDataSource('/model.json', headers)
});
```

Is it efficient approach to return a new model each time when using it around the app? Do you have a better idea?

**Comment by joshdmiller** [comment]
We've done something similar extending `HttpDataSource` to use a token from a Flux store (that we use for non-persistent ui state, etc., that syncs with local storage) that we add during the preflight `onBeforeRequest`: https://github.com/StoryShop/app/blob/lists/src/stores/data-source.js#L9-L15.

**Comment by przeor** [comment]
Works with the onBeforeRequest:
```
import falcor from 'falcor';
import FalcorDataSource from 'falcor-http-datasource';

class PublishingAppDataSource extends FalcorDataSource {
  onBeforeRequest ( config ) {
    const token = localStorage.token;
    const username = localStorage.username;
    const role = localStorage.role;

    if (token && username && role) {
      config.headers['token'] = token;
      config.headers['username'] = username;
      config.headers['role'] = role;
    }
  }
}

const model = new falcor.Model({
  source: new PublishingAppDataSource('/model.json')
});

export default model;
```

Similar issue here https://github.com/ekosz/redux-falcor/issues/7 

Closing the issue.
