### ISSUE TITLE
Preflight error using Authentication Token

### ISSUE THREAD

**Issue by farxelemon** [Netflix/falcor#767]
Hey guys! I'm struggling with an error.

I'm developing an AngularJS app and I am using falcor model on the frontend side to communicate with falcor router on the server side. I'm doing get requests with authentication token and works fine. However, when I do a call method to send info and use the auth token on the header, i get this error:

"XMLHttpRequest cannot load http://localhost:9002/model.json. Response for preflight has invalid HTTP status code 500"

If I remove the auth token, the call works fine. Can you help me?

This is how I create the falcor model.

`this.GetFalcorModel = function(authToken) {

```
  var headers = {};
   if(authToken){
       headers.Authorization = "Bearer " + authToken;
   }
   this.model = new falcor.Model({
       source: new falcor.HttpDataSource(configurations.FalcorRouterConfigs.host+':'+configurations.FalcorRouterConfigs.port+ "/model.json",
       {
           headers: headers,
           crossDomain: true
       }
   )});

return this.model;
```

  }`

Cheers!

**Comment by joshdmiller** [comment]
Sounds like your server returned 500 (internal server error) for the
preflight get. Is there an error in your server logs? Or can you see an
error in the "Network" tab of the console?

>

**Comment by farxelemon** [comment]
I don't get any other error.

Actually there is a strange issue. This process doesn't work on chrome, kind of work on Firefox and fully works on IE :/

**Comment by joshdmiller** [comment]
Again, the 500 is not normal. That's the server's way of telling the client there was an uncaught exception. If it works in some browsers and not others, that means there are most likely *two problems*: one on the client introducing an error with the token, and another on the server throwing an error when attempting to process the erroneous token.

Solving the server issue is likely the most direct route. Check the "Network" tab; are you actually getting `200` for all requests, or is one returning `500` as the error claims?

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

I would echo the answer Josh gave, though this thread has obviously died. Closing.
