### ISSUE TITLE
$atom value should be deep-copy when get/getValue return (for immutable)

### ISSUE THREAD

**Issue by ustccjw** [Netflix/falcor#768]
Code as follow, two problems:
1. scenes is a $atom value by `dataModel.getValue(['scene', 'all'])`, modify scenes will affect dataModel. That's normal? why?
2. console.log show: first scenes has modified, why? This one seems `async/console` problem.

```
export const updateScene = async () => {
  const sceneId = await uiModel.getValue(['greeting', 'sceneId'])
  let scenes = await dataModel.getValue(['scene', 'all'])
  console.log(scenes)
  let scene = null
  scenes.every(scene1 => {
    if (sceneId === scene1.symbol) {
      scene = scene1
      scene.role = scene.roles.map(({ roleSign }) => roleSign).join(',')
      return false
    }
    return true
  })
  scenes = await dataModel.getValue(['scene', 'all'])
  console.log(scenes)
  await uiModel.set({
    json: {
      app: {
        modalName: 'scene-setting',
      },
      greeting: {
        scene: $atom(scene),
      },
    },
  })

  return global.reload('greeting: updateScene')
}
```

**Comment by ustccjw** [comment]
@michaelbpaulson can you check it ?

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

Deep-copying atoms of object as a default would be prohibitively expensive on the low-end hardware netflix and falcor run on. If you want to mutate object atoms after receiving them from falcor, you might be better off copying-and-updating, then merging the changed atom back into your json response (which you essentially own and can mutate at will).

Alternatively you could break apart your scene atoms into primitive (non-object) sub-paths and request those, which would also make it perfectly safe to mutate the response falcor gives you.
