### ISSUE TITLE
What does maxSize represent?

### ISSUE THREAD

**Issue by c0** [Netflix/falcor#770]
After reading the docs, I can see that the `maxSize` option for `Model` is a number. But what does it represent?

Is it the total kb? or # items?

---

BTW, I'm glad to open a PR to help update docs after this :D

**Comment by trxcllnt** [comment]
@c0 it's not necessarily KB or item count, but can correlate to either if you like. You can attach a `$size` metadata property to references and atoms that count towards the total cache size. If no size is provided, the default is 50 (except for Arrays or Strings, their length is used instead). So by default, maxSize roughly correlates to item count (itemCount = maxSize / 50), but if you start giving things larger (or smaller) sizes, you can get a bit better control over falcor's memory usage.
