### ISSUE TITLE
Update to use symbol-observable

### ISSUE THREAD

**Issue by benlesh** [Netflix/falcor#776]
FYI, @jhusain ... we're\* going to try to standardize on [symbol-observable](https://www.npmjs.com/package/symbol-observable) as the "small module" of choice to pull in `Symbol.observable`.

/\* "we're" meaning RxJS and others. (Currently, there's a PR in for redux that will use this same module)

**Comment by jcranendonk** [comment]
Use of the `symbol-observable` package was added in the Falcor 1.0 release.
