### ISSUE TITLE
[best practises] falcor-router and update a document in our model

### ISSUE THREAD

**Issue by przeor** [Netflix/falcor#788]
Hello,

Quick question about falcor-router. For example I am updating an object in my mongo's collection with a .call as below:

```
  {
  route: 'articles.update',
  call: async (callPath, args) => 
    {
      let updatedArticle = args[0];
      let articleID = String(updatedArticle._id);
      let article = new Article(updatedArticle);
      article.isNew = false;

      return article.save(function (err, data) {
        if (err) {
          console.info("ERROR", err);
          return err;
        }
      }).then ((res) => {
        return {
          path: ["articlesById", articleID],
          value: updatedArticle
        };
      });
    }
  },
```

... as you can find above, the only thing that I return is that:

```
        return {
          path: ["articlesById", articleID],
          value: updatedArticle
        };
```

My question: is it the only thing, that I need to return in that route in order to inform the falcor's model on front-end that an article with the articleID has been changed? Is it enough to have properly updated $model on the front-end? :-)

Looking forward to your feedback and any improvements suggestions.

Regards,
Kamil

**Comment by eddieajau** [comment]
👍 I'm bumping into the same architectural question. Did you make any progress?

**Comment by joshdmiller** [comment]
If your `articlesById[articleId]` route is not an atom, returning a whole object isn't the way to go because `call` is expected to return an array of path values. You'd probably need to do one of two things:

Invalidate the local version:

```js
return [
  { path: [ 'articlesById', articleId ], $invalidated: true },
];
```

Or return all changed props (anything from the `get` route):

```js
return [
  pathValue( [ 'articlesById', articleId, 'field1' ], article.field1 ),
  pathValue( [ 'articlesById', articleId, 'field2' ], article.field2 ),
  pathValue( [ 'articlesById', articleId, 'field3' ], article.field3 ),
];
```

**Comment by przeor** [comment]
@eddieajau looks like ```return [
  { path: [ 'articlesById', articleId ], $invalidated: true },
];```

**Comment by joshdmiller** [comment]
@przeor Certainly. Invalidating the path will require another round trip to the server when that data is needed, as it is invalidated on the client-side cache. This is desirable in many cases to prevent overfetching, but not in all. Also make sure you get acquainted with the `refPaths` and `thisPaths` when [calling functions](http://netflix.github.io/falcor/documentation/model.html#calling-functions), too.

**Comment by przeor** [comment]
I am not sure what you mean by:
```
Also make sure you get acquainted with the refPaths and thisPaths
```

Could you expand on that @joshdmiller ?

**Comment by joshdmiller** [comment]
They are explained in the docs at the link I sent, but they are the third and fourth arguments to the `call` method and control what data is returned *at the caller's request*. One important goal with falcor is to be able to fetch as little data as needed to accomplish a job, so you can specify on a call what should get returned.

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

Thanks @joshdmiller for the comprehensive answers. Closing.
