### ISSUE TITLE
[falcor-router] difference with version 0.2.12 and 0.3.0 - invalidate stops working after an upgrade

### ISSUE THREAD

**Issue by przeor** [Netflix/falcor#789]
Hello,

I've just noticed that in the  version 0.2.12 of falcor-router it works:

```
  {
  route: 'articles.delete',
  call: (callPath, args) => 
    {
      let toDeleteArticleId = args[0];
      return Article.find({ _id: toDeleteArticleId }).remove((err) => {
        if (err) {
          console.info("ERROR", err);
          return err;
        }
      }).then((res) => {
        return [
          {
            path: ["articlesById", toDeleteArticleId],
            invalidate: true
          }
        ]
      });
    }
  }
```

... so I invalidate properly a deleted document... but after I upgrade to:

```
"falcor-router": "^0.3.0",
```

... it stopped to work. I've tried to find any information the documentation about this, but the only thing is in the model https://netflix.github.io/falcor/documentation/model.html docs, which doesn't provide any information what has changed in new version of falcor-router.

.. generally, the server sends the 500 error and in the response I see:

```
{"throwToNext":true}
```

... after upgrade from ^0.2.12 to ^0.3.0

Is there any up to date documentation how to use all falcor-router's features in the current versions?

Regards,
Kamil

**Comment by m1ch4ls** [comment]
I had the same problem...

use helpers here: https://github.com/Netflix/falcor-json-graph/blob/master/src/index.js

```
return [
  {
     path: ["articlesById", toDeleteArticleId],
     invalidated: true // <-- see here, it has changed to invaldate*d*
  }
]
```

**Comment by steveorsomethin** [comment]
I'm currently performing triage on the falcor issues, and closing/tagging as I go.

+1 @m1ch4ls answer. We'll be doing an upgrade to the docs soon before going to a general release. I'll make a note of this. Thanks!
