### ISSUE TITLE
Where is Falcor 1.x

### ISSUE THREAD

**Issue by jameslaneconkling** [Netflix/falcor#791]
[MIGRATIONS.md](https://github.com/Netflix/falcor/blob/master/MIGRATIONS.md) suggests that 1.x should be available as a dev preview.  However, the version published to master is `0.1.16`, which [this issue](https://github.com/Netflix/falcor/issues/752) seems to suggest is a mistake.  

I did download `0.1.16`, and it is about 1/2 as large, suggesting that it is missing the `rx` dependency, as `1.x` is supposed to.

Is `1.x` published somewhere?

**Comment by sdesai** [comment]
Hey @jameslaneconkling 

1.x isn't published anywhere currently. We were close to getting it out (at least as an RC), but we're not sure we have `deref` quite where we want it (mainly as it pertains to the current need to add internal properties to the JSON payload, to optimize performance) so we wanted to hold back, as opposed to introduce API churn and flush out the story a little more.

What's on master will ultimately be 1.x (with 0.1.16 being the mistakenly published version off master).

**Comment by sdesai** [comment]
Sorry, don't have a definitive date for you, but ideally we'd like to get it out by the end of the year if we can spend some cycles making sure we've got `deref` right over this quarter.

**Comment by maisonetteops** [comment]
Hey netflix/falcor crew, thanks for all of your efforts on this project! Curious if 1.x is on the Roadmap for 2017?

**Comment by edword** [comment]
Hey netflix/falcor crew, thanks for all of your efforts on this project! Curious if 1.x is on the Roadmap for 2017?

**Comment by sdesai** [comment]
It is, but I feel bad to keep promising it. It keeps on getting trumped by other priorities. Our focus currently is on the router [ so you're seeing some movement on that front ].

**Comment by sdesai** [comment]
1.0.0 released (finally). Sorry about the delay, but we've got some more folks available to wrap up some of the tasks we wanted to get 1.0.0 out. Thanks @steveorsomethin.
