### ISSUE TITLE
Server side falcor model

### ISSUE THREAD

**Issue by filipeperdigaosousa** [Netflix/falcor#797]
It is possible to user falcor model from server side applications in Node.js?

Currently I am using falcor-http-datasource and I receive this error: 
[TypeError: global.XMLHttpRequest is not a function]

**Comment by greim** [comment]
Hmm. I've been using falcor-http-datasource for unit tests in node and it's been working fine, I just have to pass it an absolute URL with a protocol and host. In my deps I have:

```js
"falcor-http-datasource": "^0.1.3"
```

Not sure why it would work for me and fail for you, unless there's some difference between our versions?

**Comment by filipeperdigaosousa** [comment]
I'm also trying ot use that package, but I receive the error mentioned above when I make a request.

Do you have some idea about that?

**Comment by greim** [comment]
Could you post the full stack trace of the error, plus your falcor-http-datasource version and your node version?
