### ISSUE TITLE
Is there a strategy for moving items from one list to another?

### ISSUE THREAD

**Issue by eddieajau** [Netflix/falcor#803]
I have a scenario where we have a list of "published" articles, and a list of "draft" articles. So here's  an example of the JSON graph:

``` json
{
  "jsonGraph" : {
    "articles" : {
      "0" : {
        "$type" : "ref",
        "value" : [
          "articlesById",
          1
        ]
      }
    },
    "drafts" : {
      "0" : {
        "$type" : "ref",
        "value" : [
          "articlesById",
          2
        ]
      }
    },
    "articlesById" : {
      "1" : {
        "id" : 1,
        "title" : "Hello world",
        "enabled" : true
      },
      "2" : {
        "id" : 1,
        "title" : "Still drafting",
        "enabled" : false
      }
    }
  }
}
```

Now is a real world scenario the "articles" and the "drafts" lists have many elements. The problem we are encountering is that when we change the "enabled" property on an article, we need to effectively "move" an article from one list to the other.

Our current strategy would be to invalidate the entirety of both lists when we change the "enabled" property (but not, for example, "title"). Is this the best (or perhaps only) way to handle this situation?

Thanks in advance.

**Comment by joshdmiller** [comment]
From my reasoning, the only way to do it is to invalidate the arrays. The article changed, sure, but of relevance here is that the list really *did* change, so an invalidation is "correct".

That said, you needn't invalidate the entire array; if the article at index 17 changed, you only need to invalidate 17 onward because the index positions for 0 through 16 did not change.

**Comment by greim** [comment]
Agreed, list invalidation is the right tool for the job in general, but when you mutate an item, your concern is only to mutate that item. It's an anti-pattern to attempt to also refresh any lists the item may be a member of at the moment.

Instead, let the task of invalidation fall to other parts of the app whose job it is to invalidate things at the proper times. For instance, maybe the lists are invalidated every time the view is reloaded, or there's an explicit refresh button.

It's arguably better architecture (separation of concerns) but also better UX since the list won't flash and/or refresh while the user is operating on it, which can be jarring or confusing.

**Comment by eddieajau** [comment]
Thanks for the advices all.

> Instead, let the task of invalidation fall to other parts of the app whose job it is to invalidate things at the proper times. For instance, maybe the lists are invalidated every time the view is reloaded, or there's an explicit refresh button.

Perhaps, but I think the point of Falcor is to have those invalidations in the response. The app may very well do a few passes over the response, but when it sends it back I should think the intention is to include all actions the client is supposed to do to update the JSON Graph.

> That said, you needn't invalidate the entire array; if the article at index 17 changed, you only need to invalidate 17 onward because the index positions for 0 through 16 did not change.

I don't know that this is practical because depending on when a client made the request, the actual index may change (consider a list sorted most-recent content first).

Is there an easy way to invalidate an entire array without specifying both `from` and `to` in the response from the router? Currently I'm sending `{ from: 0, to: countOfArticles }` but the overhead of counting the articles seems somewhat unnecessary, and possibly inaccurate depending on when the client last got its data.

Thanks in advance.

**Comment by trxcllnt** [comment]
> @eddieajau Is there an easy way to invalidate an entire array without specifying both from and to in the response from the router?

Yes, you should be able to emit `{ path: 'the.list', invalidated: true }` from your route handler to signal the client should invalidate its local copy of the list.

**Comment by eddieajau** [comment]
@trxcllnt thanks I'll try that out.

It doesn't look like `.set` in the router will accept anything but the path you are setting so it looks like pub/sub is the only option to deal with side-effects from the set.

**Comment by trxcllnt** [comment]
@eddieajau ah yes, invalidations can only be returned from the results of a `call` operation. `get` and `set` are idempotent (which enables us to cache their results), so they cannot choose to conditionally invalidate other parts of the cache.

**Comment by eddieajau** [comment]
OK, so basically within my pub/sub framework (Crossbar WAMP fwiw), I'll need to set up a topic listener to do something like:

```typescript
// listen for the 'model.json.invalidate' topic
wampClient.subscribe('model.json.invalidate', (paths: PathSet[]) => {
  paths.forEach((path: PathSet) => this.model.invalidate(path));
});
```

Does that sound about right?

**Comment by nickretallack** [comment]
If you know exactly how the lists should change, you could patch the cache with getCache/setCache instead of invalidating anything.

**Comment by steveorsomethin** [comment]
I'm currently performing triage on the falcor issues, and closing/tagging as I go.

+1 to Paul's answer. Please open another issue if this didn't totally work out for you.
