### ISSUE TITLE
Updating maxSize on a Model

### ISSUE THREAD

**Issue by mike-cook-projects** [Netflix/falcor#808]
We have a scenario where we request properties via paths, but those properties may instruct us to limit the max cache size on a model for memory purposes.  Currently, there is not a way to do this outside of instantiating a new model.

**Comment by sdesai** [comment]
Added a private method (to experiment with internally). If there's broader use case demand, we can evaluate whether it makes sense to support a public method: https://github.com/Netflix/falcor/blob/master/lib/Model.js#L417
