### ISSUE TITLE
falcor.Model.get(pathSets) not handling empty array argument

### ISSUE THREAD

**Issue by emilgoldsmith** [Netflix/falcor#811]
I don't know if it's supposed to, but right now you get a maxRetryExceededError if you accidentally pass an empty array as one of your pathsets to falcor.Model.get, and since the stacktrace is so bad, it took me a while to debug it.

It's probably correct that it should crash the app since it's an invalid path to pass, or maybe it shouldn't because it should be irrelevant, but maybe it could show a different error? Handle it as a special case?

**Comment by hgwood** [comment]
A maxRetryExceededError means the client believes the server has returned a JSONGraph that does not contain the requested value. For example, if the client asks for `a.b.c` and the server returns `{jsonGraph: {a: {c: "value"}}}` then you will get that error.

I think Falcor considers the empty path as a valid path requesting the root of the graph. For example, `model.get([])` could result in this graph: `{jsonGraph: "hello world"}`. It might be that what you are seeing is the normal behavior for unhandled paths.

**Comment by emilgoldsmith** [comment]
Yeah okay, I guess that makes sense
