### ISSUE TITLE
Should Model.preload succeed on inexistent pathsets?

### ISSUE THREAD

**Issue by gautaz** [Netflix/falcor#817]
I am wondering if the fact that [Model.preload](https://netflix.github.io/falcor/doc/Model.html#preload) currently succeeds on inexistent pathsets is on purpose.
If I am preloading some data for future usage, shouldn't I be aware right away that some of it is not available in the model cache (in particular if I have mispelled one of the pathsets I am asking for)?

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

Part of the semantics of preload is that you don't receive any information about what you're preloading. However, if you do want to know which paths are failing or succeeding, you could simply use get() and ignore the result.
