### ISSUE TITLE
Example of using faclor with binary data

### ISSUE THREAD

**Issue by jrabary** [Netflix/falcor#824]
I'm trying to use falcor to develop an image search application. The search is based on image content rather than  textual description. The idea is to let user upload an image in the client UI and the most similar images using some criteria based on its content will be returned by the server. I can't figure out how to build a route that accepts a binary data (the image content) as search argument. Most of the examples out there are using strings.

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

I can't advise on particular implementation details, but in theory you should be able to define whatever transport mechanism you want via implementing your own DataSource. I'll assume you have an ArrayBuffer representing the raw bytes of your image, at which point you could either base64 encode it, naively stringify it, or send it to the server as a binary content-type (I'm hand waving on the latter, but assume it's possible). You'd just need to decide what to do with it on your server, which is entirely dependent on your implementation there. Hope this helps, going to close this as part of cleanup. Feel free to follow up if you need more though.
