### ISSUE TITLE
Avoid refecth of invalidated data

### ISSUE THREAD

**Issue by drFabio** [Netflix/falcor#825]
If I have a call route that invalidate a deleted data is there a way to not try to refetch it  ? Since it was deleted this would be an unnecessary server call.

Should there be a different metadata such as removed instead of invalidate?

**Comment by trxcllnt** [comment]
@drFabio yes, instead you should set it to `null`, or `undefined`. invalidate is meant to indicate to the cache that some fragment it stale, should be deleted, and re-requested from the server next time.

**Comment by drFabio** [comment]
That makes sense, thanks. My only issue would be that I can't remove a key (say something indexed by id) but I think this is not such a drag
