### ISSUE TITLE
GraphQL-style arguments in Falcor

### ISSUE THREAD

**Issue by abetkin** [Netflix/falcor#826]
Hi everyone and thank you for building Falcor! Imho it is not just a minimalist solution in comparison with GraphQL but a well-thought data source abstraction designed for composability and microservices.

I know GraphQL supports keyword arguments in get-queries and Falcor does not. But how difficult will it be to add this support either by PR or third-party code? Let me show on an example what I mean. I don't have hands-on experience with falcor so forgive me possible inaccuracy in code.

Consider a path set that gives a list of books, something like
 
```
['books', {to: 5}, ['title', 'content']]
```

Suppose we want to add an "order by" argument so that the result contained references to books. Something like what is described [here](http://stackoverflow.com/questions/37559073/how-to-present-sort-order-by-query-in-falcor/37976470#37976470).

I see a way of doing this just in adding an item to the path, that in simplest case can be just a string containing json with arguments.

```
['books', '{"order_by": "title"}', {to: 5}, ['title', 'content']]
```

 The results will be cached as usual for this new path (with items-arguments). Instead of `{"order_by": "title"}` there could be just arbitrary JSON structure.

But it should be easy or at least possible to filter out the arguments from the path for the router or the data source. Which also doesn't seem unsolvable to me.

What do you think, is there some generic way of doing this?

Another possible option may be having some special `call` operation which will be this customized `get` operation (`get` with parameters). What do you think?

**Comment by abetkin** [comment]
Also, falcor repo doesn't seem too active, so @jhusain excuse me for this ping :)

**Comment by hgwood** [comment]
What would be the advantage over the already-working `['book', 'orderBy', 'title', {to: 5}, ['title', 'content']`?

**Comment by abetkin** [comment]
Semantically it's the same path as `['books', {to: 5}, ['title', 'content']]`, it's only a different path for caching logic. I was curios if there is an easy and generic way to make such paths processed by a single handler, without the need to return `ref` in every single case.

**Comment by abetkin** [comment]
@hgwood Also, suppose the arguments would be `{"orderBy": "title", "filter": "free"}`. What path will you make, this: `['book', 'orderBy', 'title', 'filter', 'free', {to: 5}, ['title', 'content']]` ?

**Comment by hgwood** [comment]
OK I see. You want multiple unordered parameters. Have a look here: https://github.com/Netflix/falcor/issues/775

**Comment by abetkin** [comment]
Yes, that is it

**Comment by abetkin** [comment]
Just how adequate it sounds to have `get(pathSet, json)` as HttpDataSource interface instead of `get(pathSet)`? Here `json` is parameters that should be used for this pathset query.

We also will need the client to take into account this `json` when caching results.

The paths in my proposal do not contain any arguments (any of `{city: 'New York', state: 'New York', lowPrice: 1000, highPrice: 3000}`)

**Comment by trxcllnt** [comment]
@abetkin Falcor takes the stance that it's appropriate to encode the query parameters into the path. This allows the results to be cached locally, but also enables the get requests to be batched together into a single request (and in our @graphistry forks of the client and router, streamed in over time).

**Comment by abetkin** [comment]
@trxcllnt You are right, given the stuff like requests batching exist, there will be no performance penalty from including parameters in paths. Still there  might be a way to handle them in a special way, so that the server-side code (router and the data source) could make the distinction between paths and arguments.

**Comment by abetkin** [comment]
For the sake of completeness, here is how it might look like.

You put the arguments right after the path item in some special format, ex. starting with `|args|` prefix, like in this orderBy example:

``` ['books', '|args|{"order_by": "title"}', {to: 5}, ['title', 'content']]```

Nothing changes at the client side, paths with args and without are cached separately.

On the server side however, your data source or the router if you use it, can understand this special path items, and separate them from the rest of the path.

For example, the router's get method might look as follows:

```javascript
var router = new Router([
    {
        route: "books[{range}]['title', 'content']",
        get: function (pathSet, getArgs) {
            return pathSet.map(function(path) {
                let bookArgs = getArgs(path + '/../..')
                # ...
            })
        }
    }
]);
```

Any thoughts about that?

**Comment by steveorsomethin** [comment]
I'm currently performing triage on the falcor issues, and closing/tagging as I go.

+1 to Paul's answer. @abetkin, we're internally using a stringified object as part of a path to solve the same problem, so it's definitely the solution I would recommend. Note that you should be careful to keep keys in the same order if you want caching. We're unlikely to support anything like the prefix however.
