### ISSUE TITLE
programatically handle routes, or routes with wild cards

### ISSUE THREAD

**Issue by drFabio** [Netflix/falcor#827]
Is there a way to programatically handle all uncatched routes or have a wild card ?
Say I want to implement a sort on several documents ASC and DESC, I then have 2* the routes that need to be written at startup.

Is there a way to have something like : "foo_sorteBy.*[{keys: fields}]" ?

**Comment by dbslone** [comment]
@drFabio this wouldn't be considered a best practice but instead of using `get` you could use `call` which allows you pass additional arguments to falcor.

```
// Client Side
falcor.call(['foo_sorted', 0, 'title'], ['DESC'])

// Server Side
{
    route: 'foo_sorted[{integers:indices}][{keys:props}]'
    call (callPath, args) {
         // callPath => JSON Graph path
         // args[0] => 'DESC'
    }
}
```

**Comment by trxcllnt** [comment]
@drFabio you can also write routes with sort keys like this: `myList[{ keys: sortKey }]['leaf', 'keys', 'etc']`, then request for `model.get('myList.asc['leaf', 'keys', 'etc'])`
