### ISSUE TITLE
Module not found: Error: Can't resolve 'rx' in './node_modules/falcor/node_modules/rx/dist'

### ISSUE THREAD

**Issue by krainboltgreene** [Netflix/falcor#833]
We're on the latest released webpack (`"2.2.1"`).
We're on the latest released falcor (`"0.1.17"`).
We're on the latest babel (`"6.23.0"`).

However, when I try to compile my frontend I get this error: https://gist.github.com/krainboltgreene/831a78e3b48b29266568cfc50636ed06

I know there's a note on the README.md, but I attempted to try that and it only produced more issues.

What do I do?

**Comment by mattiaerre** [comment]
Hi @krainboltgreene 
I remember I've had the same issue (not 100% sure tbf).
And I think I've been able to fix it installing explicitly `rx`:

https://github.com/mattiaerre/supersonic-lobster/blob/master/package.json#L73

let me know how it goes.

**Comment by trxcllnt** [comment]
@krainboltgreene @mattiaerre you can also try installing our [@graphistry fork](https://github.com/graphistry/falcor/tree/master/packages/falcor), which has support for a number of new features, and doesn't depend on Rx anymore. The only backwards-incompatible change we've made was to remove falcor-path-syntax from the core lib. Alternatively, if you want an RxJS5-powered model _with_ path-syntax support, you can import [`@graphistry/falcor-model-rxjs`](https://www.npmjs.com/package/@graphistry/falcor-model-rxjs). Feel free to open an issue in our repo with any questions.

**Comment by krainboltgreene** [comment]
Hey, thanks for the advice!

So while my webpack now safely compiles, when I load the page I get an error that I'm fairly sure is attributed to this change:

```
Uncaught TypeError: Cannot read property 'apply' of undefined
    at observableMergeObject (eval at <anonymous> (rest.bundle.js:9099), <anonymous>:14:75)
    at eval (eval at <anonymous> (rest.bundle.js:17205), <anonymous>:14:151)
    at Object.<anonymous> (rest.bundle.js:17205)
    at __webpack_require__ (rest.bundle.js:660)
    at fn (rest.bundle.js:84)
    at eval (eval at <anonymous> (rest.bundle.js:14755), <anonymous>:1:69)
    at Object.<anonymous> (rest.bundle.js:14755)
    at __webpack_require__ (rest.bundle.js:660)
    at fn (rest.bundle.js:84)
    at eval (eval at <anonymous> (rest.bundle.js:14727), <anonymous>:15:69)
```

And `rest.bundle.js:9099` points to:

```
(function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_babel_runtime_helpers_toConsumableArray__ = __webpack_require__(30);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_babel_runtime_helpers_toConsumableArray___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0_babel_runtime_helpers_toConsumableArray__);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_rxjs_Observable__ = __webpack_require__(291);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_rxjs_Observable___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1_rxjs_Observable__);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2_lodash__ = __webpack_require__(7);\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2_lodash___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_2_lodash__);\n/* harmony export (immutable) */ __webpack_exports__[\"a\"] = observableMergeObject;\n\n\n\n\nfunction observableMergeObject(obs) {\n\n  return __WEBPACK_IMPORTED_MODULE_1_rxjs_Observable__[\"Observable\"].merge.apply(__WEBPACK_IMPORTED_MODULE_1_rxjs_Observable__[\"Observable\"], __WEBPACK_IMPORTED_MODULE_0_babel_runtime_helpers_toConsumableArray___default()(__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_2_lodash__[\"values\"])(obs)));\n}//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiMTI4MS5qcyIsInNvdXJjZXMiOlsid2VicGFjazovLy8uL2FwcC9hc3NldHMvamF2YXNjcmlwdHMvcGFja2FnZXMvdXRpbHMvbW9kdWxlcy9vYnNlcnZhYmxlLW1lcmdlLW9iamVjdC5qcz8yYzc0Il0sInNvdXJjZXNDb250ZW50IjpbImltcG9ydCBfdG9Db25zdW1hYmxlQXJyYXkgZnJvbSAnYmFiZWwtcnVudGltZS9oZWxwZXJzL3RvQ29uc3VtYWJsZUFycmF5JztcbmltcG9ydCB7IE9ic2VydmFibGUgfSBmcm9tICdyeGpzL09ic2VydmFibGUnO1xuaW1wb3J0IHsgdmFsdWVzIH0gZnJvbSAnbG9kYXNoJztcblxuZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gb2JzZXJ2YWJsZU1lcmdlT2JqZWN0KG9icykge1xuXG4gIHJldHVybiBPYnNlcnZhYmxlLm1lcmdlLmFwcGx5KE9ic2VydmFibGUsIF90b0NvbnN1bWFibGVBcnJheSh2YWx1ZXMob2JzKSkpO1xufVxuXG5cbi8vLy8vLy8vLy8vLy8vLy8vL1xuLy8gV0VCUEFDSyBGT09URVJcbi8vIC4vYXBwL2Fzc2V0cy9qYXZhc2NyaXB0cy9wYWNrYWdlcy91dGlscy9tb2R1bGVzL29ic2VydmFibGUtbWVyZ2Utb2JqZWN0LmpzXG4vLyBtb2R1bGUgaWQgPSAxMjgxXG4vLyBtb2R1bGUgY2h1bmtzID0gMCAxIl0sIm1hcHBpbmdzIjoiQUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EiLCJzb3VyY2VSb290IjoiIn0=");

/***/ })
```

**Comment by krainboltgreene** [comment]
Actually, turns out `observableMergeObject` is defined in our project. I'm investigating that now.

**Comment by krainboltgreene** [comment]
Okay, that was unrelated to the change just how we were incorrectly using `rxjs`, however, I seem to be getting this which is both related to `falcor` and this `rx` issue:

```
TypeError: this._subscribe is not a function
    at CallResponse.Rx.Observable.observableProto.subscribe.observableProto.forEach (rest.bundle.js:223369)
    at ModelResponse.subscribeToResponse [as _subscribe] (rest.bundle.js:43488)
    at ModelResponse.subscribe (rest.bundle.js:43436)
    at ToArrayObservable.subscribeCore (rest.bundle.js:223825)
    at ToArrayObservable.tryCatcher (rest.bundle.js:221398)
    at Rx.internals.ScheduledItem.setDisposable [as action] (rest.bundle.js:223417)
    at Rx.internals.ScheduledItem.ScheduledItem.invokeCore (rest.bundle.js:222315)
    at Rx.internals.ScheduledItem.ScheduledItem.invoke (rest.bundle.js:222303)
    at runTrampoline (rest.bundle.js:222544)
    at tryCatcher (rest.bundle.js:221398)
```

**Comment by krainboltgreene** [comment]
I might just close this and make a new issue.

**Comment by mattiaerre** [comment]
@krainboltgreene as per @trxcllnt comment you can try to use their lib. I've just updated a project w/ it and it went pretty well. Let us know if you need other help w/ the issue you are having and feel free to tag me to the new one if you like.

**Comment by sdesai** [comment]
@krainboltgreene - Is it possible for me to take a look at the repo to try building myself? Rolling the conversation back to your original problem. I think it's just a webpack configuration tweak, to fix that. Alternatively, master (not published on npm yet) doesn't have the Rx dependency (for dev dependencies), however this is the upgrade README (so far) : https://github.com/Netflix/falcor/blob/master/MIGRATIONS.md
