### ISSUE TITLE
MaxRetryExceededError cannot be caught

### ISSUE THREAD

**Issue by jmerrifield** [Netflix/falcor#837]
If a `MaxRetryExceededError` is encountered, it is thrown from within an async callback, leading to a process-level uncaught exception. It should probably be propagated with something like `observer.onError(new MaxRetryExceededError());` instead of `throw new MaxRetryExceededError();`.

**Comment by jhusain** [comment]
Thanks for putting this. This issue will be fixed soon.

**Comment by jhusain** [comment]
https://github.com/Netflix/falcor/pull/844

**Comment by jmerrifield** [comment]
Thanks for the quick fix!
