### ISSUE TITLE
Immuable collection IDs

### ISSUE THREAD

**Issue by neftaly** [Netflix/falcor#849]
Hey! We've been evaluating Falcor for use with an "AP" database, and have run into a problem when looking up a collection of refs.

Our data is currently kept as a map of objects, with unique keys (UUIDs, truncated for this example):
```json
"tree": {
  "ea13b99f": { "name": "leaf 1" },
  "a2c9d75d": { "name": "leaf 2" },
  "d36395c5": { "name": "leaf 3" },

  "9e0e5531": {
    "name": "branch - list",
    "children": [
      {
        "$type": "ref",
        "value": [ "tree", "ea13b99f" ]
      },
      {
        "$type": "ref",
        "value": [ "tree", "a2c9d75d" ]
      },
      {
        "$type": "ref",
        "value": [ "tree", "d36395c5" ]
      }
    ]
  },

  "zb3749bd": {
    "name": "branch - map",
    "children": {
      "ea13b99f": {
        "$type": "ref",
        "value": [ "tree", "ea13b99f" ]
      },
      "a2c9d75d": {
        "$type": "ref",
        "value": [ "tree", "a2c9d75d" ]
      },
      "d36395c5": {
        "$type": "ref",
        "value": [ "tree", "d36395c5" ]
      }
    }
  }
}
```

Running this works fine:
```js
model.get(
  [ 'tree', '9e0e5531', 'name' ],
  [ 'tree', '9e0e5531', 'children', { to: 10 } ]
)
```

But there's a problem with our use-case. We require idempotent operations, and as such we'd like `children` to be a map (a collection of explicit unique keys), instead of an array (a collection of implicit numerical keys). 

In the undesired scenario, if two users were to attempt to delete tree.zb3749bd.children.0, tree.zb3749bd.children.length = 1.
In the desired scenario, if two users were to attempt to delete tree.9e0e5531.children.ea13b99f, tree.9e0e5531.children.length = 2.

Is it possible to run something like this? The range operation would get the first 10 keys from `children` (sorted by key) and return pretty much the same thing as the get operation above.
```js
model.get(
  [ 'tree', 'zb3749bd', 'name' ],
  [ 'tree', 'zb3749bd', 'children', { to: 10 } ]
)
```

Otherwise, is there some other way to perform idempotent operations on lists?

**Comment by asyncanup** [comment]
@neftaly glad to hear you were evaluating falcor :)
if you don't prefer numeric key ranges, you can always use explicit string keys as follows:
```
model.get(
  [ 'tree', 'zb3749bd', 'name' ],
  [ 'tree', 'zb3749bd', 'children', [ 'ea13b99f', 'dju47fu2', 'kloiu89f' ] ]
)
```

Does that answer your question?

**Comment by neftaly** [comment]
@asyncanup Looks so, thanks for your help!
