### ISSUE TITLE
Status of RxJS / webpack

### ISSUE THREAD

**Issue by val-samonte** [Netflix/falcor#867]
The webpack issue with RxJS is 2 years ago (https://github.com/Reactive-Extensions/RxJS/issues/832). Is this already been resolved without relying in "alias"? I can't use Falcor into my Angular 4 project generated by the CLI. I have an option to "ng eject" from it just to get the webpack.config, but I really don't want to mess with it.

**Comment by steveorsomethin** [comment]
What version of falcor are you using? We've published 2.0.0-rc1 if you'd like to try it (or 1.0.0-rc2 as explained in #864). In both cases Rx is no longer a direct dependency, which means that if you continue having issues there's something specific to falcor going on.

If you're still having an issue with 1.x or 2.x, could you dump some more info here?

**Comment by steveorsomethin** [comment]
Also, I've published 2.0.0-rc2 and 1.0.0-rc3 as it looks like rx was erroneously not yet moved into devDependencies (fixed in #868).

**Comment by sdesai** [comment]
@val-samonte - The 1.0.0 release, which we published to npm last week, should have resolved this, in addition to the 2.0.0-rc2 mentioned above. Closing out for now, but feel free to re-open if you're still seeing it with 1.0.0, for example.
