### ISSUE TITLE
Should `falcor.HttpDataSource` be exposed in Node.js require as well?

### ISSUE THREAD

**Issue by asyncanup** [Netflix/falcor#884]
Just like it is exposed in the browser build.

**Comment by lrowe** [comment]
From Node it makes more sense to directly import it directly from falcor-http-datasource. We want to avoid a runtime dependency on it since many users will have their own datasource implementation.

**Comment by greim** [comment]
This was exactly the case with me. Had to roll my own and definitely wouldn't want the extra weight in my bundle.

**Comment by asyncanup** [comment]
Sounds good, thanks for the discussion :)
