### ISSUE TITLE
subset of path/router

### ISSUE THREAD

**Issue by rajexcited** [Netflix/falcor#901]
Can you allow request path to have subset ?

example,
server is defining route:
route:    "book[{keys:title}]"

on client side,
when book is available, I need to find pages by chapter or by page number or  by sub topics.
the current falcor version for the above route is not capable enough to give me these details even though its jsonGraph has everything.

1. getModel("book['gameOfThrones']")
2. getModel("book[['gameOfThrones']['chapter-1','chapter-5']")
3. getModel("book[['gameOfThrones']['page-23 to 30']")

**Comment by asyncanup** [comment]
you can define the following routes on server to capture those paths:

```
route: 'book[{keys:title}]'
route: 'book[{keys:title}].chapters[{integers:chapterNumbers}]'
route: 'book[{keys:title}].pages[{integers:pageNumbers}]'
```

and return relevant parts of your jSONGraph from these routes.
Does that solve your issue?
