### ISSUE TITLE
add an observe method to the model

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#91]
Internal customers and external customers have asked for an observe method on the model.The observe method has the exact same signature as the get method, but the observable that it returns never completes.

 The simplest implementation I can imagine is simply to keep a list of observed paths inside of the model and run a get operation for them after every single set operation. This implementation can be optimized somewhat using the version flag to avoid full traversals.

**Comment by Zolmeister** [comment]
:+1: This is the reason I want to use Falcor
https://zorium.org/tutorial/streams

**Comment by michaelbpaulson** [comment]
@jhusain @ktrott @sdesai we have determined that observe will not happen. could we please close this issue if thats the case.
