### ISSUE TITLE
Recent upgrades to dev dependencies is causing dist to silently fail

### ISSUE THREAD

**Issue by steveorsomethin** [Netflix/falcor#911]
At least, I am speculating that the upgrades are the root cause. Running ```npm run dist``` now only cleans the dist directory, and the build task simply silently exits.

**Comment by steveorsomethin** [comment]
cc @asyncanup in case you have any quick gut feeling on what might have changed.

**Comment by asyncanup** [comment]
https://github.com/Netflix/falcor/pull/913
was due to a breaking api change in del@3.0.0
