### ISSUE TITLE
Limitations of Falcor

### ISSUE THREAD

**Issue by pavle-lekic-htec** [Netflix/falcor#948]
Hi :) Thanks for this wonderful project and all the effort that you invested.

I think it would be *very* helpful to know Falcor limitations in advance so that people who are looking into including Falcor in their projects could know if it is a good fit for them or not, or if they should go for some more general solution like GraphQL. Currently I haven't found such explanation, and I think it would be painful to figure out that Falcor is not for you once you invested month or two rewriting everything to use Falcor.

**Comment by jcranendonk** [comment]
Hi @pavle-lekic-htec! That's a great point, thank you for pointing out that oversight in the documentation. While we work on fixing that, here's a few articles to get you started:

- https://stackoverflow.com/questions/32057785/what-is-the-difference-between-falcor-and-graphql
- https://blog.apollographql.com/graphql-vs-falcor-4f1e9cbf7504
- https://edgecoders.com/the-falcor-data-model-is-a-graph-and-the-graphql-data-model-is-a-tree-6748ba53bb96

These articles compare Falcor with GraphQL, but their lists of pros and cons should give you an idea of where Falcor works well, and where you may wish to look for other tools.

If there's any particular use cases on your mind, let us know and we'll help address it.

**Comment by hbbio** [comment]
Thanks @jcranendonk 

I'm looking into Falcor for a project right now as a runtime for generated code. I notice there are few commits these last months and few issues as well. Is Falcor still maintained and can we have reasonable expectations that it will still be the case in the (near) future?

**Comment by jcranendonk** [comment]
Falcor is in heavy use across Netflix and we're committed to maintaining the library for the forseeable future. Currently development is driven mainly by internal requirements, but you can expect to see more updates throughout 2019.
