### ISSUE TITLE
GET url limitation on IE

### ISSUE THREAD

**Issue by zeniroy** [Netflix/falcor#950]
I am testing falcor on IE. And i figured out that long falcor request failed because of IE limitation of Get Url. (2083 byte)

Is there any way to avoid this limitation in the falcor system?

Now, I am using multiple batch models for this problem but it's not that efficient.

**Comment by jameslaneconkling** [comment]
You should be able to implement your own DataSource that uses `POST` requests for long falcor `GET` requests.

I haven't looked too deeply, but in Netflix's own [HTTPDataSource implementation here](https://github.com/Netflix/falcor-http-datasource/blob/master/src/XMLHttpSource.js#L39-L49), you should be able to change the HTTP request type from a `GET` to a `POST` if the length of the `queryObject` is longer than [2083 (or whatever)](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers).

**Comment by zeniroy** [comment]
ah. ok. Thanx for reply.
