### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by DenrizSusam** [Netflix/falcor#953]
http://netflix.github.io/falcor/documentation/model.html#model-overview

"4. Navigating information hierarchically rather than retrieving information using id’s can lead to <b>inefficent</b> back-end requests."

"inefficent" should be "inefficient".

I would open a PR but I could not find this part of the documentation in the repo :/ .

**Comment by jcranendonk** [comment]
https://github.com/Netflix/falcor/blob/gh-pages/documentation/model.md

You fix it, I'll merge it :)

**Comment by jcranendonk** [comment]
Fixed in https://github.com/Netflix/falcor/pull/954
