### ISSUE TITLE
Falcor can integrate with mongoose?

### ISSUE THREAD

**Issue by wizardnet972** [Netflix/falcor#967]
Does Falcor have integration to mongoose? or if I want to get a model or do any CRUD operation, I need to write a function which parse the query and return the results from mongoose model?

**Comment by jcranendonk** [comment]
The library does not currently provide integration with Mongoose or MongoDB. Falcor and Mongoose both offer similar functionality, in providing data modeling tools and query building, but the Falcor client library does not depend on or require any particular persistence service.

If you're looking to provide a Falcor interface to a MongoDB server, you could write an implementation of the [DataSource interface](https://netflix.github.io/falcor/documentation/datasources.html) to target that particular backend.
